window.vocabularyBank = [
  { id: "D01-W01", day: 1, type: "word", japanese: "～である", answer: "be", hint: "", similar: [] },
  { id: "D01-W02", day: 1, type: "word", japanese: "持っている", answer: "have", hint: "", similar: [] },
  { id: "D01-W03", day: 1, type: "word", japanese: "する", answer: "do", hint: "", similar: [] },
  { id: "D01-W04", day: 1, type: "word", japanese: "作る", answer: "make", hint: "", similar: [] },
  { id: "D01-W05", day: 1, type: "word", japanese: "取る・持っていく", answer: "take", hint: "", similar: [ { answer: "bring", reason: "話し手側から持っていく" } ] },
  { id: "D01-W06", day: 1, type: "word", japanese: "得る", answer: "get", hint: "", similar: [] },
  { id: "D01-W07", day: 1, type: "word", japanese: "行く", answer: "go", hint: "", similar: [ { answer: "come", reason: "話し手側から離れる" } ] },
  { id: "D01-W08", day: 1, type: "word", japanese: "来る", answer: "come", hint: "", similar: [ { answer: "go", reason: "話し手側へ来る" } ] },
  { id: "D01-W09", day: 1, type: "word", japanese: "見る", answer: "see", hint: "", similar: [ { answer: "look", reason: "意識して見る" }, { answer: "watch", reason: "動いているものを見る" } ] },
  { id: "D01-W10", day: 1, type: "word", japanese: "見る", answer: "look", hint: "", similar: [ { answer: "see", reason: "自然に目に入る" }, { answer: "watch", reason: "動いているものを見る" } ] },
  { id: "D01-W11", day: 1, type: "word", japanese: "（じっと）見る", answer: "watch", hint: "", similar: [ { answer: "see", reason: "自然に目に入る" }, { answer: "look", reason: "意識して見る" } ] },
  { id: "D01-W12", day: 1, type: "word", japanese: "聞こえる", answer: "hear", hint: "", similar: [ { answer: "listen", reason: "意識して聞く" } ] },
  { id: "D01-W13", day: 1, type: "word", japanese: "聞く", answer: "listen", hint: "", similar: [ { answer: "hear", reason: "自然に聞こえる" } ] },
  { id: "D01-W14", day: 1, type: "word", japanese: "話す", answer: "speak", hint: "", similar: [ { answer: "say", reason: "言葉を言う" }, { answer: "tell", reason: "相手に伝える" }, { answer: "talk", reason: "会話する" } ] },
  { id: "D01-W15", day: 1, type: "word", japanese: "言う", answer: "say", hint: "", similar: [ { answer: "tell", reason: "相手に伝える" }, { answer: "speak", reason: "言語を話す" }, { answer: "talk", reason: "会話する" } ] },
  { id: "D01-W16", day: 1, type: "word", japanese: "伝える", answer: "tell", hint: "", similar: [ { answer: "say", reason: "言葉を言う" }, { answer: "speak", reason: "言語を話す" }, { answer: "talk", reason: "会話する" } ] },
  { id: "D01-W17", day: 1, type: "word", japanese: "話す", answer: "talk", hint: "", similar: [ { answer: "say", reason: "言葉を言う" }, { answer: "tell", reason: "相手に伝える" }, { answer: "speak", reason: "言語を話す" } ] },
  { id: "D01-W18", day: 1, type: "word", japanese: "尋ねる", answer: "ask", hint: "", similar: [] },
  { id: "D01-W19", day: 1, type: "word", japanese: "答える", answer: "answer", hint: "", similar: [] },
  { id: "D01-W20", day: 1, type: "word", japanese: "知っている", answer: "know", hint: "", similar: [] },
  { id: "D01-P01", day: 1, type: "phrase", japanese: "～に興味がある", answer: "be interested in", hint: "", similar: [] },
  { id: "D01-P02", day: 1, type: "phrase", japanese: "～が得意", answer: "be good at", hint: "", similar: [] },
  { id: "D01-P03", day: 1, type: "phrase", japanese: "～で有名", answer: "be famous for", hint: "", similar: [] },
  { id: "D01-P04", day: 1, type: "phrase", japanese: "～を見る", answer: "look at", hint: "", similar: [] },
  { id: "D01-P05", day: 1, type: "phrase", japanese: "～を聞く", answer: "listen to", hint: "", similar: [] },
  { id: "D02-W01", day: 2, type: "word", japanese: "考える", answer: "think", hint: "", similar: [] },
  { id: "D02-W02", day: 2, type: "word", japanese: "理解する", answer: "understand", hint: "", similar: [] },
  { id: "D02-W03", day: 2, type: "word", japanese: "学ぶ", answer: "learn", hint: "", similar: [] },
  { id: "D02-W04", day: 2, type: "word", japanese: "勉強する", answer: "study", hint: "", similar: [] },
  { id: "D02-W05", day: 2, type: "word", japanese: "教える", answer: "teach", hint: "", similar: [] },
  { id: "D02-W06", day: 2, type: "word", japanese: "読む", answer: "read", hint: "", similar: [] },
  { id: "D02-W07", day: 2, type: "word", japanese: "書く", answer: "write", hint: "", similar: [] },
  { id: "D02-W08", day: 2, type: "word", japanese: "使う", answer: "use", hint: "", similar: [] },
  { id: "D02-W09", day: 2, type: "word", japanese: "助ける", answer: "help", hint: "", similar: [] },
  { id: "D02-W10", day: 2, type: "word", japanese: "働く", answer: "work", hint: "", similar: [] },
  { id: "D02-W11", day: 2, type: "word", japanese: "行く", answer: "go", hint: "", similar: [ { answer: "come", reason: "話し手側から離れる" } ] },
  { id: "D02-W12", day: 2, type: "word", japanese: "来る", answer: "come", hint: "", similar: [ { answer: "go", reason: "話し手側へ来る" } ] },
  { id: "D02-W13", day: 2, type: "word", japanese: "聞く", answer: "listen", hint: "", similar: [ { answer: "hear", reason: "自然に聞こえる" } ] },
  { id: "D02-W14", day: 2, type: "word", japanese: "話す", answer: "speak", hint: "", similar: [ { answer: "say", reason: "言葉を言う" }, { answer: "tell", reason: "相手に伝える" }, { answer: "talk", reason: "会話する" } ] },
  { id: "D02-W15", day: 2, type: "word", japanese: "尋ねる", answer: "ask", hint: "", similar: [] },
  { id: "D02-W16", day: 2, type: "word", japanese: "答える", answer: "answer", hint: "", similar: [] },
  { id: "D02-W17", day: 2, type: "word", japanese: "知っている", answer: "know", hint: "", similar: [] },
  { id: "D02-W18", day: 2, type: "word", japanese: "持っている", answer: "have", hint: "", similar: [] },
  { id: "D02-W19", day: 2, type: "word", japanese: "作る", answer: "make", hint: "", similar: [] },
  { id: "D02-W20", day: 2, type: "word", japanese: "得る", answer: "get", hint: "", similar: [] },
  { id: "D02-P01", day: 2, type: "phrase", japanese: "～を探す", answer: "look for", hint: "", similar: [] },
  { id: "D02-P02", day: 2, type: "phrase", japanese: "～を待つ", answer: "wait for", hint: "", similar: [] },
  { id: "D02-P03", day: 2, type: "phrase", japanese: "～について話す", answer: "talk about", hint: "", similar: [] },
  { id: "D02-P04", day: 2, type: "phrase", japanese: "～に興味がある", answer: "be interested in", hint: "", similar: [] },
  { id: "D02-P05", day: 2, type: "phrase", japanese: "～を聞く", answer: "listen to", hint: "", similar: [] },
  { id: "D03-W01", day: 3, type: "word", japanese: "遊ぶ・する", answer: "play", hint: "", similar: [] },
  { id: "D03-W02", day: 3, type: "word", japanese: "走る", answer: "run", hint: "", similar: [] },
  { id: "D03-W03", day: 3, type: "word", japanese: "歩く", answer: "walk", hint: "", similar: [] },
  { id: "D03-W04", day: 3, type: "word", japanese: "食べる", answer: "eat", hint: "", similar: [] },
  { id: "D03-W05", day: 3, type: "word", japanese: "飲む", answer: "drink", hint: "", similar: [] },
  { id: "D03-W06", day: 3, type: "word", japanese: "買う", answer: "buy", hint: "", similar: [] },
  { id: "D03-W07", day: 3, type: "word", japanese: "売る", answer: "sell", hint: "", similar: [] },
  { id: "D03-W08", day: 3, type: "word", japanese: "支払う", answer: "pay", hint: "", similar: [] },
  { id: "D03-W09", day: 3, type: "word", japanese: "与える", answer: "give", hint: "", similar: [] },
  { id: "D03-W10", day: 3, type: "word", japanese: "見せる", answer: "show", hint: "", similar: [] },
  { id: "D03-W11", day: 3, type: "word", japanese: "考える", answer: "think", hint: "", similar: [] },
  { id: "D03-W12", day: 3, type: "word", japanese: "勉強する", answer: "study", hint: "", similar: [] },
  { id: "D03-W13", day: 3, type: "word", japanese: "読む", answer: "read", hint: "", similar: [] },
  { id: "D03-W14", day: 3, type: "word", japanese: "書く", answer: "write", hint: "", similar: [] },
  { id: "D03-W15", day: 3, type: "word", japanese: "使う", answer: "use", hint: "", similar: [] },
  { id: "D03-W16", day: 3, type: "word", japanese: "助ける", answer: "help", hint: "", similar: [] },
  { id: "D03-W17", day: 3, type: "word", japanese: "知っている", answer: "know", hint: "", similar: [] },
  { id: "D03-W18", day: 3, type: "word", japanese: "話す", answer: "speak", hint: "", similar: [ { answer: "say", reason: "言葉を言う" }, { answer: "tell", reason: "相手に伝える" }, { answer: "talk", reason: "会話する" } ] },
  { id: "D03-W19", day: 3, type: "word", japanese: "話す", answer: "talk", hint: "", similar: [ { answer: "say", reason: "言葉を言う" }, { answer: "tell", reason: "相手に伝える" }, { answer: "speak", reason: "言語を話す" } ] },
  { id: "D03-W20", day: 3, type: "word", japanese: "教える", answer: "teach", hint: "", similar: [] },
  { id: "D03-P01", day: 3, type: "phrase", japanese: "～について考える", answer: "think about", hint: "", similar: [] },
  { id: "D03-P02", day: 3, type: "phrase", japanese: "～しなければならない", answer: "have to", hint: "", similar: [] },
  { id: "D03-P03", day: 3, type: "phrase", japanese: "～したい", answer: "want to", hint: "", similar: [] },
  { id: "D03-P04", day: 3, type: "phrase", japanese: "～を探す", answer: "look for", hint: "", similar: [] },
  { id: "D03-P05", day: 3, type: "phrase", japanese: "～を待つ", answer: "wait for", hint: "", similar: [] },
  { id: "D04-W01", day: 4, type: "word", japanese: "持ってくる", answer: "bring", hint: "", similar: [ { answer: "take", reason: "話し手側へ持ってくる" } ] },
  { id: "D04-W02", day: 4, type: "word", japanese: "送る", answer: "send", hint: "", similar: [] },
  { id: "D04-W03", day: 4, type: "word", japanese: "会う", answer: "meet", hint: "", similar: [] },
  { id: "D04-W04", day: 4, type: "word", japanese: "訪れる", answer: "visit", hint: "", similar: [] },
  { id: "D04-W05", day: 4, type: "word", japanese: "旅行する", answer: "travel", hint: "", similar: [] },
  { id: "D04-W06", day: 4, type: "word", japanese: "滞在する", answer: "stay", hint: "", similar: [] },
  { id: "D04-W07", day: 4, type: "word", japanese: "住む", answer: "live", hint: "", similar: [] },
  { id: "D04-W08", day: 4, type: "word", japanese: "動く・引っ越す", answer: "move", hint: "", similar: [] },
  { id: "D04-W09", day: 4, type: "word", japanese: "開ける", answer: "open", hint: "", similar: [] },
  { id: "D04-W10", day: 4, type: "word", japanese: "閉める", answer: "close", hint: "", similar: [] },
  { id: "D04-W11", day: 4, type: "word", japanese: "遊ぶ・する", answer: "play", hint: "", similar: [] },
  { id: "D04-W12", day: 4, type: "word", japanese: "走る", answer: "run", hint: "", similar: [] },
  { id: "D04-W13", day: 4, type: "word", japanese: "歩く", answer: "walk", hint: "", similar: [] },
  { id: "D04-W14", day: 4, type: "word", japanese: "食べる", answer: "eat", hint: "", similar: [] },
  { id: "D04-W15", day: 4, type: "word", japanese: "飲む", answer: "drink", hint: "", similar: [] },
  { id: "D04-W16", day: 4, type: "word", japanese: "買う", answer: "buy", hint: "", similar: [] },
  { id: "D04-W17", day: 4, type: "word", japanese: "支払う", answer: "pay", hint: "", similar: [] },
  { id: "D04-W18", day: 4, type: "word", japanese: "与える", answer: "give", hint: "", similar: [] },
  { id: "D04-W19", day: 4, type: "word", japanese: "見せる", answer: "show", hint: "", similar: [] },
  { id: "D04-W20", day: 4, type: "word", japanese: "助ける", answer: "help", hint: "", similar: [] },
  { id: "D04-P01", day: 4, type: "phrase", japanese: "～する必要がある", answer: "need to", hint: "", similar: [] },
  { id: "D04-P02", day: 4, type: "phrase", japanese: "～したいと思う", answer: "hope to", hint: "", similar: [] },
  { id: "D04-P03", day: 4, type: "phrase", japanese: "～することを決める", answer: "decide to", hint: "", similar: [] },
  { id: "D04-P04", day: 4, type: "phrase", japanese: "～しなければならない", answer: "have to", hint: "", similar: [] },
  { id: "D04-P05", day: 4, type: "phrase", japanese: "～したい", answer: "want to", hint: "", similar: [] },
  { id: "D05-W01", day: 5, type: "word", japanese: "始める", answer: "start", hint: "", similar: [ { answer: "begin", reason: "開始する" } ] },
  { id: "D05-W02", day: 5, type: "word", japanese: "始まる", answer: "begin", hint: "", similar: [ { answer: "start", reason: "開始する" } ] },
  { id: "D05-W03", day: 5, type: "word", japanese: "終える", answer: "finish", hint: "", similar: [ { answer: "stop", reason: "中断/終了の違い" } ] },
  { id: "D05-W04", day: 5, type: "word", japanese: "止める", answer: "stop", hint: "", similar: [ { answer: "finish", reason: "中断/終了の違い" } ] },
  { id: "D05-W05", day: 5, type: "word", japanese: "待つ", answer: "wait", hint: "", similar: [] },
  { id: "D05-W06", day: 5, type: "word", japanese: "電話する", answer: "call", hint: "", similar: [] },
  { id: "D05-W07", day: 5, type: "word", japanese: "見つける", answer: "find", hint: "", similar: [] },
  { id: "D05-W08", day: 5, type: "word", japanese: "失う・負ける", answer: "lose", hint: "", similar: [] },
  { id: "D05-W09", day: 5, type: "word", japanese: "勝つ", answer: "win", hint: "", similar: [] },
  { id: "D05-W10", day: 5, type: "word", japanese: "試す", answer: "try", hint: "", similar: [] },
  { id: "D05-W11", day: 5, type: "word", japanese: "持ってくる", answer: "bring", hint: "", similar: [ { answer: "take", reason: "話し手側へ持ってくる" } ] },
  { id: "D05-W12", day: 5, type: "word", japanese: "送る", answer: "send", hint: "", similar: [] },
  { id: "D05-W13", day: 5, type: "word", japanese: "会う", answer: "meet", hint: "", similar: [] },
  { id: "D05-W14", day: 5, type: "word", japanese: "訪れる", answer: "visit", hint: "", similar: [] },
  { id: "D05-W15", day: 5, type: "word", japanese: "旅行する", answer: "travel", hint: "", similar: [] },
  { id: "D05-W16", day: 5, type: "word", japanese: "滞在する", answer: "stay", hint: "", similar: [] },
  { id: "D05-W17", day: 5, type: "word", japanese: "住む", answer: "live", hint: "", similar: [] },
  { id: "D05-W18", day: 5, type: "word", japanese: "開ける", answer: "open", hint: "", similar: [] },
  { id: "D05-W19", day: 5, type: "word", japanese: "閉める", answer: "close", hint: "", similar: [] },
  { id: "D05-W20", day: 5, type: "word", japanese: "動く", answer: "move", hint: "", similar: [] },
  { id: "D05-P01", day: 5, type: "phrase", japanese: "～しようとする", answer: "try to", hint: "", similar: [] },
  { id: "D05-P02", day: 5, type: "phrase", japanese: "～することを学ぶ", answer: "learn to", hint: "", similar: [] },
  { id: "D05-P03", day: 5, type: "phrase", japanese: "人に～してほしい", answer: "want 人 to", hint: "", similar: [] },
  { id: "D05-P04", day: 5, type: "phrase", japanese: "～する必要がある", answer: "need to", hint: "", similar: [] },
  { id: "D05-P05", day: 5, type: "phrase", japanese: "～することを決める", answer: "decide to", hint: "", similar: [] },
  { id: "D06-W01", day: 6, type: "word", japanese: "望む", answer: "hope", hint: "", similar: [] },
  { id: "D06-W02", day: 6, type: "word", japanese: "決める", answer: "decide", hint: "", similar: [] },
  { id: "D06-W03", day: 6, type: "word", japanese: "覚えている", answer: "remember", hint: "", similar: [] },
  { id: "D06-W04", day: 6, type: "word", japanese: "忘れる", answer: "forget", hint: "", similar: [] },
  { id: "D06-W05", day: 6, type: "word", japanese: "必要とする", answer: "need", hint: "", similar: [] },
  { id: "D06-W06", day: 6, type: "word", japanese: "欲しい", answer: "want", hint: "", similar: [] },
  { id: "D06-W07", day: 6, type: "word", japanese: "楽しむ", answer: "enjoy", hint: "", similar: [] },
  { id: "D06-W08", day: 6, type: "word", japanese: "到着する", answer: "arrive", hint: "", similar: [] },
  { id: "D06-W09", day: 6, type: "word", japanese: "～になる", answer: "become", hint: "", similar: [] },
  { id: "D06-W10", day: 6, type: "word", japanese: "去る・出発する", answer: "leave", hint: "", similar: [] },
  { id: "D06-W11", day: 6, type: "word", japanese: "始める", answer: "start", hint: "", similar: [ { answer: "begin", reason: "開始する" } ] },
  { id: "D06-W12", day: 6, type: "word", japanese: "終える", answer: "finish", hint: "", similar: [ { answer: "stop", reason: "中断/終了の違い" } ] },
  { id: "D06-W13", day: 6, type: "word", japanese: "待つ", answer: "wait", hint: "", similar: [] },
  { id: "D06-W14", day: 6, type: "word", japanese: "電話する", answer: "call", hint: "", similar: [] },
  { id: "D06-W15", day: 6, type: "word", japanese: "見つける", answer: "find", hint: "", similar: [] },
  { id: "D06-W16", day: 6, type: "word", japanese: "失う・負ける", answer: "lose", hint: "", similar: [] },
  { id: "D06-W17", day: 6, type: "word", japanese: "勝つ", answer: "win", hint: "", similar: [] },
  { id: "D06-W18", day: 6, type: "word", japanese: "試す", answer: "try", hint: "", similar: [] },
  { id: "D06-W19", day: 6, type: "word", japanese: "訪れる", answer: "visit", hint: "", similar: [] },
  { id: "D06-W20", day: 6, type: "word", japanese: "滞在する", answer: "stay", hint: "", similar: [] },
  { id: "D06-P01", day: 6, type: "phrase", japanese: "人に～するよう言う", answer: "tell 人 to", hint: "", similar: [] },
  { id: "D06-P02", day: 6, type: "phrase", japanese: "人に～を頼む", answer: "ask 人 to", hint: "", similar: [] },
  { id: "D06-P03", day: 6, type: "phrase", japanese: "人が～するのを助ける", answer: "help 人 (to)", hint: "", similar: [] },
  { id: "D06-P04", day: 6, type: "phrase", japanese: "～しようとする", answer: "try to", hint: "", similar: [] },
  { id: "D06-P05", day: 6, type: "phrase", japanese: "～することを学ぶ", answer: "learn to", hint: "", similar: [] },
  { id: "D07-W01", day: 7, type: "word", japanese: "戻る・返す", answer: "return", hint: "", similar: [] },
  { id: "D07-W02", day: 7, type: "word", japanese: "選ぶ", answer: "choose", hint: "", similar: [] },
  { id: "D07-W03", day: 7, type: "word", japanese: "借りる", answer: "borrow", hint: "", similar: [ { answer: "lend", reason: "借りる/貸すの違い" } ] },
  { id: "D07-W04", day: 7, type: "word", japanese: "貸す", answer: "lend", hint: "", similar: [ { answer: "borrow", reason: "借りる/貸すの違い" } ] },
  { id: "D07-W05", day: 7, type: "word", japanese: "参加する", answer: "join", hint: "", similar: [] },
  { id: "D07-W06", day: 7, type: "word", japanese: "育つ", answer: "grow", hint: "", similar: [] },
  { id: "D07-W07", day: 7, type: "word", japanese: "改善する", answer: "improve", hint: "", similar: [] },
  { id: "D07-W08", day: 7, type: "word", japanese: "変える", answer: "change", hint: "", similar: [] },
  { id: "D07-W09", day: 7, type: "word", japanese: "運ぶ", answer: "carry", hint: "", similar: [] },
  { id: "D07-W10", day: 7, type: "word", japanese: "招待する", answer: "invite", hint: "", similar: [] },
  { id: "D07-W11", day: 7, type: "word", japanese: "望む", answer: "hope", hint: "", similar: [] },
  { id: "D07-W12", day: 7, type: "word", japanese: "決める", answer: "decide", hint: "", similar: [] },
  { id: "D07-W13", day: 7, type: "word", japanese: "覚えている", answer: "remember", hint: "", similar: [] },
  { id: "D07-W14", day: 7, type: "word", japanese: "忘れる", answer: "forget", hint: "", similar: [] },
  { id: "D07-W15", day: 7, type: "word", japanese: "必要とする", answer: "need", hint: "", similar: [] },
  { id: "D07-W16", day: 7, type: "word", japanese: "欲しい", answer: "want", hint: "", similar: [] },
  { id: "D07-W17", day: 7, type: "word", japanese: "楽しむ", answer: "enjoy", hint: "", similar: [] },
  { id: "D07-W18", day: 7, type: "word", japanese: "到着する", answer: "arrive", hint: "", similar: [] },
  { id: "D07-W19", day: 7, type: "word", japanese: "～になる", answer: "become", hint: "", similar: [] },
  { id: "D07-W20", day: 7, type: "word", japanese: "出発する", answer: "leave", hint: "", similar: [] },
  { id: "D07-P01", day: 7, type: "phrase", japanese: "～することを楽しむ", answer: "enjoy doing", hint: "", similar: [] },
  { id: "D07-P02", day: 7, type: "phrase", japanese: "～し終える", answer: "finish doing", hint: "", similar: [] },
  { id: "D07-P03", day: 7, type: "phrase", japanese: "～することをやめる", answer: "stop doing", hint: "", similar: [] },
  { id: "D07-P04", day: 7, type: "phrase", japanese: "人に～するよう言う", answer: "tell 人 to", hint: "", similar: [] },
  { id: "D07-P05", day: 7, type: "phrase", japanese: "人に～を頼む", answer: "ask 人 to", hint: "", similar: [] }
];

function normalizeAudioBaseName(text) {
  return String(text || "")
    .toLowerCase()
    .replace(/人/g, "person")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/_+/g, "_");
}

window.vocabularyBank = (window.vocabularyBank || []).map((item) => {
  if (item.audioFile) return item;
  const baseName = normalizeAudioBaseName(item.answer || "");
  return {
    ...item,
    audioFile: baseName ? `audio/${baseName}.mp3` : ""
  };
});
