window.vocabularyBank = [
  { id: "D01-W01", day: 1, type: "word", japanese: "～である", answer: "be", hint: "", similar: [] },
  { id: "D01-W02", day: 1, type: "word", japanese: "持っている", answer: "have", hint: "", similar: [] },
  { id: "D01-W03", day: 1, type: "word", japanese: "する", answer: "do", hint: "", similar: [] },
  { id: "D01-W04", day: 1, type: "word", japanese: "作る", answer: "make", hint: "", similar: [] },
  { id: "D01-W05", day: 1, type: "word", japanese: "取る・持っていく", answer: "take", hint: "", similar: [ { answer: "bring", reason: "話し手側から持っていく" } ] },
  { id: "D01-W06", day: 1, type: "word", japanese: "得る", answer: "get", hint: "", similar: [] },
  { id: "D01-W07", day: 1, type: "word", japanese: "行く", answer: "go", hint: "", similar: [ { answer: "come", reason: "話し手側から離れる" } ] },
  { id: "D01-W08", day: 1, type: "word", japanese: "来る", answer: "come", hint: "", similar: [ { answer: "go", reason: "話し手側へ来る" } ] },
  { id: "D01-W09", day: 1, type: "word", japanese: "見る", answer: "see", hint: "", similar: [ { answer: "look", reason: "意識して見る" }, { answer: "watch", reason: "動いているものを見る" } ] },
  { id: "D01-W10", day: 1, type: "word", japanese: "見る", answer: "look", hint: "", similar: [ { answer: "see", reason: "自然に目に入る" }, { answer: "watch", reason: "動いているものを見る" } ] },
  { id: "D01-W11", day: 1, type: "word", japanese: "（じっと）見る", answer: "watch", hint: "", similar: [ { answer: "see", reason: "自然に目に入る" }, { answer: "look", reason: "意識して見る" } ] },
  { id: "D01-W12", day: 1, type: "word", japanese: "聞こえる", answer: "hear", hint: "", similar: [ { answer: "listen", reason: "意識して聞く" } ] },
  { id: "D01-W13", day: 1, type: "word", japanese: "聞く", answer: "listen", hint: "", similar: [ { answer: "hear", reason: "自然に聞こえる" } ] },
  { id: "D01-W14", day: 1, type: "word", japanese: "話す", answer: "speak", hint: "", similar: [ { answer: "say", reason: "言葉を言う" }, { answer: "tell", reason: "相手に伝える" }, { answer: "talk", reason: "会話する" } ] },
  { id: "D01-W15", day: 1, type: "word", japanese: "言う", answer: "say", hint: "", similar: [ { answer: "tell", reason: "相手に伝える" }, { answer: "speak", reason: "言語を話す" }, { answer: "talk", reason: "会話する" } ] },
  { id: "D01-W16", day: 1, type: "word", japanese: "伝える", answer: "tell", hint: "", similar: [ { answer: "say", reason: "言葉を言う" }, { answer: "speak", reason: "言語を話す" }, { answer: "talk", reason: "会話する" } ] },
  { id: "D01-W17", day: 1, type: "word", japanese: "話す", answer: "talk", hint: "", similar: [ { answer: "say", reason: "言葉を言う" }, { answer: "tell", reason: "相手に伝える" }, { answer: "speak", reason: "言語を話す" } ] },
  { id: "D01-W18", day: 1, type: "word", japanese: "尋ねる", answer: "ask", hint: "", similar: [] },
  { id: "D01-W19", day: 1, type: "word", japanese: "答える", answer: "answer", hint: "", similar: [] },
  { id: "D01-W20", day: 1, type: "word", japanese: "知っている", answer: "know", hint: "", similar: [] },
  { id: "D01-P01", day: 1, type: "phrase", japanese: "～に興味がある", learningJapanese: "気持ちが向いていて～に興味がある", answer: "be interested in", hint: "", similar: [] },
  { id: "D01-P02", day: 1, type: "phrase", japanese: "～が得意", learningJapanese: "うまくできて～が得意", answer: "be good at", hint: "", similar: [] },
  { id: "D01-P03", day: 1, type: "phrase", japanese: "～で有名", learningJapanese: "そのことでよく知られていて～で有名", answer: "be famous for", hint: "", similar: [] },
  { id: "D01-P04", day: 1, type: "phrase", japanese: "～を見る", learningJapanese: "意識して～に目を向ける", answer: "look at", hint: "", similar: [] },
  { id: "D01-P05", day: 1, type: "phrase", japanese: "～を聞く", learningJapanese: "意識して～を聞く", answer: "listen to", hint: "", similar: [] },
  { id: "D02-W01", day: 2, type: "word", japanese: "考える", answer: "think", hint: "", similar: [] },
  { id: "D02-W02", day: 2, type: "word", japanese: "理解する", answer: "understand", hint: "", similar: [] },
  { id: "D02-W03", day: 2, type: "word", japanese: "学ぶ", answer: "learn", hint: "", similar: [] },
  { id: "D02-W04", day: 2, type: "word", japanese: "勉強する", answer: "study", hint: "", similar: [] },
  { id: "D02-W05", day: 2, type: "word", japanese: "教える", answer: "teach", hint: "", similar: [] },
  { id: "D02-W06", day: 2, type: "word", japanese: "読む", answer: "read", hint: "", similar: [] },
  { id: "D02-W07", day: 2, type: "word", japanese: "書く", answer: "write", hint: "", similar: [] },
  { id: "D02-W08", day: 2, type: "word", japanese: "使う", answer: "use", hint: "", similar: [] },
  { id: "D02-W09", day: 2, type: "word", japanese: "助ける", answer: "help", hint: "", similar: [] },
  { id: "D02-W10", day: 2, type: "word", japanese: "働く", answer: "work", hint: "", similar: [] },
  { id: "D02-W11", day: 2, type: "word", japanese: "行く", answer: "go", hint: "", similar: [ { answer: "come", reason: "話し手側から離れる" } ] },
  { id: "D02-W12", day: 2, type: "word", japanese: "来る", answer: "come", hint: "", similar: [ { answer: "go", reason: "話し手側へ来る" } ] },
  { id: "D02-W13", day: 2, type: "word", japanese: "聞く", answer: "listen", hint: "", similar: [ { answer: "hear", reason: "自然に聞こえる" } ] },
  { id: "D02-W14", day: 2, type: "word", japanese: "話す", answer: "speak", hint: "", similar: [ { answer: "say", reason: "言葉を言う" }, { answer: "tell", reason: "相手に伝える" }, { answer: "talk", reason: "会話する" } ] },
  { id: "D02-W15", day: 2, type: "word", japanese: "尋ねる", answer: "ask", hint: "", similar: [] },
  { id: "D02-W16", day: 2, type: "word", japanese: "答える", answer: "answer", hint: "", similar: [] },
  { id: "D02-W17", day: 2, type: "word", japanese: "知っている", answer: "know", hint: "", similar: [] },
  { id: "D02-W18", day: 2, type: "word", japanese: "持っている", answer: "have", hint: "", similar: [] },
  { id: "D02-W19", day: 2, type: "word", japanese: "作る", answer: "make", hint: "", similar: [] },
  { id: "D02-W20", day: 2, type: "word", japanese: "得る", answer: "get", hint: "", similar: [] },
  { id: "D02-P01", day: 2, type: "phrase", japanese: "～を探す", learningJapanese: "見つけようとして～を探す", answer: "look for", hint: "", similar: [] },
  { id: "D02-P02", day: 2, type: "phrase", japanese: "～を待つ", learningJapanese: "来るまで・そうなるまで～を待つ", answer: "wait for", hint: "", similar: [] },
  { id: "D02-P03", day: 2, type: "phrase", japanese: "～について話す", learningJapanese: "話題として～について話す", answer: "talk about", hint: "", similar: [] },
  { id: "D02-P04", day: 2, type: "phrase", japanese: "～に興味がある", learningJapanese: "気持ちが向いていて～に興味がある", answer: "be interested in", hint: "", similar: [] },
  { id: "D02-P05", day: 2, type: "phrase", japanese: "～を聞く", learningJapanese: "意識して～を聞く", answer: "listen to", hint: "", similar: [] },
  { id: "D03-W01", day: 3, type: "word", japanese: "遊ぶ・する", answer: "play", hint: "", similar: [] },
  { id: "D03-W02", day: 3, type: "word", japanese: "走る", answer: "run", hint: "", similar: [] },
  { id: "D03-W03", day: 3, type: "word", japanese: "歩く", answer: "walk", hint: "", similar: [] },
  { id: "D03-W04", day: 3, type: "word", japanese: "食べる", answer: "eat", hint: "", similar: [] },
  { id: "D03-W05", day: 3, type: "word", japanese: "飲む", answer: "drink", hint: "", similar: [] },
  { id: "D03-W06", day: 3, type: "word", japanese: "買う", answer: "buy", hint: "", similar: [] },
  { id: "D03-W07", day: 3, type: "word", japanese: "売る", answer: "sell", hint: "", similar: [] },
  { id: "D03-W08", day: 3, type: "word", japanese: "支払う", answer: "pay", hint: "", similar: [] },
  { id: "D03-W09", day: 3, type: "word", japanese: "与える", answer: "give", hint: "", similar: [] },
  { id: "D03-W10", day: 3, type: "word", japanese: "見せる", answer: "show", hint: "", similar: [] },
  { id: "D03-W11", day: 3, type: "word", japanese: "考える", answer: "think", hint: "", similar: [] },
  { id: "D03-W12", day: 3, type: "word", japanese: "勉強する", answer: "study", hint: "", similar: [] },
  { id: "D03-W13", day: 3, type: "word", japanese: "読む", answer: "read", hint: "", similar: [] },
  { id: "D03-W14", day: 3, type: "word", japanese: "書く", answer: "write", hint: "", similar: [] },
  { id: "D03-W15", day: 3, type: "word", japanese: "使う", answer: "use", hint: "", similar: [] },
  { id: "D03-W16", day: 3, type: "word", japanese: "助ける", answer: "help", hint: "", similar: [] },
  { id: "D03-W17", day: 3, type: "word", japanese: "知っている", answer: "know", hint: "", similar: [] },
  { id: "D03-W18", day: 3, type: "word", japanese: "話す", answer: "speak", hint: "", similar: [ { answer: "say", reason: "言葉を言う" }, { answer: "tell", reason: "相手に伝える" }, { answer: "talk", reason: "会話する" } ] },
  { id: "D03-W19", day: 3, type: "word", japanese: "話す", answer: "talk", hint: "", similar: [ { answer: "say", reason: "言葉を言う" }, { answer: "tell", reason: "相手に伝える" }, { answer: "speak", reason: "言語を話す" } ] },
  { id: "D03-W20", day: 3, type: "word", japanese: "教える", answer: "teach", hint: "", similar: [] },
  { id: "D03-P01", day: 3, type: "phrase", japanese: "～について考える", learningJapanese: "頭の中で～のことを考える", answer: "think about", hint: "", similar: [] },
  { id: "D03-P02", day: 3, type: "phrase", japanese: "～しなければならない", learningJapanese: "しなければいけない必要があって～する", answer: "have to", hint: "", similar: [] },
  { id: "D03-P03", day: 3, type: "phrase", japanese: "～したい", learningJapanese: "自分の希望として～したい", answer: "want to", hint: "", similar: [] },
  { id: "D03-P04", day: 3, type: "phrase", japanese: "～を探す", learningJapanese: "見つけようとして～を探す", answer: "look for", hint: "", similar: [] },
  { id: "D03-P05", day: 3, type: "phrase", japanese: "～を待つ", learningJapanese: "来るまで・そうなるまで～を待つ", answer: "wait for", hint: "", similar: [] },
  { id: "D04-W01", day: 4, type: "word", japanese: "持ってくる", answer: "bring", hint: "", similar: [ { answer: "take", reason: "話し手側へ持ってくる" } ] },
  { id: "D04-W02", day: 4, type: "word", japanese: "送る", answer: "send", hint: "", similar: [] },
  { id: "D04-W03", day: 4, type: "word", japanese: "会う", answer: "meet", hint: "", similar: [] },
  { id: "D04-W04", day: 4, type: "word", japanese: "訪れる", answer: "visit", hint: "", similar: [] },
  { id: "D04-W05", day: 4, type: "word", japanese: "旅行する", answer: "travel", hint: "", similar: [] },
  { id: "D04-W06", day: 4, type: "word", japanese: "滞在する", answer: "stay", hint: "", similar: [] },
  { id: "D04-W07", day: 4, type: "word", japanese: "住む", answer: "live", hint: "", similar: [] },
  { id: "D04-W08", day: 4, type: "word", japanese: "動く・引っ越す", answer: "move", hint: "", similar: [] },
  { id: "D04-W09", day: 4, type: "word", japanese: "開ける", answer: "open", hint: "", similar: [] },
  { id: "D04-W10", day: 4, type: "word", japanese: "閉める", answer: "close", hint: "", similar: [] },
  { id: "D04-W11", day: 4, type: "word", japanese: "遊ぶ・する", answer: "play", hint: "", similar: [] },
  { id: "D04-W12", day: 4, type: "word", japanese: "走る", answer: "run", hint: "", similar: [] },
  { id: "D04-W13", day: 4, type: "word", japanese: "歩く", answer: "walk", hint: "", similar: [] },
  { id: "D04-W14", day: 4, type: "word", japanese: "食べる", answer: "eat", hint: "", similar: [] },
  { id: "D04-W15", day: 4, type: "word", japanese: "飲む", answer: "drink", hint: "", similar: [] },
  { id: "D04-W16", day: 4, type: "word", japanese: "買う", answer: "buy", hint: "", similar: [] },
  { id: "D04-W17", day: 4, type: "word", japanese: "支払う", answer: "pay", hint: "", similar: [] },
  { id: "D04-W18", day: 4, type: "word", japanese: "与える", answer: "give", hint: "", similar: [] },
  { id: "D04-W19", day: 4, type: "word", japanese: "見せる", answer: "show", hint: "", similar: [] },
  { id: "D04-W20", day: 4, type: "word", japanese: "助ける", answer: "help", hint: "", similar: [] },
  { id: "D04-P01", day: 4, type: "phrase", japanese: "～する必要がある", learningJapanese: "必要だから～する必要がある", answer: "need to", hint: "", similar: [] },
  { id: "D04-P02", day: 4, type: "phrase", japanese: "～したいと思う", learningJapanese: "～できるといいなと思う", answer: "hope to", hint: "", similar: [] },
  { id: "D04-P03", day: 4, type: "phrase", japanese: "～することを決める", learningJapanese: "することを自分で決めて～する", answer: "decide to", hint: "", similar: [] },
  { id: "D04-P04", day: 4, type: "phrase", japanese: "～しなければならない", learningJapanese: "しなければいけない必要があって～する", answer: "have to", hint: "", similar: [] },
  { id: "D04-P05", day: 4, type: "phrase", japanese: "～したい", learningJapanese: "自分の希望として～したい", answer: "want to", hint: "", similar: [] },
  { id: "D05-W01", day: 5, type: "word", japanese: "始める", answer: "start", hint: "", similar: [ { answer: "begin", reason: "開始する" } ] },
  { id: "D05-W02", day: 5, type: "word", japanese: "始まる", answer: "begin", hint: "", similar: [ { answer: "start", reason: "開始する" } ] },
  { id: "D05-W03", day: 5, type: "word", japanese: "終える", answer: "finish", hint: "", similar: [ { answer: "stop", reason: "中断/終了の違い" } ] },
  { id: "D05-W04", day: 5, type: "word", japanese: "止める", answer: "stop", hint: "", similar: [ { answer: "finish", reason: "中断/終了の違い" } ] },
  { id: "D05-W05", day: 5, type: "word", japanese: "待つ", answer: "wait", hint: "", similar: [] },
  { id: "D05-W06", day: 5, type: "word", japanese: "電話する", answer: "call", hint: "", similar: [] },
  { id: "D05-W07", day: 5, type: "word", japanese: "見つける", answer: "find", hint: "", similar: [] },
  { id: "D05-W08", day: 5, type: "word", japanese: "失う・負ける", answer: "lose", hint: "", similar: [] },
  { id: "D05-W09", day: 5, type: "word", japanese: "勝つ", answer: "win", hint: "", similar: [] },
  { id: "D05-W10", day: 5, type: "word", japanese: "試す", answer: "try", hint: "", similar: [] },
  { id: "D05-W11", day: 5, type: "word", japanese: "持ってくる", answer: "bring", hint: "", similar: [ { answer: "take", reason: "話し手側へ持ってくる" } ] },
  { id: "D05-W12", day: 5, type: "word", japanese: "送る", answer: "send", hint: "", similar: [] },
  { id: "D05-W13", day: 5, type: "word", japanese: "会う", answer: "meet", hint: "", similar: [] },
  { id: "D05-W14", day: 5, type: "word", japanese: "訪れる", answer: "visit", hint: "", similar: [] },
  { id: "D05-W15", day: 5, type: "word", japanese: "旅行する", answer: "travel", hint: "", similar: [] },
  { id: "D05-W16", day: 5, type: "word", japanese: "滞在する", answer: "stay", hint: "", similar: [] },
  { id: "D05-W17", day: 5, type: "word", japanese: "住む", answer: "live", hint: "", similar: [] },
  { id: "D05-W18", day: 5, type: "word", japanese: "開ける", answer: "open", hint: "", similar: [] },
  { id: "D05-W19", day: 5, type: "word", japanese: "閉める", answer: "close", hint: "", similar: [] },
  { id: "D05-W20", day: 5, type: "word", japanese: "動く", answer: "move", hint: "", similar: [] },
  { id: "D05-P01", day: 5, type: "phrase", japanese: "～しようとする", learningJapanese: "できるかやってみようとして～する", answer: "try to", hint: "", similar: [] },
  { id: "D05-P02", day: 5, type: "phrase", japanese: "～することを学ぶ", learningJapanese: "練習して～できるようになる", answer: "learn to", hint: "", similar: [] },
  { id: "D05-P03", day: 5, type: "phrase", japanese: "someoneに～してほしい", learningJapanese: "someoneに～してほしいと思う", answer: "want someone to", hint: "", similar: [] },
  { id: "D05-P04", day: 5, type: "phrase", japanese: "～する必要がある", learningJapanese: "必要だから～する必要がある", answer: "need to", hint: "", similar: [] },
  { id: "D05-P05", day: 5, type: "phrase", japanese: "～することを決める", learningJapanese: "することを自分で決めて～する", answer: "decide to", hint: "", similar: [] },
  { id: "D06-W01", day: 6, type: "word", japanese: "望む", answer: "hope", hint: "", similar: [] },
  { id: "D06-W02", day: 6, type: "word", japanese: "決める", answer: "decide", hint: "", similar: [] },
  { id: "D06-W03", day: 6, type: "word", japanese: "覚えている", answer: "remember", hint: "", similar: [] },
  { id: "D06-W04", day: 6, type: "word", japanese: "忘れる", answer: "forget", hint: "", similar: [] },
  { id: "D06-W05", day: 6, type: "word", japanese: "必要とする", answer: "need", hint: "", similar: [] },
  { id: "D06-W06", day: 6, type: "word", japanese: "欲しい", answer: "want", hint: "", similar: [] },
  { id: "D06-W07", day: 6, type: "word", japanese: "楽しむ", answer: "enjoy", hint: "", similar: [] },
  { id: "D06-W08", day: 6, type: "word", japanese: "到着する", answer: "arrive", hint: "", similar: [] },
  { id: "D06-W09", day: 6, type: "word", japanese: "～になる", answer: "become", hint: "", similar: [] },
  { id: "D06-W10", day: 6, type: "word", japanese: "去る・出発する", answer: "leave", hint: "", similar: [] },
  { id: "D06-W11", day: 6, type: "word", japanese: "始める", answer: "start", hint: "", similar: [ { answer: "begin", reason: "開始する" } ] },
  { id: "D06-W12", day: 6, type: "word", japanese: "終える", answer: "finish", hint: "", similar: [ { answer: "stop", reason: "中断/終了の違い" } ] },
  { id: "D06-W13", day: 6, type: "word", japanese: "待つ", answer: "wait", hint: "", similar: [] },
  { id: "D06-W14", day: 6, type: "word", japanese: "電話する", answer: "call", hint: "", similar: [] },
  { id: "D06-W15", day: 6, type: "word", japanese: "見つける", answer: "find", hint: "", similar: [] },
  { id: "D06-W16", day: 6, type: "word", japanese: "失う・負ける", answer: "lose", hint: "", similar: [] },
  { id: "D06-W17", day: 6, type: "word", japanese: "勝つ", answer: "win", hint: "", similar: [] },
  { id: "D06-W18", day: 6, type: "word", japanese: "試す", answer: "try", hint: "", similar: [] },
  { id: "D06-W19", day: 6, type: "word", japanese: "訪れる", answer: "visit", hint: "", similar: [] },
  { id: "D06-W20", day: 6, type: "word", japanese: "滞在する", answer: "stay", hint: "", similar: [] },
  { id: "D06-P01", day: 6, type: "phrase", japanese: "someoneに～するよう言う", learningJapanese: "someoneにこうしなさいと伝えて～するよう言う", answer: "tell someone to", hint: "", similar: [] },
  { id: "D06-P02", day: 6, type: "phrase", japanese: "someoneに～を頼む", learningJapanese: "someoneにお願いして～するよう頼む", answer: "ask someone to", hint: "", similar: [] },
  { id: "D06-P03", day: 6, type: "phrase", japanese: "someoneが～するのを助ける", learningJapanese: "someoneが～できるよう力を貸す", answer: "help someone (to)", hint: "", similar: [] },
  { id: "D06-P04", day: 6, type: "phrase", japanese: "～しようとする", learningJapanese: "できるかやってみようとして～する", answer: "try to", hint: "", similar: [] },
  { id: "D06-P05", day: 6, type: "phrase", japanese: "～することを学ぶ", learningJapanese: "練習して～できるようになる", answer: "learn to", hint: "", similar: [] },
  { id: "D07-W01", day: 7, type: "word", japanese: "戻る・返す", answer: "return", hint: "", similar: [] },
  { id: "D07-W02", day: 7, type: "word", japanese: "選ぶ", answer: "choose", hint: "", similar: [] },
  { id: "D07-W03", day: 7, type: "word", japanese: "借りる", answer: "borrow", hint: "", similar: [ { answer: "lend", reason: "借りる/貸すの違い" } ] },
  { id: "D07-W04", day: 7, type: "word", japanese: "貸す", answer: "lend", hint: "", similar: [ { answer: "borrow", reason: "借りる/貸すの違い" } ] },
  { id: "D07-W05", day: 7, type: "word", japanese: "参加する", answer: "join", hint: "", similar: [] },
  { id: "D07-W06", day: 7, type: "word", japanese: "育つ", answer: "grow", hint: "", similar: [] },
  { id: "D07-W07", day: 7, type: "word", japanese: "改善する", answer: "improve", hint: "", similar: [] },
  { id: "D07-W08", day: 7, type: "word", japanese: "変える", answer: "change", hint: "", similar: [] },
  { id: "D07-W09", day: 7, type: "word", japanese: "運ぶ", answer: "carry", hint: "", similar: [] },
  { id: "D07-W10", day: 7, type: "word", japanese: "招待する", answer: "invite", hint: "", similar: [] },
  { id: "D07-W11", day: 7, type: "word", japanese: "望む", answer: "hope", hint: "", similar: [] },
  { id: "D07-W12", day: 7, type: "word", japanese: "決める", answer: "decide", hint: "", similar: [] },
  { id: "D07-W13", day: 7, type: "word", japanese: "覚えている", answer: "remember", hint: "", similar: [] },
  { id: "D07-W14", day: 7, type: "word", japanese: "忘れる", answer: "forget", hint: "", similar: [] },
  { id: "D07-W15", day: 7, type: "word", japanese: "必要とする", answer: "need", hint: "", similar: [] },
  { id: "D07-W16", day: 7, type: "word", japanese: "欲しい", answer: "want", hint: "", similar: [] },
  { id: "D07-W17", day: 7, type: "word", japanese: "楽しむ", answer: "enjoy", hint: "", similar: [] },
  { id: "D07-W18", day: 7, type: "word", japanese: "到着する", answer: "arrive", hint: "", similar: [] },
  { id: "D07-W19", day: 7, type: "word", japanese: "～になる", answer: "become", hint: "", similar: [] },
  { id: "D07-W20", day: 7, type: "word", japanese: "出発する", answer: "leave", hint: "", similar: [] },
  { id: "D07-P01", day: 7, type: "phrase", japanese: "～することを楽しむ", learningJapanese: "していて楽しいと感じる", answer: "enjoy doing", hint: "", similar: [] },
  { id: "D07-P02", day: 7, type: "phrase", japanese: "～し終える", learningJapanese: "最後までして～し終える", answer: "finish doing", hint: "", similar: [] },
  { id: "D07-P03", day: 7, type: "phrase", japanese: "～することをやめる", learningJapanese: "途中でやめて～するのをやめる", answer: "stop doing", hint: "", similar: [] },
  { id: "D07-P04", day: 7, type: "phrase", japanese: "someoneに～するよう言う", learningJapanese: "someoneにこうしなさいと伝えて～するよう言う", answer: "tell someone to", hint: "", similar: [] },
  { id: "D07-P05", day: 7, type: "phrase", japanese: "someoneに～を頼む", learningJapanese: "someoneにお願いして～するよう頼む", answer: "ask someone to", hint: "", similar: [] },  { id: "D08-W01", day: 8, type: "word", japanese: "到着する", answer: "arrive", hint: "", similar: [] },
  { id: "D08-W02", day: 8, type: "word", japanese: "出発する", answer: "leave", hint: "", similar: [] },
  { id: "D08-W03", day: 8, type: "word", japanese: "借りる", answer: "borrow", hint: "", similar: [ { answer: "lend", reason: "借りる・貸すの違い" } ] },
  { id: "D08-W04", day: 8, type: "word", japanese: "貸す", answer: "lend", hint: "", similar: [ { answer: "borrow", reason: "貸す・借りるの違い" } ] },
  { id: "D08-W05", day: 8, type: "word", japanese: "選ぶ", answer: "choose", hint: "", similar: [] },
  { id: "D08-W06", day: 8, type: "word", japanese: "持ってくる", answer: "bring", hint: "", similar: [ { answer: "take", reason: "話し手のいる方へ持ってくる" } ] },
  { id: "D08-W07", day: 8, type: "word", japanese: "運ぶ", answer: "carry", hint: "", similar: [] },
  { id: "D08-W08", day: 8, type: "word", japanese: "覚えている", answer: "remember", hint: "", similar: [ { answer: "forget", reason: "覚えている・忘れるの違い" } ] },
  { id: "D08-W09", day: 8, type: "word", japanese: "忘れる", answer: "forget", hint: "", similar: [ { answer: "remember", reason: "忘れる・覚えているの違い" } ] },
  { id: "D08-W10", day: 8, type: "word", japanese: "～になる", answer: "become", hint: "", similar: [] },
  { id: "D08-W11", day: 8, type: "word", japanese: "建てる", answer: "build", hint: "", similar: [] },
  { id: "D08-W12", day: 8, type: "word", japanese: "壊す", answer: "break", hint: "", similar: [] },
  { id: "D08-W13", day: 8, type: "word", japanese: "掃除する", answer: "clean", hint: "", similar: [] },
  { id: "D08-W14", day: 8, type: "word", japanese: "閉める", answer: "close", hint: "", similar: [ { answer: "open", reason: "閉める・開けるの違い" } ] },
  { id: "D08-W15", day: 8, type: "word", japanese: "開ける", answer: "open", hint: "", similar: [ { answer: "close", reason: "開ける・閉めるの違い" } ] },
  { id: "D08-W16", day: 8, type: "word", japanese: "旅行する", answer: "travel", hint: "", similar: [] },
  { id: "D08-W17", day: 8, type: "word", japanese: "滞在する", answer: "stay", hint: "", similar: [] },
  { id: "D08-W18", day: 8, type: "word", japanese: "訪れる", answer: "visit", hint: "", similar: [] },
  { id: "D08-W19", day: 8, type: "word", japanese: "～の周りに", answer: "around", hint: "", similar: [] },
  { id: "D08-W20", day: 8, type: "word", japanese: "～の前に", answer: "before", hint: "", similar: [] },
  { id: "D08-P01", day: 8, type: "phrase", japanese: "～を見る", answer: "look at", hint: "", similar: [] },
  { id: "D08-P02", day: 8, type: "phrase", japanese: "～を探す", answer: "look for", hint: "", similar: [] },
  { id: "D08-P03", day: 8, type: "phrase", japanese: "～の出身である", answer: "come from", hint: "", similar: [] },
  { id: "D08-P04", day: 8, type: "phrase", japanese: "～に興味がある", answer: "be interested in", hint: "", similar: [] },
  { id: "D08-P05", day: 8, type: "phrase", japanese: "～しなければならない", answer: "have to", hint: "", similar: [] },
  { id: "D09-W01", day: 9, type: "word", japanese: "返す", answer: "return", hint: "", similar: [] },
  { id: "D09-W02", day: 9, type: "word", japanese: "会う", answer: "meet", hint: "", similar: [] },
  { id: "D09-W03", day: 9, type: "word", japanese: "参加する", answer: "join", hint: "", similar: [] },
  { id: "D09-W04", day: 9, type: "word", japanese: "望む", answer: "hope", hint: "", similar: [] },
  { id: "D09-W05", day: 9, type: "word", japanese: "決める", answer: "decide", hint: "", similar: [] },
  { id: "D09-W06", day: 9, type: "word", japanese: "料理する", answer: "cook", hint: "", similar: [] },
  { id: "D09-W07", day: 9, type: "word", japanese: "洗う", answer: "wash", hint: "", similar: [] },
  { id: "D09-W08", day: 9, type: "word", japanese: "動く", answer: "move", hint: "", similar: [] },
  { id: "D09-W09", day: 9, type: "word", japanese: "渡る", answer: "cross", hint: "", similar: [] },
  { id: "D09-W10", day: 9, type: "word", japanese: "曲がる", answer: "turn", hint: "", similar: [] },
  { id: "D09-W11", day: 9, type: "word", japanese: "右", answer: "right", hint: "", similar: [] },
  { id: "D09-W12", day: 9, type: "word", japanese: "左", answer: "left", hint: "", similar: [] },
  { id: "D09-W13", day: 9, type: "word", japanese: "まっすぐ", answer: "straight", hint: "", similar: [] },
  { id: "D09-W14", day: 9, type: "word", japanese: "忙しい", answer: "busy", hint: "", similar: [] },
  { id: "D09-W15", day: 9, type: "word", japanese: "暇な", answer: "free", hint: "", similar: [] },
  { id: "D09-W16", day: 9, type: "word", japanese: "異なる", answer: "different", hint: "", similar: [] },
  { id: "D09-W17", day: 9, type: "word", japanese: "同じ", answer: "same", hint: "", similar: [] },
  { id: "D09-W18", day: 9, type: "word", japanese: "お気に入りの", answer: "favorite", hint: "", similar: [] },
  { id: "D09-W19", day: 9, type: "word", japanese: "速く", answer: "quickly", hint: "", similar: [] },
  { id: "D09-W20", day: 9, type: "word", japanese: "ゆっくり", answer: "slowly", hint: "", similar: [] },
  { id: "D09-P01", day: 9, type: "phrase", japanese: "～について話す", learningJapanese: "話題として～について話す", answer: "talk about", hint: "", similar: [] },
  { id: "D09-P02", day: 9, type: "phrase", japanese: "～を求める", learningJapanese: "必要として～を求める", answer: "ask for", hint: "", similar: [] },
  { id: "D09-P03", day: 9, type: "phrase", japanese: "～と異なる", learningJapanese: "比べて～と異なる", answer: "be different from", hint: "", similar: [] },
  { id: "D09-P04", day: 9, type: "phrase", japanese: "買い物に行く", learningJapanese: "買い物をするために行く", answer: "go shopping", hint: "", similar: [] },
  { id: "D09-P05", day: 9, type: "phrase", japanese: "～に着く", learningJapanese: "目的地の～に着く", answer: "get to", hint: "", similar: [] },
  { id: "D10-W01", day: 10, type: "word", japanese: "到着する", answer: "arrive", hint: "", similar: [] },
  { id: "D10-W02", day: 10, type: "word", japanese: "空港", answer: "airport", hint: "", similar: [] },
  { id: "D10-W03", day: 10, type: "word", japanese: "切符", answer: "ticket", hint: "", similar: [] },
  { id: "D10-W04", day: 10, type: "word", japanese: "橋", answer: "bridge", hint: "", similar: [] },
  { id: "D10-W05", day: 10, type: "word", japanese: "川", answer: "river", hint: "", similar: [] },
  { id: "D10-W06", day: 10, type: "word", japanese: "山", answer: "mountain", hint: "", similar: [] },
  { id: "D10-W07", day: 10, type: "word", japanese: "旅行する", answer: "travel", hint: "", similar: [] },
  { id: "D10-W08", day: 10, type: "word", japanese: "訪れる", answer: "visit", hint: "", similar: [] },
  { id: "D10-W09", day: 10, type: "word", japanese: "滞在する", answer: "stay", hint: "", similar: [] },
  { id: "D10-W10", day: 10, type: "word", japanese: "建てる", answer: "build", hint: "", similar: [] },
  { id: "D10-W11", day: 10, type: "word", japanese: "壊す", answer: "break", hint: "", similar: [] },
  { id: "D10-W12", day: 10, type: "word", japanese: "注意深い", answer: "careful", hint: "", similar: [] },
  { id: "D10-W13", day: 10, type: "word", japanese: "危険な", answer: "dangerous", hint: "", similar: [] },
  { id: "D10-W14", day: 10, type: "word", japanese: "安全な", answer: "safe", hint: "", similar: [] },
  { id: "D10-W15", day: 10, type: "word", japanese: "人気のある", answer: "popular", hint: "", similar: [] },
  { id: "D10-W16", day: 10, type: "word", japanese: "役に立つ", answer: "useful", hint: "", similar: [] },
  { id: "D10-W17", day: 10, type: "word", japanese: "いつも", answer: "always", hint: "", similar: [] },
  { id: "D10-W18", day: 10, type: "word", japanese: "よく", answer: "often", hint: "", similar: [] },
  { id: "D10-W19", day: 10, type: "word", japanese: "～の周りに", answer: "around", hint: "", similar: [] },
  { id: "D10-W20", day: 10, type: "word", japanese: "～の前に", answer: "before", hint: "", similar: [] },
  { id: "D10-P01", day: 10, type: "phrase", japanese: "～の世話をする", learningJapanese: "面倒を見て～の世話をする", answer: "look after", hint: "", similar: [] },
  { id: "D10-P02", day: 10, type: "phrase", japanese: "～の出身である", learningJapanese: "生まれ育った場所が～の出身である", answer: "come from", hint: "", similar: [] },
  { id: "D10-P03", day: 10, type: "phrase", japanese: "～を見る", learningJapanese: "意識して～に目を向ける", answer: "look at", hint: "", similar: [] },
  { id: "D10-P04", day: 10, type: "phrase", japanese: "～しなければならない", learningJapanese: "しなければいけない必要があって～する", answer: "have to", hint: "", similar: [] },
  { id: "D10-P05", day: 10, type: "phrase", japanese: "～に興味がある", learningJapanese: "気持ちが向いていて～に興味がある", answer: "be interested in", hint: "", similar: [] },
  { id: "D11-W01", day: 11, type: "word", japanese: "返す", answer: "return", hint: "", similar: [] },
  { id: "D11-W02", day: 11, type: "word", japanese: "会う", answer: "meet", hint: "", similar: [] },
  { id: "D11-W03", day: 11, type: "word", japanese: "参加する", answer: "join", hint: "", similar: [] },
  { id: "D11-W04", day: 11, type: "word", japanese: "望む", answer: "hope", hint: "", similar: [] },
  { id: "D11-W05", day: 11, type: "word", japanese: "決める", answer: "decide", hint: "", similar: [] },
  { id: "D11-W06", day: 11, type: "word", japanese: "料理する", answer: "cook", hint: "", similar: [] },
  { id: "D11-W07", day: 11, type: "word", japanese: "洗う", answer: "wash", hint: "", similar: [] },
  { id: "D11-W08", day: 11, type: "word", japanese: "動く", answer: "move", hint: "", similar: [] },
  { id: "D11-W09", day: 11, type: "word", japanese: "渡る", answer: "cross", hint: "", similar: [] },
  { id: "D11-W10", day: 11, type: "word", japanese: "曲がる", answer: "turn", hint: "", similar: [] },
  { id: "D11-W11", day: 11, type: "word", japanese: "右", answer: "right", hint: "", similar: [] },
  { id: "D11-W12", day: 11, type: "word", japanese: "左", answer: "left", hint: "", similar: [] },
  { id: "D11-W13", day: 11, type: "word", japanese: "まっすぐ", answer: "straight", hint: "", similar: [] },
  { id: "D11-W14", day: 11, type: "word", japanese: "忙しい", answer: "busy", hint: "", similar: [] },
  { id: "D11-W15", day: 11, type: "word", japanese: "暇な", answer: "free", hint: "", similar: [] },
  { id: "D11-W16", day: 11, type: "word", japanese: "異なる", answer: "different", hint: "", similar: [] },
  { id: "D11-W17", day: 11, type: "word", japanese: "同じ", answer: "same", hint: "", similar: [] },
  { id: "D11-W18", day: 11, type: "word", japanese: "お気に入りの", answer: "favorite", hint: "", similar: [] },
  { id: "D11-W19", day: 11, type: "word", japanese: "速く", answer: "quickly", hint: "", similar: [] },
  { id: "D11-W20", day: 11, type: "word", japanese: "ゆっくり", answer: "slowly", hint: "", similar: [] },
  { id: "D11-P01", day: 11, type: "phrase", japanese: "～について話す", learningJapanese: "話題として～について話す", answer: "talk about", hint: "", similar: [] },
  { id: "D11-P02", day: 11, type: "phrase", japanese: "～を求める", learningJapanese: "必要として～を求める", answer: "ask for", hint: "", similar: [] },
  { id: "D11-P03", day: 11, type: "phrase", japanese: "買い物に行く", learningJapanese: "買い物をするために行く", answer: "go shopping", hint: "", similar: [] },
  { id: "D11-P04", day: 11, type: "phrase", japanese: "～に着く", learningJapanese: "目的地の～に着く", answer: "get to", hint: "", similar: [] },
  { id: "D11-P05", day: 11, type: "phrase", japanese: "～と異なる", learningJapanese: "比べて～と異なる", answer: "be different from", hint: "", similar: [] },
  { id: "D12-W01", day: 12, type: "word", japanese: "買う", answer: "buy", hint: "", similar: [] },
  { id: "D12-W02", day: 12, type: "word", japanese: "売る", answer: "sell", hint: "", similar: [] },
  { id: "D12-W03", day: 12, type: "word", japanese: "支払う", answer: "pay", hint: "", similar: [] },
  { id: "D12-W04", day: 12, type: "word", japanese: "費用がかかる", answer: "cost", hint: "", similar: [] },
  { id: "D12-W05", day: 12, type: "word", japanese: "お金", answer: "money", hint: "", similar: [] },
  { id: "D12-W06", day: 12, type: "word", japanese: "市場", answer: "market", hint: "", similar: [] },
  { id: "D12-W07", day: 12, type: "word", japanese: "店", answer: "store", hint: "", similar: [] },
  { id: "D12-W08", day: 12, type: "word", japanese: "安い", answer: "cheap", hint: "", similar: [] },
  { id: "D12-W09", day: 12, type: "word", japanese: "高い", answer: "expensive", hint: "", similar: [] },
  { id: "D12-W10", day: 12, type: "word", japanese: "美しい", answer: "beautiful", hint: "", similar: [] },
  { id: "D12-W11", day: 12, type: "word", japanese: "きれいな", answer: "clean", hint: "", similar: [] },
  { id: "D12-W12", day: 12, type: "word", japanese: "汚い", answer: "dirty", hint: "", similar: [] },
  { id: "D12-W13", day: 12, type: "word", japanese: "～の中に", answer: "inside", hint: "", similar: [] },
  { id: "D12-W14", day: 12, type: "word", japanese: "～の外に", answer: "outside", hint: "", similar: [] },
  { id: "D12-W15", day: 12, type: "word", japanese: "昨日", answer: "yesterday", hint: "", similar: [] },
  { id: "D12-W16", day: 12, type: "word", japanese: "この前の", answer: "last", hint: "", similar: [] },
  { id: "D12-W17", day: 12, type: "word", japanese: "週", answer: "week", hint: "", similar: [] },
  { id: "D12-W18", day: 12, type: "word", japanese: "月", answer: "month", hint: "", similar: [] },
  { id: "D12-W19", day: 12, type: "word", japanese: "年", answer: "year", hint: "", similar: [] },
  { id: "D12-W20", day: 12, type: "word", japanese: "なぜなら", answer: "because", hint: "", similar: [] },
  { id: "D12-P01", day: 12, type: "phrase", japanese: "～の代金を払う", learningJapanese: "代金として～の代金を払う", answer: "pay for", hint: "", similar: [] },
  { id: "D12-P02", day: 12, type: "phrase", japanese: "～のように見える", learningJapanese: "見た感じが～のように見える", answer: "look like", hint: "", similar: [] },
  { id: "D12-P03", day: 12, type: "phrase", japanese: "至る所に", learningJapanese: "場所全体に広がって至る所に", answer: "all over", hint: "", similar: [] },
  { id: "D12-P04", day: 12, type: "phrase", japanese: "お互いに", learningJapanese: "一方と他方でお互いに", answer: "each other", hint: "", similar: [] },
  { id: "D12-P05", day: 12, type: "phrase", japanese: "～を恐れる", learningJapanese: "こわいと感じて～を恐れる", answer: "be afraid of", hint: "", similar: [] },
  { id: "D13-W01", day: 13, type: "word", japanese: "明日", answer: "tomorrow", hint: "", similar: [] },
  { id: "D13-W02", day: 13, type: "word", japanese: "次の", answer: "next", hint: "", similar: [] },
  { id: "D13-W03", day: 13, type: "word", japanese: "未来", answer: "future", hint: "", similar: [] },
  { id: "D13-W04", day: 13, type: "word", japanese: "計画する", answer: "plan", hint: "", similar: [] },
  { id: "D13-W05", day: 13, type: "word", japanese: "約束する", answer: "promise", hint: "", similar: [] },
  { id: "D13-W06", day: 13, type: "word", japanese: "招待する", answer: "invite", hint: "", similar: [] },
  { id: "D13-W07", day: 13, type: "word", japanese: "パーティー", answer: "party", hint: "", similar: [] },
  { id: "D13-W08", day: 13, type: "word", japanese: "祭り", answer: "festival", hint: "", similar: [] },
  { id: "D13-W09", day: 13, type: "word", japanese: "天気", answer: "weather", hint: "", similar: [] },
  { id: "D13-W10", day: 13, type: "word", japanese: "晴れた", answer: "sunny", hint: "", similar: [] },
  { id: "D13-W11", day: 13, type: "word", japanese: "曇りの", answer: "cloudy", hint: "", similar: [] },
  { id: "D13-W12", day: 13, type: "word", japanese: "雨の", answer: "rainy", hint: "", similar: [] },
  { id: "D13-W13", day: 13, type: "word", japanese: "雪の", answer: "snowy", hint: "", similar: [] },
  { id: "D13-W14", day: 13, type: "word", japanese: "風の強い", answer: "windy", hint: "", similar: [] },
  { id: "D13-W15", day: 13, type: "word", japanese: "暖かい", answer: "warm", hint: "", similar: [] },
  { id: "D13-W16", day: 13, type: "word", japanese: "涼しい", answer: "cool", hint: "", similar: [] },
  { id: "D13-W17", day: 13, type: "word", japanese: "暑い", answer: "hot", hint: "", similar: [] },
  { id: "D13-W18", day: 13, type: "word", japanese: "寒い", answer: "cold", hint: "", similar: [] },
  { id: "D13-W19", day: 13, type: "word", japanese: "すぐに", answer: "soon", hint: "", similar: [] },
  { id: "D13-W20", day: 13, type: "word", japanese: "すでに", answer: "already", hint: "", similar: [] },
  { id: "D13-P01", day: 13, type: "phrase", japanese: "～する予定", learningJapanese: "これから～する予定", answer: "be going to", hint: "", similar: [] },
  { id: "D13-P02", day: 13, type: "phrase", japanese: "～に参加する", learningJapanese: "活動の一部として～に参加する", answer: "take part in", hint: "", similar: [] },
  { id: "D13-P03", day: 13, type: "phrase", japanese: "実現する", learningJapanese: "願いなどが本当になって実現する", answer: "come true", hint: "", similar: [] },
  { id: "D13-P04", day: 13, type: "phrase", japanese: "～を待つ", learningJapanese: "来るまで・そうなるまで～を待つ", answer: "wait for", hint: "", similar: [] },
  { id: "D13-P05", day: 13, type: "phrase", japanese: "成長する", learningJapanese: "大きくなって成長する", answer: "grow up", hint: "", similar: [] },
  { id: "D14-W01", day: 14, type: "word", japanese: "復習する", answer: "review", hint: "", similar: [] },
  { id: "D14-W02", day: 14, type: "word", japanese: "覚えている", answer: "remember", hint: "", similar: [ { answer: "forget", reason: "覚えている・忘れるの違い" } ] },
  { id: "D14-W03", day: 14, type: "word", japanese: "忘れる", answer: "forget", hint: "", similar: [ { answer: "remember", reason: "忘れる・覚えているの違い" } ] },
  { id: "D14-W04", day: 14, type: "word", japanese: "上達する", answer: "improve", hint: "", similar: [] },
  { id: "D14-W05", day: 14, type: "word", japanese: "挑戦する", answer: "challenge", hint: "", similar: [] },
  { id: "D14-W06", day: 14, type: "word", japanese: "夢", answer: "dream", hint: "", similar: [] },
  { id: "D14-W07", day: 14, type: "word", japanese: "目標", answer: "goal", hint: "", similar: [] },
  { id: "D14-W08", day: 14, type: "word", japanese: "成功", answer: "success", hint: "", similar: [] },
  { id: "D14-W09", day: 14, type: "word", japanese: "失敗する", answer: "fail", hint: "", similar: [] },
  { id: "D14-W10", day: 14, type: "word", japanese: "続ける", answer: "continue", hint: "", similar: [] },
  { id: "D14-W11", day: 14, type: "word", japanese: "すばらしい", answer: "excellent", hint: "", similar: [] },
  { id: "D14-W12", day: 14, type: "word", japanese: "重要な", answer: "important", hint: "", similar: [] },
  { id: "D14-W13", day: 14, type: "word", japanese: "準備ができた", answer: "ready", hint: "", similar: [] },
  { id: "D14-W14", day: 14, type: "word", japanese: "一緒に", answer: "together", hint: "", similar: [] },
  { id: "D14-W15", day: 14, type: "word", japanese: "再び", answer: "again", hint: "", similar: [] },
  { id: "D14-W16", day: 14, type: "word", japanese: "ついに", answer: "finally", hint: "", similar: [] },
  { id: "D14-W17", day: 14, type: "word", japanese: "たいてい", answer: "usually", hint: "", similar: [] },
  { id: "D14-W18", day: 14, type: "word", japanese: "ときどき", answer: "sometimes", hint: "", similar: [] },
  { id: "D14-W19", day: 14, type: "word", japanese: "決して～ない", answer: "never", hint: "", similar: [] },
  { id: "D14-W20", day: 14, type: "word", japanese: "復習", answer: "review", hint: "", similar: [] },
  { id: "D14-P01", day: 14, type: "phrase", japanese: "ベストを尽くす", learningJapanese: "できる力を全部使ってベストを尽くす", answer: "do one's best", hint: "", similar: [] },
  { id: "D14-P02", day: 14, type: "phrase", japanese: "～の準備ができている", learningJapanese: "これからする～の準備ができている", answer: "be ready for", hint: "", similar: [] },
  { id: "D14-P03", day: 14, type: "phrase", japanese: "～し続ける", learningJapanese: "途中でやめずに～し続ける", answer: "keep on", hint: "", similar: [] },
  { id: "D14-P04", day: 14, type: "phrase", japanese: "～をありがとう", learningJapanese: "してくれたことに対して～をありがとう", answer: "thank you for", hint: "", similar: [] },
  { id: "D14-P05", day: 14, type: "phrase", japanese: "楽しく過ごす", learningJapanese: "楽しい時間を過ごす", answer: "have a good time", hint: "", similar: [] }
];

function normalizeAudioBaseName(text) {
  return String(text || "")
    .toLowerCase()
    .replace(/someone/g, "person")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/_+/g, "_");
}

window.vocabularyBank = (window.vocabularyBank || []).map((item) => {
  if (item.audioFile) return item;
  const baseName = normalizeAudioBaseName(item.answer || "");
  return {
    ...item,
    audioFile: baseName ? `audio/${baseName}.mp3` : ""
  };
});
