window.prepositionTrainingMeta = {
  at: { icon: "📍", coreImage: "点", representative: ["at seven", "at the station", "good at baseball"] },
  in: { icon: "▣", coreImage: "中・囲まれた範囲", representative: ["in Tokyo", "in the park", "in English"] },
  on: { icon: "●━", coreImage: "面に接している", representative: ["on Sunday", "on time", "keep on studying"] },
  to: { icon: "➡", coreImage: "目的地へ向かう", representative: ["go to school", "write to my friend", "listen to music"] },
  from: { icon: "⬅", coreImage: "出発点から離れる", representative: ["from Japan", "come from Osaka", "different from"] },
  for: { icon: "🎯", coreImage: "向かう目的・対象", representative: ["wait for him", "thank you for", "ready for the game"] },
  with: { icon: "👥", coreImage: "一緒・道具を伴う", representative: ["talk with you", "with my family", "agree with you"] },
  by: { icon: "🚌", coreImage: "手段・そば・期限", representative: ["by plane", "by bus", "by the station"] },
  about: { icon: "💭", coreImage: "周辺・〜について", representative: ["talk about", "learn about", "about English"] },
  after: { icon: "▶", coreImage: "後ろ・後の時間", representative: ["after school", "after dinner", "after class"] },
  before: { icon: "◀", coreImage: "前・前の時間", representative: ["before school", "before dinner", "before my homework"] },
  near: { icon: "● ●", coreImage: "近く", representative: ["near the school", "near the hospital", "near the forest"] },
  during: { icon: "↔", coreImage: "期間の中", representative: ["during class", "during lunch", "during summer"] },
  without: { icon: "🚫", coreImage: "〜を伴わない", representative: ["without a dictionary", "without help", "without sugar"] },
  of: { icon: "🔗", coreImage: "所属・一部・つながり", representative: ["a member of", "the meaning of", "take care of"] },
  around: { icon: "⭕", coreImage: "周囲を取り囲む", representative: ["around the world", "around the park", "all around"] }
};

window.prepositionTrainingBank = [
  { id: "prep_at_001", preposition: "at", sentence: "I get up at six every morning.", question: "I get up (      ) six every morning.", answer: "at", translation: "私は毎朝6時に起きます。", contextImage: "時刻の一点", sourceDay: 1 },
  { id: "prep_at_002", preposition: "at", sentence: "I wait for my father at the station.", question: "I wait for my father (      ) the station.", answer: "at", translation: "私は駅で父を待ちます。", contextImage: "場所の一点", sourceDay: 2 },
  { id: "prep_at_003", preposition: "at", sentence: "We stay at a hotel.", question: "We stay (      ) a hotel.", answer: "at", translation: "私たちはホテルに泊まります。", contextImage: "滞在先の一点", sourceDay: 4 },
  { id: "prep_at_004", preposition: "at", sentence: "I arrived at the station yesterday.", question: "I arrived (      ) the station yesterday.", answer: "at", translation: "私は昨日、駅に着きました。", contextImage: "到着点", sourceDay: 19 },
  { id: "prep_at_005", preposition: "at", sentence: "He is good at baseball.", question: "He is good (      ) baseball.", answer: "at", translation: "彼は野球が得意です。", contextImage: "得意な対象", sourceDay: 17 },
  { id: "prep_at_006", preposition: "at", sentence: "I bought a book at the store yesterday.", question: "I bought a book (      ) the store yesterday.", answer: "at", translation: "私は昨日、その店で本を買いました。", contextImage: "行為の場所の一点", sourceDay: 12 },
  { id: "prep_at_007", preposition: "at", sentence: "I stayed at the hotel.", question: "I stayed (      ) the hotel.", answer: "at", translation: "私はそのホテルに泊まりました。", contextImage: "滞在先の一点", sourceDay: 10 },
  { id: "prep_at_008", preposition: "at", sentence: "I'll meet my friend at the airport.", question: "I'll meet my friend (      ) the airport.", answer: "at", translation: "私は空港で友だちに会う予定です。", contextImage: "待ち合わせ地点", sourceDay: 10 },

  { id: "prep_in_001", preposition: "in", sentence: "I talk with you in English.", question: "I talk with you (      ) English.", answer: "in", translation: "私はあなたと英語で話します。", contextImage: "言語という枠の中", sourceDay: 18 },
  { id: "prep_in_002", preposition: "in", sentence: "I arrived in Tokyo yesterday.", question: "I arrived (      ) Tokyo yesterday.", answer: "in", translation: "私は昨日、東京に着きました。", contextImage: "都市という範囲の中", sourceDay: 19 },
  { id: "prep_in_003", preposition: "in", sentence: "We took a picture in the park.", question: "We took a picture (      ) the park.", answer: "in", translation: "私たちは公園で写真を撮りました。", contextImage: "場所の内部", sourceDay: 22 },
  { id: "prep_in_004", preposition: "in", sentence: "Are you interested in English?", question: "Are you interested (      ) English?", answer: "in", translation: "あなたは英語に興味がありますか。", contextImage: "関心の向かう範囲", sourceDay: 1 },
  { id: "prep_in_005", preposition: "in", sentence: "I looked up the word in the dictionary.", question: "I looked up the word (      ) the dictionary.", answer: "in", translation: "私はその単語を辞書で調べました。", contextImage: "情報源の中", sourceDay: 23 },
  { id: "prep_in_006", preposition: "in", sentence: "We play in the park.", question: "We play (      ) the park.", answer: "in", translation: "私たちは公園で遊びます。", contextImage: "活動の場所の中", sourceDay: 3 },
  { id: "prep_in_007", preposition: "in", sentence: "We go to the sea in summer.", question: "We go to the sea (      ) summer.", answer: "in", translation: "私たちは夏に海へ行きます。", contextImage: "季節という期間の中", sourceDay: 24 },
  { id: "prep_in_008", preposition: "in", sentence: "I swam in the lake.", question: "I swam (      ) the lake.", answer: "in", translation: "私はその湖で泳ぎました。", contextImage: "水域の中", sourceDay: 19 },
  { id: "prep_in_009", preposition: "in", sentence: "I am the tallest in my class.", question: "I am the tallest (      ) my class.", answer: "in", translation: "私はクラスでいちばん背が高いです。", contextImage: "集団の範囲内", sourceDay: 18 },
  { id: "prep_in_010", preposition: "in", sentence: "I believe in the future.", question: "I believe (      ) the future.", answer: "in", translation: "私は未来を信じています。", contextImage: "信念の対象として内面で支える", sourceDay: 20 },

  { id: "prep_on_001", preposition: "on", sentence: "We play baseball on Sundays.", question: "We play baseball (      ) Sundays.", answer: "on", translation: "私たちは日曜日に野球をします。", contextImage: "曜日に予定を置く", sourceDay: 17 },
  { id: "prep_on_002", preposition: "on", sentence: "What do you do on the weekend?", question: "What do you do (      ) the weekend?", answer: "on", translation: "あなたは週末に何をしますか。", contextImage: "週末という日面に接する", sourceDay: 25 },
  { id: "prep_on_003", preposition: "on", sentence: "Did you come on time?", question: "Did you come (      ) time?", answer: "on", translation: "時間どおりに来ましたか。", contextImage: "時間軸上のぴったり接触", sourceDay: 26 },
  { id: "prep_on_004", preposition: "on", sentence: "He came to school on time.", question: "He came to school (      ) time.", answer: "on", translation: "彼は時間どおりに学校へ来ました。", contextImage: "時間への接触", sourceDay: 18 },
  { id: "prep_on_005", preposition: "on", sentence: "I play baseball on weekends.", question: "I play baseball (      ) weekends.", answer: "on", translation: "私は週末に野球をします。", contextImage: "週末ごとの日面", sourceDay: 17 },
  { id: "prep_on_006", preposition: "on", sentence: "We keep on studying English.", question: "We keep (      ) studying English.", answer: "on", translation: "私たちは英語を勉強し続けます。", contextImage: "動作を継続面に乗せる", sourceDay: 14 },

  { id: "prep_to_001", preposition: "to", sentence: "I write a letter to my friend.", question: "I write a letter (      ) my friend.", answer: "to", translation: "私は友だちに手紙を書きます。", contextImage: "相手へ向かう到達点", sourceDay: 2 },
  { id: "prep_to_002", preposition: "to", sentence: "Do you walk to school?", question: "Do you walk (      ) school?", answer: "to", translation: "あなたは歩いて学校へ行きますか。", contextImage: "学校へ向かう", sourceDay: 18 },
  { id: "prep_to_003", preposition: "to", sentence: "I get to the station.", question: "I get (      ) the station.", answer: "to", translation: "私は駅に着きます。", contextImage: "到着先に向かう", sourceDay: 9 },
  { id: "prep_to_004", preposition: "to", sentence: "I went to the library.", question: "I went (      ) the library.", answer: "to", translation: "私は図書館へ行きました。", contextImage: "目的地へ移動", sourceDay: 27 },
  { id: "prep_to_005", preposition: "to", sentence: "I returned the book to the teacher.", question: "I returned the book (      ) the teacher.", answer: "to", translation: "私は先生に本を返しました。", contextImage: "受け取り手へ向かう", sourceDay: 7 },
  { id: "prep_to_006", preposition: "to", sentence: "I walked to the station.", question: "I walked (      ) the station.", answer: "to", translation: "私は歩いて駅へ行きました。", contextImage: "歩いて目的地へ", sourceDay: 3 },
  { id: "prep_to_007", preposition: "to", sentence: "She is kind to everyone.", question: "She is kind (      ) everyone.", answer: "to", translation: "彼女はみんなに親切です。", contextImage: "態度の向かう相手", sourceDay: 15 },
  { id: "prep_to_008", preposition: "to", sentence: "I wrote to my friend.", question: "I wrote (      ) my friend.", answer: "to", translation: "私は友だちに手紙を書きました。", contextImage: "連絡の向かう相手", sourceDay: 11 },
  { id: "prep_to_009", preposition: "to", sentence: "I went straight to the station.", question: "I went straight (      ) the station.", answer: "to", translation: "私はまっすぐ駅へ行きました。", contextImage: "一直線に目的地へ", sourceDay: 19 },
  { id: "prep_to_010", preposition: "to", sentence: "This road leads to the station.", question: "This road leads (      ) the station.", answer: "to", translation: "この道は駅へ続いています。", contextImage: "道の行き先", sourceDay: 19 },
  { id: "prep_to_011", preposition: "to", sentence: "We listen to our teacher.", question: "We listen (      ) our teacher.", answer: "to", translation: "私たちは先生の話を聞きます。", contextImage: "注意の向かう対象", sourceDay: 1 },

  { id: "prep_from_001", preposition: "from", sentence: "I am from Japan.", question: "I am (      ) Japan.", answer: "from", translation: "私は日本の出身です。", contextImage: "出身の起点", sourceDay: 8 },
  { id: "prep_from_002", preposition: "from", sentence: "I come from Japan.", question: "I come (      ) Japan.", answer: "from", translation: "私は日本から来ました。", contextImage: "来る起点", sourceDay: 8 },
  { id: "prep_from_003", preposition: "from", sentence: "He comes from Osaka.", question: "He comes (      ) Osaka.", answer: "from", translation: "彼は大阪から来ています。", contextImage: "出発点", sourceDay: 28 },

  { id: "prep_for_001", preposition: "for", sentence: "I wait for him.", question: "I wait (      ) him.", answer: "for", translation: "私は彼を待ちます。", contextImage: "待つ対象", sourceDay: 2 },
  { id: "prep_for_002", preposition: "for", sentence: "We looked for the station.", question: "We looked (      ) the station.", answer: "for", translation: "私たちは駅を探しました。", contextImage: "探す対象", sourceDay: 8 },
  { id: "prep_for_003", preposition: "for", sentence: "We are looking for the dog.", question: "We are looking (      ) the dog.", answer: "for", translation: "私たちはその犬を探しています。", contextImage: "探索の対象", sourceDay: 3 },
  { id: "prep_for_004", preposition: "for", sentence: "I asked the teacher for help.", question: "I asked the teacher (      ) help.", answer: "for", translation: "私は先生に助けを求めました。", contextImage: "求める目的物", sourceDay: 9 },
  { id: "prep_for_005", preposition: "for", sentence: "I eat bread for breakfast.", question: "I eat bread (      ) breakfast.", answer: "for", translation: "私は朝食にパンを食べます。", contextImage: "目的・用途", sourceDay: 16 },
  { id: "prep_for_006", preposition: "for", sentence: "I cheered for my friend.", question: "I cheered (      ) my friend.", answer: "for", translation: "私は友だちを応援しました。", contextImage: "応援の対象", sourceDay: 17 },
  { id: "prep_for_007", preposition: "for", sentence: "I thank you for your help.", question: "I thank you (      ) your help.", answer: "for", translation: "助けてくれてありがとう。", contextImage: "理由・対象", sourceDay: 14 },
  { id: "prep_for_008", preposition: "for", sentence: "We are ready for the game.", question: "We are ready (      ) the game.", answer: "for", translation: "私たちは試合の準備ができています。", contextImage: "備える対象", sourceDay: 14 },

  { id: "prep_with_001", preposition: "with", sentence: "I talk with you in English.", question: "I talk (      ) you in English.", answer: "with", translation: "私はあなたと英語で話します。", contextImage: "会話の相手と一緒", sourceDay: 18 },
  { id: "prep_with_002", preposition: "with", sentence: "I had dinner with my family.", question: "I had dinner (      ) my family.", answer: "with", translation: "私は家族と夕食を食べました。", contextImage: "共に行動する", sourceDay: 15 },
  { id: "prep_with_003", preposition: "with", sentence: "We are living with our grandparents.", question: "We are living (      ) our grandparents.", answer: "with", translation: "私たちは祖父母と一緒に暮らしています。", contextImage: "同居する相手", sourceDay: 15 },
  { id: "prep_with_004", preposition: "with", sentence: "I had a good time with my friend.", question: "I had a good time (      ) my friend.", answer: "with", translation: "私は友だちと楽しい時間を過ごしました。", contextImage: "一緒に時間を過ごす", sourceDay: 15 },
  { id: "prep_with_005", preposition: "with", sentence: "I like cooking with my mother.", question: "I like cooking (      ) my mother.", answer: "with", translation: "私は母と一緒に料理するのが好きです。", contextImage: "協同する相手", sourceDay: 9 },
  { id: "prep_with_006", preposition: "with", sentence: "I like playing with my friends.", question: "I like playing (      ) my friends.", answer: "with", translation: "私は友だちと遊ぶのが好きです。", contextImage: "一緒に遊ぶ", sourceDay: 17 },
  { id: "prep_with_007", preposition: "with", sentence: "I agree with you.", question: "I agree (      ) you.", answer: "with", translation: "私はあなたに賛成です。", contextImage: "同意の相手", sourceDay: 20 },
  { id: "prep_with_008", preposition: "with", sentence: "I laughed with my friend.", question: "I laughed (      ) my friend.", answer: "with", translation: "私は友だちと一緒に笑いました。", contextImage: "感情を共にする", sourceDay: 29 },

  { id: "prep_by_001", preposition: "by", sentence: "We travel by plane.", question: "We travel (      ) plane.", answer: "by", translation: "私たちは飛行機で移動します。", contextImage: "移動手段", sourceDay: 19 },
  { id: "prep_by_002", preposition: "by", sentence: "We came home by bus.", question: "We came home (      ) bus.", answer: "by", translation: "私たちはバスで家に帰りました。", contextImage: "帰宅手段", sourceDay: 10 },

  { id: "prep_about_001", preposition: "about", sentence: "We talked about the teacher.", question: "We talked (      ) the teacher.", answer: "about", translation: "私たちは先生について話しました。", contextImage: "話題の周辺", sourceDay: 2 },
  { id: "prep_about_002", preposition: "about", sentence: "I thought about the answer.", question: "I thought (      ) the answer.", answer: "about", translation: "私はその答えについて考えました。", contextImage: "思考の対象", sourceDay: 3 },
  { id: "prep_about_003", preposition: "about", sentence: "We talked about English.", question: "We talked (      ) English.", answer: "about", translation: "私たちは英語について話しました。", contextImage: "話題内容", sourceDay: 11 },
  { id: "prep_about_004", preposition: "about", sentence: "I want to learn about new things.", question: "I want to learn (      ) new things.", answer: "about", translation: "私は新しいことについて学びたいです。", contextImage: "知識の対象", sourceDay: 18 },
  { id: "prep_about_005", preposition: "about", sentence: "I talked about the book.", question: "I talked (      ) the book.", answer: "about", translation: "私はその本について話しました。", contextImage: "会話の主題", sourceDay: 30 },
  { id: "prep_about_006", preposition: "about", sentence: "Do you want to learn more about English?", question: "Do you want to learn more (      ) English?", answer: "about", translation: "もっと英語について学びたいですか。", contextImage: "学習対象", sourceDay: 18 },

  { id: "prep_after_001", preposition: "after", sentence: "I am going to play baseball after school.", question: "I am going to play baseball (      ) school.", answer: "after", translation: "私は放課後に野球をするつもりです。", contextImage: "時間の後", sourceDay: 13 },
  { id: "prep_after_002", preposition: "after", sentence: "We play baseball after school.", question: "We play baseball (      ) school.", answer: "after", translation: "私たちは放課後に野球をします。", contextImage: "放課後", sourceDay: 17 },
  { id: "prep_after_003", preposition: "after", sentence: "I study after dinner.", question: "I study (      ) dinner.", answer: "after", translation: "私は夕食のあとで勉強します。", contextImage: "夕食後", sourceDay: 16 },
  { id: "prep_after_004", preposition: "after", sentence: "I talked with my friend after class.", question: "I talked with my friend (      ) class.", answer: "after", translation: "私は授業のあとで友だちと話しました。", contextImage: "授業の後", sourceDay: 18 },
  { id: "prep_after_005", preposition: "after", sentence: "We studied after lunch.", question: "We studied (      ) lunch.", answer: "after", translation: "私たちは昼食のあとで勉強しました。", contextImage: "昼食後", sourceDay: 16 },
  { id: "prep_after_006", preposition: "after", sentence: "I do my homework after dinner.", question: "I do my homework (      ) dinner.", answer: "after", translation: "私は夕食のあとで宿題をします。", contextImage: "行動の順序", sourceDay: 21 },
  { id: "prep_after_007", preposition: "after", sentence: "I look after my brother every day.", question: "I look (      ) my brother every day.", answer: "after", translation: "私は毎日、弟の世話をします。", contextImage: "熟語としての対象", sourceDay: 10, category: "fixedPhrase" },

  { id: "prep_before_001", preposition: "before", sentence: "We met before school.", question: "We met (      ) school.", answer: "before", translation: "私たちは学校の前に会いました。", contextImage: "時間の前", sourceDay: 31 },
  { id: "prep_before_002", preposition: "before", sentence: "I do my homework before dinner.", question: "I do my homework (      ) dinner.", answer: "before", translation: "私は夕食の前に宿題をします。", contextImage: "夕食前", sourceDay: 16 },
  { id: "prep_before_003", preposition: "before", sentence: "I eat dinner before my homework.", question: "I eat dinner (      ) my homework.", answer: "before", translation: "私は宿題の前に夕食を食べます。", contextImage: "順序の先", sourceDay: 21 },

  { id: "prep_near_001", preposition: "near", sentence: "I live near the school.", question: "I live (      ) the school.", answer: "near", translation: "私は学校の近くに住んでいます。", contextImage: "場所の近接", sourceDay: 15 },
  { id: "prep_near_002", preposition: "near", sentence: "The museum is near the hospital.", question: "The museum is (      ) the hospital.", answer: "near", translation: "その博物館は病院の近くにあります。", contextImage: "基準点の近く", sourceDay: 32 },
  { id: "prep_near_003", preposition: "near", sentence: "We live near the forest.", question: "We live (      ) the forest.", answer: "near", translation: "私たちは森の近くに住んでいます。", contextImage: "自然物の近く", sourceDay: 33 },

  { id: "prep_during_001", preposition: "during", sentence: "We speak English during class.", question: "We speak English (      ) class.", answer: "during", translation: "私たちは授業中に英語を話します。", contextImage: "授業という期間内", sourceDay: 18 },

  { id: "prep_without_001", preposition: "without", sentence: "Can you study without a dictionary?", question: "Can you study (      ) a dictionary?", answer: "without", translation: "辞書なしで勉強できますか。", contextImage: "道具を伴わない", sourceDay: 34 },

  { id: "prep_of_001", preposition: "of", sentence: "I am a member of the team.", question: "I am a member (      ) the team.", answer: "of", translation: "私はそのチームの一員です。", contextImage: "所属のつながり", sourceDay: 17 },
  { id: "prep_of_002", preposition: "of", sentence: "I know the meaning of the sentence.", question: "I know the meaning (      ) the sentence.", answer: "of", translation: "私はその文の意味を知っています。", contextImage: "内容との関係", sourceDay: 18 },
  { id: "prep_of_003", preposition: "of", sentence: "He is afraid of horses.", question: "He is afraid (      ) horses.", answer: "of", translation: "彼は馬をこわがっています。", contextImage: "感情の対象", sourceDay: 12 },
  { id: "prep_of_004", preposition: "of", sentence: "I understand the meaning of the story.", question: "I understand the meaning (      ) the story.", answer: "of", translation: "私はその物語の意味を理解しています。", contextImage: "意味の対象", sourceDay: 20 },
  { id: "prep_of_005", preposition: "of", sentence: "I take care of my brother.", question: "I take care (      ) my brother.", answer: "of", translation: "私は弟の世話をします。", contextImage: "世話を向ける対象", sourceDay: 15 },

  { id: "prep_around_001", preposition: "around", sentence: "I want to travel around the world.", question: "I want to travel (      ) the world.", answer: "around", translation: "私は世界中を旅したいです。", contextImage: "周囲をめぐる", sourceDay: 19 },
  { id: "prep_around_002", preposition: "around", sentence: "Do you want to travel around the world?", question: "Do you want to travel (      ) the world?", answer: "around", translation: "あなたは世界中を旅したいですか。", contextImage: "広い範囲を取り囲む移動", sourceDay: 19 }
];
