window.responseTrainingBank = [
  {
    id: "response_001",
    category: "be動詞",
    topic: "be動詞（現在形）",
    question: "Is she your sister?",
    response: "Yes, she (      ).",
    answer: ["is"],
    completedResponse: "Yes, she is.",
    translationQuestion: "彼女はあなたのお姉さんですか。",
    translationAnswer: "はい、そうです。",
    point: "Is で聞かれたら、is / isn't で答える。"
  },
  {
    id: "response_002",
    category: "be動詞",
    topic: "be動詞（現在形）",
    question: "Are they in the classroom?",
    response: "No, they (      ).",
    answer: ["aren't", "are not"],
    completedResponse: "No, they aren't.",
    translationQuestion: "彼らは教室にいますか。",
    translationAnswer: "いいえ、いません。",
    point: "Are で聞かれたら、are / aren't で返す。"
  },
  {
    id: "response_003",
    category: "be動詞",
    topic: "be動詞（過去形）",
    question: "Was he busy yesterday?",
    response: "Yes, he (      ).",
    answer: ["was"],
    completedResponse: "Yes, he was.",
    translationQuestion: "彼は昨日忙しかったですか。",
    translationAnswer: "はい、忙しかったです。",
    point: "Was の応答は was / wasn't。"
  },
  {
    id: "response_004",
    category: "be動詞",
    topic: "be動詞（過去形）",
    question: "Were you at home last night?",
    response: "No, I (      ).",
    answer: ["wasn't", "was not"],
    completedResponse: "No, I wasn't.",
    translationQuestion: "あなたは昨夜家にいましたか。",
    translationAnswer: "いいえ、いませんでした。",
    point: "Were のときも主語に合わせて be動詞で返す。"
  },
  {
    id: "response_005",
    category: "一般動詞",
    topic: "一般動詞（現在形）",
    question: "Do you play tennis?",
    response: "Yes, I (      ).",
    answer: ["do"],
    completedResponse: "Yes, I do.",
    translationQuestion: "あなたはテニスをしますか。",
    translationAnswer: "はい、します。",
    point: "Do で聞かれたら do / don't。"
  },
  {
    id: "response_006",
    category: "一般動詞",
    topic: "一般動詞（現在形）",
    question: "Does he like math?",
    response: "No, he (      ).",
    answer: ["doesn't", "does not"],
    completedResponse: "No, he doesn't.",
    translationQuestion: "彼は数学が好きですか。",
    translationAnswer: "いいえ、好きではありません。",
    point: "Does の応答は does / doesn't。"
  },
  {
    id: "response_007",
    category: "一般動詞",
    topic: "一般動詞（過去形）",
    question: "Did they watch the game?",
    response: "Yes, they (      ).",
    answer: ["did"],
    completedResponse: "Yes, they did.",
    translationQuestion: "彼らはその試合を見ましたか。",
    translationAnswer: "はい、見ました。",
    point: "Did で聞かれたら did / didn't。"
  },
  {
    id: "response_008",
    category: "一般動詞",
    topic: "一般動詞（過去形）",
    question: "Did you finish your homework?",
    response: "No, I (      ).",
    answer: ["didn't", "did not"],
    completedResponse: "No, I didn't.",
    translationQuestion: "あなたは宿題を終えましたか。",
    translationAnswer: "いいえ、終えていません。",
    point: "過去の一般動詞は did で受ける。"
  },
  {
    id: "response_009",
    category: "助動詞",
    topic: "助動詞（can）",
    question: "Can she swim fast?",
    response: "Yes, she (      ).",
    answer: ["can"],
    completedResponse: "Yes, she can.",
    translationQuestion: "彼女は速く泳げますか。",
    translationAnswer: "はい、泳げます。",
    point: "Can には can / can't で返す。"
  },
  {
    id: "response_010",
    category: "助動詞",
    topic: "助動詞（can）",
    question: "Can you come tomorrow?",
    response: "No, I (      ).",
    answer: ["can't", "can not", "cannot"],
    completedResponse: "No, I can't.",
    translationQuestion: "あなたは明日来られますか。",
    translationAnswer: "いいえ、行けません。",
    point: "助動詞の疑問文は同じ助動詞で応答。"
  },
  {
    id: "response_011",
    category: "助動詞",
    topic: "助動詞（will）",
    question: "Will he join us?",
    response: "Yes, he (      ).",
    answer: ["will"],
    completedResponse: "Yes, he will.",
    translationQuestion: "彼は私たちに加わりますか。",
    translationAnswer: "はい、加わります。",
    point: "Will には will / won't で返す。"
  },
  {
    id: "response_012",
    category: "助動詞",
    topic: "助動詞（must）",
    question: "Must we leave now?",
    response: "No, you (      ).",
    answer: ["mustn't", "must not"],
    completedResponse: "No, you mustn't.",
    translationQuestion: "私たちは今出発しなければなりませんか。",
    translationAnswer: "いいえ、出発してはいけません。",
    point: "Must の否定応答は must not / mustn't。"
  },
  {
    id: "response_013",
    category: "疑問詞",
    topic: "一般動詞",
    question: "What do you want for lunch?",
    response: "I (      ) curry.",
    answer: ["want"],
    completedResponse: "I want curry.",
    translationQuestion: "昼食に何がほしいですか。",
    translationAnswer: "カレーがほしいです。",
    point: "疑問詞の応答は意味に合う短い文で返す。"
  },
  {
    id: "response_014",
    category: "疑問詞",
    topic: "一般動詞",
    question: "Who cooked dinner?",
    response: "My mother (      ).",
    answer: ["did"],
    completedResponse: "My mother did.",
    translationQuestion: "だれが夕食を作りましたか。",
    translationAnswer: "母が作りました。",
    point: "Who ...? の質問に、同じ動詞の繰り返しを避けて did で答えることがある。"
  },
  {
    id: "response_015",
    category: "疑問詞",
    topic: "一般動詞",
    question: "Where do you live?",
    response: "I (      ) in Tokyo.",
    answer: ["live"],
    completedResponse: "I live in Tokyo.",
    translationQuestion: "あなたはどこに住んでいますか。",
    translationAnswer: "私は東京に住んでいます。",
    point: "Where do you ...? と聞かれたら、主語に合う一般動詞で答える。"
  },
  {
    id: "response_016",
    category: "疑問詞",
    topic: "一般動詞（過去形）",
    question: "What did your mother cook?",
    response: "She (      ) curry.",
    answer: ["cooked"],
    completedResponse: "She cooked curry.",
    translationQuestion: "あなたのお母さんは何を作りましたか。",
    translationAnswer: "母はカレーを作りました。",
    point: "did を使った質問でも、答えの文では一般動詞を過去形にする。"
  },
  {
    id: "response_017",
    category: "現在形",
    topic: "一般動詞（現在形）",
    question: "Does your father cook dinner?",
    response: "Yes, he (      ).",
    answer: ["does"],
    completedResponse: "Yes, he does.",
    translationQuestion: "あなたのお父さんは夕食を作りますか。",
    translationAnswer: "はい、作ります。",
    point: "主語が三人称単数なら does / doesn't。"
  },
  {
    id: "response_018",
    category: "現在形",
    topic: "一般動詞（現在形）",
    question: "Do your friends study English every day?",
    response: "No, they (      ).",
    answer: ["don't", "do not"],
    completedResponse: "No, they don't.",
    translationQuestion: "あなたの友だちは毎日英語を勉強しますか。",
    translationAnswer: "いいえ、毎日ではありません。",
    point: "Do の否定応答は don't。"
  },
  {
    id: "response_019",
    category: "過去形",
    topic: "be動詞（過去形）",
    question: "Was the movie interesting?",
    response: "Yes, it (      ).",
    answer: ["was"],
    completedResponse: "Yes, it was.",
    translationQuestion: "その映画はおもしろかったですか。",
    translationAnswer: "はい、おもしろかったです。",
    point: "過去の be 動詞は was / were で応答。"
  },
  {
    id: "response_020",
    category: "過去形",
    topic: "一般動詞（過去形）",
    question: "Did she call you last night?",
    response: "No, she (      ).",
    answer: ["didn't", "did not"],
    completedResponse: "No, she didn't.",
    translationQuestion: "彼女は昨夜あなたに電話しましたか。",
    translationAnswer: "いいえ、しませんでした。",
    point: "Did 疑問文は did / didn't で返す。"
  },
  {
    id: "response_021",
    category: "過去形",
    topic: "一般動詞（過去形）",
    question: "Did he clean his room?",
    response: "Yes, he (      ).",
    answer: ["did"],
    completedResponse: "Yes, he did.",
    translationQuestion: "彼は自分の部屋を掃除しましたか。",
    translationAnswer: "はい、しました。",
    point: "動詞の原形に戻して did で返答。"
  },
  {
    id: "response_022",
    category: "未来表現",
    topic: "助動詞（will）",
    question: "Will you visit Kyoto next month?",
    response: "Yes, I (      ).",
    answer: ["will"],
    completedResponse: "Yes, I will.",
    translationQuestion: "あなたは来月京都を訪れますか。",
    translationAnswer: "はい、訪れます。",
    point: "Will には will / won't で即答。"
  },
  {
    id: "response_023",
    category: "be going to",
    topic: "未来表現 be going to",
    question: "Are they going to study tonight?",
    response: "No, they (      ).",
    answer: ["aren't", "are not"],
    completedResponse: "No, they aren't.",
    translationQuestion: "彼らは今夜勉強する予定ですか。",
    translationAnswer: "いいえ、その予定はありません。",
    point: "be going to は be動詞で受ける。"
  },
  {
    id: "response_024",
    category: "進行形",
    topic: "現在進行形",
    question: "Is he using this computer now?",
    response: "Yes, he (      ).",
    answer: ["is"],
    completedResponse: "Yes, he is.",
    translationQuestion: "彼は今このコンピューターを使っていますか。",
    translationAnswer: "はい、使っています。",
    point: "進行形の疑問文は be動詞で返す。"
  },
  {
    id: "response_025",
    category: "進行形",
    topic: "現在進行形",
    question: "Are you waiting for the bus?",
    response: "No, I (      ).",
    answer: ["am not"],
    completedResponse: "No, I am not.",
    translationQuestion: "あなたはバスを待っていますか。",
    translationAnswer: "いいえ、待っていません。",
    point: "I の否定は am not。"
  },
  {
    id: "response_026",
    category: "比較",
    topic: "比較級",
    question: "Is math more difficult than English?",
    response: "Yes, it (      ).",
    answer: ["is"],
    completedResponse: "Yes, it is.",
    translationQuestion: "数学は英語より難しいですか。",
    translationAnswer: "はい、難しいです。",
    point: "比較文でも疑問の形に合わせて応答。"
  },
  {
    id: "response_027",
    category: "比較",
    topic: "比較級",
    question: "Is this bag cheaper than that one?",
    response: "No, it (      ).",
    answer: ["isn't", "is not"],
    completedResponse: "No, it isn't.",
    translationQuestion: "このバッグはあのバッグより安いですか。",
    translationAnswer: "いいえ、安くありません。",
    point: "be動詞疑問文は be動詞で返す。"
  },
  {
    id: "response_028",
    category: "there is / there are",
    topic: "There is / There are",
    question: "Is there a bank near here?",
    response: "Yes, there (      ).",
    answer: ["is"],
    completedResponse: "Yes, there is.",
    translationQuestion: "この近くに銀行はありますか。",
    translationAnswer: "はい、あります。",
    point: "There is の疑問には there is / there isn't。"
  },
  {
    id: "response_029",
    category: "there is / there are",
    topic: "There is / There are",
    question: "Are there any apples on the table?",
    response: "No, there (      ).",
    answer: ["aren't", "are not"],
    completedResponse: "No, there aren't.",
    translationQuestion: "テーブルの上にりんごはありますか。",
    translationAnswer: "いいえ、ありません。",
    point: "There are の疑問は there are / there aren't。"
  },
  {
    id: "response_030",
    category: "have to",
    topic: "have to",
    question: "Do we have to finish it today?",
    response: "Yes, we (      ).",
    answer: ["do"],
    completedResponse: "Yes, we do.",
    translationQuestion: "私たちはそれを今日終えなければなりませんか。",
    translationAnswer: "はい、終えなければなりません。",
    point: "have to 疑問文は do / don't で返す。"
  },
  {
    id: "response_031",
    category: "want to",
    topic: "want to",
    question: "Do you want to join us?",
    response: "No, I (      ).",
    answer: ["don't", "do not"],
    completedResponse: "No, I don't.",
    translationQuestion: "あなたは私たちと一緒に参加したいですか。",
    translationAnswer: "いいえ、今回は参加しません。",
    point: "want to でも do 疑問文として応答する。"
  }
];
