window.responseTrainingBank = [
  {
    id: "response_001",
    category: "be",
    title: "be動詞（現在）",
    question: "Is she your sister?",
    response: "Yes, she (      ).",
    answer: ["is"],
    translationQuestion: "彼女はあなたのお姉さんですか。",
    translationAnswer: "はい、そうです。",
    point: "Is で聞かれたら、is / isn't で答える。"
  },
  {
    id: "response_002",
    category: "be",
    title: "be動詞（現在）",
    question: "Are they in the classroom?",
    response: "No, they (      ).",
    answer: ["aren't", "are not"],
    translationQuestion: "彼らは教室にいますか。",
    translationAnswer: "いいえ、いません。",
    point: "Are で聞かれたら、are / aren't で返す。"
  },
  {
    id: "response_003",
    category: "be",
    title: "be動詞（過去）",
    question: "Was he busy yesterday?",
    response: "Yes, he (      ).",
    answer: ["was"],
    translationQuestion: "彼は昨日忙しかったですか。",
    translationAnswer: "はい、忙しかったです。",
    point: "Was の応答は was / wasn't。"
  },
  {
    id: "response_004",
    category: "be",
    title: "be動詞（過去）",
    question: "Were you at home last night?",
    response: "No, I (      ).",
    answer: ["wasn't", "was not"],
    translationQuestion: "あなたは昨夜家にいましたか。",
    translationAnswer: "いいえ、いませんでした。",
    point: "Were のときも主語に合わせて be動詞で返す。"
  },
  {
    id: "response_005",
    category: "general",
    title: "一般動詞（現在）",
    question: "Do you play tennis?",
    response: "Yes, I (      ).",
    answer: ["do"],
    translationQuestion: "あなたはテニスをしますか。",
    translationAnswer: "はい、します。",
    point: "Do で聞かれたら do / don't。"
  },
  {
    id: "response_006",
    category: "general",
    title: "一般動詞（現在）",
    question: "Does he like math?",
    response: "No, he (      ).",
    answer: ["doesn't", "does not"],
    translationQuestion: "彼は数学が好きですか。",
    translationAnswer: "いいえ、好きではありません。",
    point: "Does の応答は does / doesn't。"
  },
  {
    id: "response_007",
    category: "general",
    title: "一般動詞（過去）",
    question: "Did they watch the game?",
    response: "Yes, they (      ).",
    answer: ["did"],
    translationQuestion: "彼らはその試合を見ましたか。",
    translationAnswer: "はい、見ました。",
    point: "Did で聞かれたら did / didn't。"
  },
  {
    id: "response_008",
    category: "general",
    title: "一般動詞（過去）",
    question: "Did you finish your homework?",
    response: "No, I (      ).",
    answer: ["didn't", "did not"],
    translationQuestion: "あなたは宿題を終えましたか。",
    translationAnswer: "いいえ、終えていません。",
    point: "過去の一般動詞は did で受ける。"
  },
  {
    id: "response_009",
    category: "modal",
    title: "助動詞 can",
    question: "Can she swim fast?",
    response: "Yes, she (      ).",
    answer: ["can"],
    translationQuestion: "彼女は速く泳げますか。",
    translationAnswer: "はい、泳げます。",
    point: "Can には can / can't で返す。"
  },
  {
    id: "response_010",
    category: "modal",
    title: "助動詞 can",
    question: "Can you come tomorrow?",
    response: "No, I (      ).",
    answer: ["can't", "cannot"],
    translationQuestion: "あなたは明日来られますか。",
    translationAnswer: "いいえ、行けません。",
    point: "助動詞の疑問文は同じ助動詞で応答。"
  },
  {
    id: "response_011",
    category: "modal",
    title: "助動詞 will",
    question: "Will he join us?",
    response: "Yes, he (      ).",
    answer: ["will"],
    translationQuestion: "彼は私たちに加わりますか。",
    translationAnswer: "はい、加わります。",
    point: "Will には will / won't で返す。"
  },
  {
    id: "response_012",
    category: "modal",
    title: "助動詞 must",
    question: "Must we leave now?",
    response: "No, you (      ).",
    answer: ["mustn't", "must not"],
    translationQuestion: "私たちは今出発しなければなりませんか。",
    translationAnswer: "いいえ、出発してはいけません。",
    point: "Must の否定応答は must not / mustn't。"
  },
  {
    id: "response_013",
    category: "wh",
    title: "疑問詞 what",
    question: "What do you want for lunch?",
    response: "I (      ) curry.",
    answer: ["want"],
    translationQuestion: "昼食に何がほしいですか。",
    translationAnswer: "カレーがほしいです。",
    point: "疑問詞の応答は意味に合う短い文で返す。"
  },
  {
    id: "response_014",
    category: "wh",
    title: "疑問詞 who",
    question: "Who helped you?",
    response: "My brother (      ).",
    answer: ["did"],
    translationQuestion: "だれがあなたを手伝ってくれましたか。",
    translationAnswer: "兄が手伝ってくれました。",
    point: "Who の答えは人物を先に出す。"
  },
  {
    id: "response_015",
    category: "wh",
    title: "疑問詞 when",
    question: "When did she arrive?",
    response: "She arrived (      ) 7.",
    answer: ["at"],
    translationQuestion: "彼女はいつ到着しましたか。",
    translationAnswer: "7時に到着しました。",
    point: "When には時刻や時間表現で答える。"
  },
  {
    id: "response_016",
    category: "wh",
    title: "疑問詞 where",
    question: "Where do they play soccer?",
    response: "They play it (      ) the park.",
    answer: ["in"],
    translationQuestion: "彼らはどこでサッカーをしますか。",
    translationAnswer: "公園でします。",
    point: "Where は場所情報を素早く返す。"
  },
  {
    id: "response_017",
    category: "present",
    title: "現在形",
    question: "Does your father cook dinner?",
    response: "Yes, he (      ).",
    answer: ["does"],
    translationQuestion: "あなたのお父さんは夕食を作りますか。",
    translationAnswer: "はい、作ります。",
    point: "主語が三人称単数なら does / doesn't。"
  },
  {
    id: "response_018",
    category: "present",
    title: "現在形",
    question: "Do your friends study English every day?",
    response: "No, they (      ).",
    answer: ["don't", "do not"],
    translationQuestion: "あなたの友だちは毎日英語を勉強しますか。",
    translationAnswer: "いいえ、毎日ではありません。",
    point: "Do の否定応答は don't。"
  },
  {
    id: "response_019",
    category: "past",
    title: "過去形（be）",
    question: "Was the movie interesting?",
    response: "Yes, it (      ).",
    answer: ["was"],
    translationQuestion: "その映画はおもしろかったですか。",
    translationAnswer: "はい、おもしろかったです。",
    point: "過去の be 動詞は was / were で応答。"
  },
  {
    id: "response_020",
    category: "past",
    title: "過去形（一般動詞）",
    question: "Did she call you last night?",
    response: "No, she (      ).",
    answer: ["didn't", "did not"],
    translationQuestion: "彼女は昨夜あなたに電話しましたか。",
    translationAnswer: "いいえ、しませんでした。",
    point: "Did 疑問文は did / didn't で返す。"
  },
  {
    id: "response_021",
    category: "past",
    title: "過去形（一般動詞）",
    question: "Did he clean his room?",
    response: "Yes, he (      ).",
    answer: ["did"],
    translationQuestion: "彼は自分の部屋を掃除しましたか。",
    translationAnswer: "はい、しました。",
    point: "動詞の原形に戻して did で返答。"
  },
  {
    id: "response_022",
    category: "future",
    title: "未来表現 will",
    question: "Will you visit Kyoto next month?",
    response: "Yes, I (      ).",
    answer: ["will"],
    translationQuestion: "あなたは来月京都を訪れますか。",
    translationAnswer: "はい、訪れます。",
    point: "Will には will / won't で即答。"
  },
  {
    id: "response_023",
    category: "future",
    title: "未来表現 be going to",
    question: "Are they going to study tonight?",
    response: "No, they (      ).",
    answer: ["aren't", "are not"],
    translationQuestion: "彼らは今夜勉強する予定ですか。",
    translationAnswer: "いいえ、その予定はありません。",
    point: "be going to は be動詞で受ける。"
  },
  {
    id: "response_024",
    category: "progressive",
    title: "現在進行形",
    question: "Is he using this computer now?",
    response: "Yes, he (      ).",
    answer: ["is"],
    translationQuestion: "彼は今このコンピューターを使っていますか。",
    translationAnswer: "はい、使っています。",
    point: "進行形の疑問文は be動詞で返す。"
  },
  {
    id: "response_025",
    category: "progressive",
    title: "現在進行形",
    question: "Are you waiting for the bus?",
    response: "No, I (      ).",
    answer: ["am not"],
    translationQuestion: "あなたはバスを待っていますか。",
    translationAnswer: "いいえ、待っていません。",
    point: "I の否定は am not。"
  },
  {
    id: "response_026",
    category: "comparison",
    title: "比較",
    question: "Is math more difficult than English?",
    response: "Yes, it (      ).",
    answer: ["is"],
    translationQuestion: "数学は英語より難しいですか。",
    translationAnswer: "はい、難しいです。",
    point: "比較文でも疑問の形に合わせて応答。"
  },
  {
    id: "response_027",
    category: "comparison",
    title: "比較",
    question: "Is this bag cheaper than that one?",
    response: "No, it (      ).",
    answer: ["isn't", "is not"],
    translationQuestion: "このバッグはあのバッグより安いですか。",
    translationAnswer: "いいえ、安くありません。",
    point: "be動詞疑問文は be動詞で返す。"
  },
  {
    id: "response_028",
    category: "other",
    title: "There is / There are",
    question: "Is there a bank near here?",
    response: "Yes, there (      ).",
    answer: ["is"],
    translationQuestion: "この近くに銀行はありますか。",
    translationAnswer: "はい、あります。",
    point: "There is の疑問には there is / there isn't。"
  },
  {
    id: "response_029",
    category: "other",
    title: "There is / There are",
    question: "Are there any apples on the table?",
    response: "No, there (      ).",
    answer: ["aren't", "are not"],
    translationQuestion: "テーブルの上にりんごはありますか。",
    translationAnswer: "いいえ、ありません。",
    point: "There are の疑問は there are / there aren't。"
  },
  {
    id: "response_030",
    category: "other",
    title: "have to",
    question: "Do we have to finish it today?",
    response: "Yes, we (      ).",
    answer: ["do"],
    translationQuestion: "私たちはそれを今日終えなければなりませんか。",
    translationAnswer: "はい、終えなければなりません。",
    point: "have to 疑問文は do / don't で返す。"
  },
  {
    id: "response_031",
    category: "other",
    title: "want to",
    question: "Do you want to join us?",
    response: "No, I (      ).",
    answer: ["don't", "do not"],
    translationQuestion: "あなたは私たちと一緒に参加したいですか。",
    translationAnswer: "いいえ、今回は参加しません。",
    point: "want to でも do 疑問文として応答する。"
  }
];
