function normalizeResponseText(value) {
  return typeof value === "string" ? value.trim() : "";
}

function normalizeResponseAnswerList(value) {
  const source = Array.isArray(value) ? value : value ? [value] : [];
  const out = [];
  const seen = new Set();
  source.forEach((entry) => {
    const normalized = normalizeResponseText(entry);
    if (!normalized || seen.has(normalized)) return;
    seen.add(normalized);
    out.push(normalized);
  });
  return out;
}

function parseResponseIdNumber(id) {
  const match = /^response_(\d+)$/.exec(String(id || "").trim());
  return match ? Number(match[1]) : null;
}

function buildResponseIdResolver(rows) {
  let nextNumber = 1;
  rows.forEach((row) => {
    const parsed = parseResponseIdNumber(row?.id);
    if (Number.isFinite(parsed)) nextNumber = Math.max(nextNumber, parsed + 1);
  });

  const used = new Set();
  return (preferredId) => {
    const safePreferred = normalizeResponseText(preferredId);
    if (safePreferred && !used.has(safePreferred)) {
      used.add(safePreferred);
      return safePreferred;
    }

    let candidate = `response_${String(nextNumber).padStart(3, "0")}`;
    while (used.has(candidate)) {
      nextNumber += 1;
      candidate = `response_${String(nextNumber).padStart(3, "0")}`;
    }
    used.add(candidate);
    nextNumber += 1;
    return candidate;
  };
}

function buildCompletedResponse(response, answers, fallbackCompletedResponse) {
  const explicitCompleted = normalizeResponseText(fallbackCompletedResponse);
  if (explicitCompleted) return explicitCompleted;
  const firstAnswer = answers[0] || "";
  if (!response || !firstAnswer) return "";
  if (response.includes("(      )")) {
    return response.replace("(      )", firstAnswer);
  }
  return response.replace(/\(\s*\)/, firstAnswer);
}

function normalizeResponseTrainingItem(row, resolveId) {
  const question = normalizeResponseText(row?.question);
  const response = normalizeResponseText(row?.response);
  const answers = normalizeResponseAnswerList(row?.answer ?? row?.answers);
  const category = normalizeResponseText(row?.category);
  const topic = normalizeResponseText(row?.topic || row?.title || row?.category);
  const completedResponse = buildCompletedResponse(
    response,
    answers,
    row?.completedResponse || row?.completed || row?.completedAnswer
  );
  const translationQuestion = normalizeResponseText(
    row?.translationQuestion || row?.questionTranslation || row?.translationQ || row?.translation
  );
  const translationAnswer = normalizeResponseText(
    row?.translationAnswer || row?.answerTranslation || row?.translationA
  );
  const point = normalizeResponseText(row?.point || row?.note || row?.memo);

  return {
    id: resolveId(row?.id),
    category,
    topic,
    question,
    response,
    answer: answers,
    completedResponse,
    translationQuestion,
    translationAnswer,
    point
  };
}

function normalizeResponseTrainingBank(rows) {
  const safeRows = Array.isArray(rows) ? rows : [];
  const resolveId = buildResponseIdResolver(safeRows);
  return safeRows
    .map((row) => normalizeResponseTrainingItem(row, resolveId))
    .filter((row) => (
      row.question &&
      row.response &&
      row.answer.length &&
      row.completedResponse &&
      row.category &&
      row.topic &&
      row.point
    ));
}

const responseTrainingBaseItems = [
  {
    id: "response_001",
    category: "be動詞",
    topic: "be動詞（現在形）",
    question: "Is she your sister?",
    response: "Yes, she (      ).",
    answer: ["is"],
    completedResponse: "Yes, she is.",
    translationQuestion: "彼女はあなたのお姉さんですか。",
    translationAnswer: "はい、そうです。",
    point: "Is で聞かれたら、is / isn't で答える。"
  },
  {
    id: "response_002",
    category: "be動詞",
    topic: "be動詞（現在形）",
    question: "Are they in the classroom?",
    response: "No, they (      ).",
    answer: ["aren't", "are not"],
    completedResponse: "No, they aren't.",
    translationQuestion: "彼らは教室にいますか。",
    translationAnswer: "いいえ、いません。",
    point: "Are で聞かれたら、are / aren't で返す。"
  },
  {
    id: "response_003",
    category: "be動詞",
    topic: "be動詞（過去形）",
    question: "Was he busy yesterday?",
    response: "Yes, he (      ).",
    answer: ["was"],
    completedResponse: "Yes, he was.",
    translationQuestion: "彼は昨日忙しかったですか。",
    translationAnswer: "はい、忙しかったです。",
    point: "Was の応答は was / wasn't。"
  },
  {
    id: "response_004",
    category: "be動詞",
    topic: "be動詞（過去形）",
    question: "Were you at home last night?",
    response: "No, I (      ).",
    answer: ["wasn't", "was not"],
    completedResponse: "No, I wasn't.",
    translationQuestion: "あなたは昨夜家にいましたか。",
    translationAnswer: "いいえ、いませんでした。",
    point: "Were のときも主語に合わせて be動詞で返す。"
  },
  {
    id: "response_005",
    category: "一般動詞",
    topic: "一般動詞（現在形）",
    question: "Do you play tennis?",
    response: "Yes, I (      ).",
    answer: ["do"],
    completedResponse: "Yes, I do.",
    translationQuestion: "あなたはテニスをしますか。",
    translationAnswer: "はい、します。",
    point: "Do で聞かれたら do / don't。"
  },
  {
    id: "response_006",
    category: "一般動詞",
    topic: "一般動詞（現在形）",
    question: "Does he like math?",
    response: "No, he (      ).",
    answer: ["doesn't", "does not"],
    completedResponse: "No, he doesn't.",
    translationQuestion: "彼は数学が好きですか。",
    translationAnswer: "いいえ、好きではありません。",
    point: "Does の応答は does / doesn't。"
  },
  {
    id: "response_007",
    category: "一般動詞",
    topic: "一般動詞（過去形）",
    question: "Did they watch the game?",
    response: "Yes, they (      ).",
    answer: ["did"],
    completedResponse: "Yes, they did.",
    translationQuestion: "彼らはその試合を見ましたか。",
    translationAnswer: "はい、見ました。",
    point: "Did で聞かれたら did / didn't。"
  },
  {
    id: "response_008",
    category: "一般動詞",
    topic: "一般動詞（過去形）",
    question: "Did you finish your homework?",
    response: "No, I (      ).",
    answer: ["didn't", "did not"],
    completedResponse: "No, I didn't.",
    translationQuestion: "あなたは宿題を終えましたか。",
    translationAnswer: "いいえ、終えていません。",
    point: "過去の一般動詞は did で受ける。"
  },
  {
    id: "response_009",
    category: "助動詞",
    topic: "助動詞（can）",
    question: "Can she swim fast?",
    response: "Yes, she (      ).",
    answer: ["can"],
    completedResponse: "Yes, she can.",
    translationQuestion: "彼女は速く泳げますか。",
    translationAnswer: "はい、泳げます。",
    point: "Can には can / can't で返す。"
  },
  {
    id: "response_010",
    category: "助動詞",
    topic: "助動詞（can）",
    question: "Can you come tomorrow?",
    response: "No, I (      ).",
    answer: ["can't", "can not", "cannot"],
    completedResponse: "No, I can't.",
    translationQuestion: "あなたは明日来られますか。",
    translationAnswer: "いいえ、行けません。",
    point: "助動詞の疑問文は同じ助動詞で応答。"
  },
  {
    id: "response_011",
    category: "助動詞",
    topic: "助動詞（will）",
    question: "Will he join us?",
    response: "Yes, he (      ).",
    answer: ["will"],
    completedResponse: "Yes, he will.",
    translationQuestion: "彼は私たちに加わりますか。",
    translationAnswer: "はい、加わります。",
    point: "Will には will / won't で即答。"
  },
  {
    id: "response_012",
    category: "助動詞",
    topic: "助動詞（must）",
    question: "Must we leave now?",
    response: "No, you (      ).",
    answer: ["mustn't", "must not"],
    completedResponse: "No, you mustn't.",
    translationQuestion: "私たちは今出発しなければなりませんか。",
    translationAnswer: "いいえ、出発してはいけません。",
    point: "Must の否定応答は must not / mustn't。"
  },
  {
    id: "response_013",
    category: "疑問詞",
    topic: "一般動詞",
    question: "What do you want for lunch?",
    response: "I (      ) curry.",
    answer: ["want"],
    completedResponse: "I want curry.",
    translationQuestion: "昼食に何がほしいですか。",
    translationAnswer: "カレーがほしいです。",
    point: "疑問詞の応答は意味に合う短い文で返す。"
  },
  {
    id: "response_014",
    category: "疑問詞",
    topic: "一般動詞",
    question: "Who cooked dinner?",
    response: "My mother (      ).",
    answer: ["did"],
    completedResponse: "My mother did.",
    translationQuestion: "だれが夕食を作りましたか。",
    translationAnswer: "母が作りました。",
    point: "Who ...? の質問に、同じ動詞の繰り返しを避けて did で答えることがある。"
  },
  {
    id: "response_015",
    category: "疑問詞",
    topic: "一般動詞",
    question: "Where do you live?",
    response: "I (      ) in Tokyo.",
    answer: ["live"],
    completedResponse: "I live in Tokyo.",
    translationQuestion: "あなたはどこに住んでいますか。",
    translationAnswer: "私は東京に住んでいます。",
    point: "Where do you ...? と聞かれたら、主語に合う一般動詞で答える。"
  },
  {
    id: "response_016",
    category: "疑問詞",
    topic: "一般動詞（過去形）",
    question: "What did your mother cook?",
    response: "She (      ) curry.",
    answer: ["cooked"],
    completedResponse: "She cooked curry.",
    translationQuestion: "あなたのお母さんは何を作りましたか。",
    translationAnswer: "母はカレーを作りました。",
    point: "did を使った質問でも、答えの文では一般動詞を過去形にする。"
  },
  {
    id: "response_017",
    category: "現在形",
    topic: "一般動詞（現在形）",
    question: "Does your father cook dinner?",
    response: "Yes, he (      ).",
    answer: ["does"],
    completedResponse: "Yes, he does.",
    translationQuestion: "あなたのお父さんは夕食を作りますか。",
    translationAnswer: "はい、作ります。",
    point: "主語が三人称単数なら does / doesn't。"
  },
  {
    id: "response_018",
    category: "現在形",
    topic: "一般動詞（現在形）",
    question: "Do your friends study English every day?",
    response: "No, they (      ).",
    answer: ["don't", "do not"],
    completedResponse: "No, they don't.",
    translationQuestion: "あなたの友だちは毎日英語を勉強しますか。",
    translationAnswer: "いいえ、毎日ではありません。",
    point: "Do の否定応答は don't。"
  },
  {
    id: "response_019",
    category: "過去形",
    topic: "be動詞（過去形）",
    question: "Was the movie interesting?",
    response: "Yes, it (      ).",
    answer: ["was"],
    completedResponse: "Yes, it was.",
    translationQuestion: "その映画はおもしろかったですか。",
    translationAnswer: "はい、おもしろかったです。",
    point: "過去の be 動詞は was / were で応答。"
  },
  {
    id: "response_020",
    category: "過去形",
    topic: "一般動詞（過去形）",
    question: "Did she call you last night?",
    response: "No, she (      ).",
    answer: ["didn't", "did not"],
    completedResponse: "No, she didn't.",
    translationQuestion: "彼女は昨夜あなたに電話しましたか。",
    translationAnswer: "いいえ、しませんでした。",
    point: "Did 疑問文は did / didn't で返す。"
  },
  {
    id: "response_021",
    category: "過去形",
    topic: "一般動詞（過去形）",
    question: "Did he clean his room?",
    response: "Yes, he (      ).",
    answer: ["did"],
    completedResponse: "Yes, he did.",
    translationQuestion: "彼は自分の部屋を掃除しましたか。",
    translationAnswer: "はい、しました。",
    point: "動詞の原形に戻して did で返答。"
  },
  {
    id: "response_022",
    category: "未来表現",
    topic: "助動詞（will）",
    question: "Will you visit Kyoto next month?",
    response: "Yes, I (      ).",
    answer: ["will"],
    completedResponse: "Yes, I will.",
    translationQuestion: "あなたは来月京都を訪れますか。",
    translationAnswer: "はい、訪れます。",
    point: "Will には will / won't で即答。"
  },
  {
    id: "response_023",
    category: "be going to",
    topic: "未来表現 be going to",
    question: "Are they going to study tonight?",
    response: "No, they (      ).",
    answer: ["aren't", "are not"],
    completedResponse: "No, they aren't.",
    translationQuestion: "彼らは今夜勉強する予定ですか。",
    translationAnswer: "いいえ、その予定はありません。",
    point: "be going to は be動詞で受ける。"
  },
  {
    id: "response_024",
    category: "進行形",
    topic: "現在進行形",
    question: "Is he using this computer now?",
    response: "Yes, he (      ).",
    answer: ["is"],
    completedResponse: "Yes, he is.",
    translationQuestion: "彼は今このコンピューターを使っていますか。",
    translationAnswer: "はい、使っています。",
    point: "進行形の疑問文は be動詞で返す。"
  },
  {
    id: "response_025",
    category: "進行形",
    topic: "現在進行形",
    question: "Are you waiting for the bus?",
    response: "No, I (      ).",
    answer: ["am not"],
    completedResponse: "No, I am not.",
    translationQuestion: "あなたはバスを待っていますか。",
    translationAnswer: "いいえ、待っていません。",
    point: "I の否定は am not。"
  },
  {
    id: "response_026",
    category: "比較",
    topic: "比較級",
    question: "Is math more difficult than English?",
    response: "Yes, it (      ).",
    answer: ["is"],
    completedResponse: "Yes, it is.",
    translationQuestion: "数学は英語より難しいですか。",
    translationAnswer: "はい、難しいです。",
    point: "比較文でも疑問の形に合わせて応答。"
  },
  {
    id: "response_027",
    category: "比較",
    topic: "比較級",
    question: "Is this bag cheaper than that one?",
    response: "No, it (      ).",
    answer: ["isn't", "is not"],
    completedResponse: "No, it isn't.",
    translationQuestion: "このバッグはあのバッグより安いですか。",
    translationAnswer: "いいえ、安くありません。",
    point: "be動詞疑問文は be動詞で返す。"
  },
  {
    id: "response_028",
    category: "there is / there are",
    topic: "There is / There are",
    question: "Is there a bank near here?",
    response: "Yes, there (      ).",
    answer: ["is"],
    completedResponse: "Yes, there is.",
    translationQuestion: "この近くに銀行はありますか。",
    translationAnswer: "はい、あります。",
    point: "There is の疑問には there is / there isn't。"
  },
  {
    id: "response_029",
    category: "there is / there are",
    topic: "There is / There are",
    question: "Are there any apples on the table?",
    response: "No, there (      ).",
    answer: ["aren't", "are not"],
    completedResponse: "No, there aren't.",
    translationQuestion: "テーブルの上にりんごはありますか。",
    translationAnswer: "いいえ、ありません。",
    point: "There are の疑問は there are / there aren't。"
  },
  {
    id: "response_030",
    category: "have to",
    topic: "have to",
    question: "Do we have to finish it today?",
    response: "Yes, we (      ).",
    answer: ["do"],
    completedResponse: "Yes, we do.",
    translationQuestion: "私たちはそれを今日終えなければなりませんか。",
    translationAnswer: "はい、終えなければなりません。",
    point: "have to 疑問文は do / don't で返す。"
  },
  {
    id: "response_031",
    category: "want to",
    topic: "want to",
    question: "Do you want to join us?",
    response: "No, I (      ).",
    answer: ["don't", "do not"],
    completedResponse: "No, I don't.",
    translationQuestion: "あなたは私たちと一緒に参加したいですか。",
    translationAnswer: "いいえ、今回は参加しません。",
    point: "want to でも do 疑問文として応答する。"
  }
];

// 今後の追加問題はこの配列の末尾に貼り付ける。
// 既存問題は残り、id が重複しても自動で振り直される。
// title しかない場合は topic として補完し、completedResponse がない場合は
// response と answer から可能な範囲で自動生成する。
const responseTrainingAppendedItems = [
  {
    id: "response_032",
    category: "be動詞",
    topic: "be動詞（現在形）",
    question: "Is your brother going to play in the baseball game that will be held this Saturday?",
    response: "Yes, he (      ).",
    answer: ["is"],
    completedResponse: "Yes, he is.",
    translationQuestion: "あなたのお兄さん（弟）は今週土曜日に行われる野球の試合に出場する予定ですか。",
    translationAnswer: "はい、その予定です。",
    point: "be going to の質問は be動詞で答える。"
  },
  {
    id: "response_033",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your father usually work?",
    response: "He (      ) in Tokyo.",
    answer: ["Where", "works"],
    completedResponse: "Where does your father usually work?He works in Tokyo.",
    translationQuestion: "あなたのお父さんは普段どこで働いていますか。",
    translationAnswer: "お父さんは普段どこで働いていますか。東京で働いています。",
    point: "Where＋does＋works のセットを覚える。"
  },
  {
    id: "response_034",
    category: "一般動詞",
    topic: "一般動詞（過去形）",
    question: "Did your English teacher explain today's homework before the class ended?",
    response: "Yes, she (      ).",
    answer: ["did"],
    completedResponse: "Yes, she did.",
    translationQuestion: "英語の先生は授業が終わる前に今日の宿題を説明しましたか。",
    translationAnswer: "はい、説明しました。",
    point: "Did の質問は did で返す。"
  },
  {
    id: "response_035",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) time does your first class begin every morning?",
    response: "It (      ) at 8:30.",
    answer: ["What", "begins"],
    completedResponse: "What time does your first class begin every morning?It begins at 8:30.",
    translationQuestion: "毎朝1時間目は何時に始まりますか。",
    translationAnswer: "毎朝1時間目は何時に始まりますか。8時30分に始まります。",
    point: "What time と三単現 begins を同時に練習する。"
  },
  {
    id: "response_036",
    category: "助動詞",
    topic: "助動詞（can）",
    question: "Can you lend me your English dictionary after school today?",
    response: "Yes, I (      ).",
    answer: ["can"],
    completedResponse: "Yes, I can.",
    translationQuestion: "今日放課後、英和辞典を貸してくれますか。",
    translationAnswer: "はい、貸せます。",
    point: "Can の質問は can で返す。"
  },
  {
    id: "response_037",
    category: "三単現",
    topic: "三単現",
    question: "What sport does your sister enjoy the most?",
    response: "She (      ) tennis the most.",
    answer: ["enjoys"],
    completedResponse: "She enjoys tennis the most.",
    translationQuestion: "あなたのお姉さん（妹）は何のスポーツが一番好きですか。",
    translationAnswer: "彼女はテニスが一番好きです。",
    point: "三単現では enjoys のように s が付く。"
  },
  {
    id: "response_038",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) often do you practice baseball after school?",
    response: "I (      ) almost every day.",
    answer: ["How", "practice"],
    completedResponse: "How often do you practice baseball after school?I practice almost every day.",
    translationQuestion: "放課後どのくらいの頻度で野球を練習しますか。",
    translationAnswer: "放課後どのくらいの頻度で野球を練習しますか。ほぼ毎日練習します。",
    point: "How often は頻度を尋ねる。"
  },
  {
    id: "response_039",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Are your classmates preparing for next week's English test now?",
    response: "Yes, they (      ).",
    answer: ["are"],
    completedResponse: "Yes, they are.",
    translationQuestion: "クラスメートは今、来週の英語のテストの準備をしていますか。",
    translationAnswer: "はい、しています。",
    point: "現在進行形は be動詞で答える。"
  },
  {
    id: "response_040",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your mother usually get home from work?",
    response: "She (      ) home around six.",
    answer: ["When", "gets"],
    completedResponse: "When does your mother usually get home from work?She gets home around six.",
    translationQuestion: "お母さんは普段何時に仕事から帰宅しますか。",
    translationAnswer: "お母さんは普段何時に仕事から帰宅しますか。6時ごろ帰宅します。",
    point: "does の後は原形、答えは gets。"
  },
  {
    id: "response_041",
    category: "be動詞",
    topic: "be動詞",
    question: "Is your classroom one of the largest classrooms in your school?",
    response: "No, it (      ).",
    answer: ["isn't"],
    completedResponse: "No, it isn't.",
    translationQuestion: "あなたの教室は学校で最も大きい教室の一つですか。",
    translationAnswer: "いいえ、違います。",
    point: "Is の否定は isn't。"
  },
  {
    id: "response_042",
    category: "助動詞",
    topic: "助動詞（will）",
    question: "Will your class visit the science museum during the school trip next month?",
    response: "Yes, we (      ).",
    answer: ["will"],
    completedResponse: "Yes, we will.",
    translationQuestion: "来月の校外学習で、あなたのクラスは科学館を訪れる予定ですか。",
    translationAnswer: "はい、訪れる予定です。",
    point: "Will の質問は will で答える。"
  },
  {
    id: "response_043",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your English teacher usually give homework?",
    response: "She (      ) us to practice English every day.",
    answer: ["Why", "wants"],
    completedResponse: "Why does your English teacher usually give homework?She wants us to practice English every day.",
    translationQuestion: "英語の先生はなぜいつも宿題を出すのですか。",
    translationAnswer: "英語の先生はなぜいつも宿題を出すのですか。毎日英語を練習してほしいからです。",
    point: "Why と三単現 wants を同時に練習する。"
  },
  {
    id: "response_044",
    category: "一般動詞",
    topic: "一般動詞（過去形）",
    question: "Did your family enjoy watching the fireworks during the summer festival?",
    response: "Yes, we (      ).",
    answer: ["did"],
    completedResponse: "Yes, we did.",
    translationQuestion: "家族は夏祭りで花火を見るのを楽しみましたか。",
    translationAnswer: "はい、楽しみました。",
    point: "Did の質問には did で答える。"
  },
  {
    id: "response_045",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) many students are going to join the English speech contest?",
    response: "About thirty students (      ).",
    answer: ["How", "are"],
    completedResponse: "How many students are going to join the English speech contest?About thirty students are.",
    translationQuestion: "英語スピーチコンテストには何人の生徒が参加する予定ですか。",
    translationAnswer: "英語スピーチコンテストには何人参加する予定ですか。約30人です。",
    point: "How many は人数・個数を尋ねる。"
  },
  {
    id: "response_046",
    category: "助動詞",
    topic: "助動詞（can）",
    question: "Can your best friend solve difficult math problems without using a calculator?",
    response: "No, he (      ).",
    answer: ["can't"],
    completedResponse: "No, he can't.",
    translationQuestion: "あなたの親友は電卓を使わずに難しい数学の問題を解けますか。",
    translationAnswer: "いいえ、解けません。",
    point: "can't を素早く答えられるようにする。"
  },
  {
    id: "response_047",
    category: "三単現",
    topic: "三単現",
    question: "What time does your father usually leave home on weekdays?",
    response: "He (      ) home at seven.",
    answer: ["leaves"],
    completedResponse: "He leaves home at seven.",
    translationQuestion: "お父さんは平日何時に家を出ますか。",
    translationAnswer: "7時に家を出ます。",
    point: "leave の三単現は leaves。"
  },
  {
    id: "response_048",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) do you usually spend your summer vacation?",
    response: "I (      ) time with my grandparents.",
    answer: ["How", "spend"],
    completedResponse: "How do you usually spend your summer vacation?I spend time with my grandparents.",
    translationQuestion: "夏休みは普段どのように過ごしますか。",
    translationAnswer: "夏休みは祖父母と過ごします。",
    point: "How は方法・様子を尋ねる。"
  },
  {
    id: "response_049",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Is your sister studying for tomorrow's math test in her room now?",
    response: "Yes, she (      ).",
    answer: ["is"],
    completedResponse: "Yes, she is.",
    translationQuestion: "お姉さん（妹）は今、自分の部屋で明日の数学のテスト勉強をしていますか。",
    translationAnswer: "はい、勉強しています。",
    point: "現在進行形は be動詞で答える。"
  },
  {
    id: "response_050",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) subject does your brother like the most?",
    response: "He (      ) science the most.",
    answer: ["Which", "likes"],
    completedResponse: "Which subject does your brother like the most?He likes science the most.",
    translationQuestion: "あなたのお兄さん（弟）は何の教科が一番好きですか。",
    translationAnswer: "一番好きな教科は理科です。",
    point: "Which と likes を同時に練習する。"
  },
  {
    id: "response_051",
    category: "be動詞",
    topic: "be動詞",
    question: "Are you ready to give your presentation in front of the whole class tomorrow?",
    response: "Yes, I (      ).",
    answer: ["am"],
    completedResponse: "Yes, I am.",
    translationQuestion: "明日、クラス全員の前で発表する準備はできていますか。",
    translationAnswer: "はい、準備できています。",
    point: "be ready to ～ は学校でも英検でもよく使われる重要表現。"
  },
  {
    id: "response_052",
    category: "一般動詞",
    topic: "一般動詞（三単現）",
    question: "Does your mother always prepare breakfast before everyone gets up?",
    response: "Yes, she (      ).",
    answer: ["does"],
    completedResponse: "Yes, she does.",
    translationQuestion: "お母さんはみんなが起きる前に、いつも朝食を準備しますか。",
    translationAnswer: "はい、準備します。",
    point: "Does の質問には does で答える。"
  },
  {
    id: "response_053",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your father usually come home after work?",
    response: "He (      ) home around seven.",
    answer: ["When", "comes"],
    completedResponse: "When does your father usually come home after work?He comes home around seven.",
    translationQuestion: "お父さんは仕事の後、普段何時に帰宅しますか。",
    translationAnswer: "お父さんは普段7時ごろ帰宅します。",
    point: "come の三単現は comes。"
  },
  {
    id: "response_054",
    category: "助動詞",
    topic: "助動詞（should）",
    question: "Should we finish our science project before this Friday?",
    response: "Yes, we (      ).",
    answer: ["should"],
    completedResponse: "Yes, we should.",
    translationQuestion: "今週の金曜日までに理科の課題を終わらせるべきですか。",
    translationAnswer: "はい、その方がいいです。",
    point: "Should の質問には should で答える。"
  },
  {
    id: "response_055",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) long have you practiced the piano?",
    response: "I (      ) for about five years.",
    answer: ["How", "have", "practiced"],
    completedResponse: "How long have you practiced the piano?I have practiced for about five years.",
    translationQuestion: "ピアノはどのくらい練習していますか。",
    translationAnswer: "約5年間練習しています。",
    point: "How long + 現在完了 は英検3級ではやや発展的です。"
  },
  {
    id: "response_056",
    category: "助動詞",
    topic: "助動詞（will）",
    question: "Will your grandparents come to watch your baseball game this weekend?",
    response: "Yes, they (      ).",
    answer: ["will"],
    completedResponse: "Yes, they will.",
    translationQuestion: "今週末、おじいさんとおばあさんはあなたの野球の試合を見に来ますか。",
    translationAnswer: "はい、来ます。",
    point: "Will の質問には will で答える。"
  },
  {
    id: "response_057",
    category: "三単現",
    topic: "三単現",
    question: "Where does your English teacher usually park her car?",
    response: "She (      ) it near the school.",
    answer: ["parks"],
    completedResponse: "Where does your English teacher usually park her car?She parks it near the school.",
    translationQuestion: "英語の先生は普段どこに車を止めますか。",
    translationAnswer: "学校の近くに止めます。",
    point: "park の三単現は parks。"
  },
  {
    id: "response_058",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Are your classmates cleaning the classroom before the next lesson starts?",
    response: "Yes, they (      ).",
    answer: ["are"],
    completedResponse: "Yes, they are.",
    translationQuestion: "クラスメートは次の授業が始まる前に教室を掃除していますか。",
    translationAnswer: "はい、掃除しています。",
    point: "現在進行形は be動詞で答える。"
  },
  {
    id: "response_059",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your sister want to become in the future?",
    response: "She (      ) to become a nurse.",
    answer: ["What", "wants"],
    completedResponse: "What does your sister want to become in the future?She wants to become a nurse.",
    translationQuestion: "あなたのお姉さん（妹）は将来何になりたいですか。",
    translationAnswer: "将来は看護師になりたいと思っています。",
    point: "want の三単現は wants。"
  },
  {
    id: "response_060",
    category: "一般動詞",
    topic: "一般動詞（過去形）",
    question: "Did your class visit the history museum during last month's school trip?",
    response: "No, we (      ).",
    answer: ["didn't"],
    completedResponse: "No, we didn't.",
    translationQuestion: "先月の校外学習で歴史博物館を見学しましたか。",
    translationAnswer: "いいえ、見学しませんでした。",
    point: "Did の否定は didn't。"
  },
  {
    id: "response_061",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) much milk do you drink every morning?",
    response: "I (      ) about two glasses.",
    answer: ["How", "drink"],
    completedResponse: "How much milk do you drink every morning?I drink about two glasses.",
    translationQuestion: "毎朝どのくらい牛乳を飲みますか。",
    translationAnswer: "毎朝コップ2杯くらい飲みます。",
    point: "How much は量を尋ねる。"
  },
  {
    id: "response_062",
    category: "現在完了",
    topic: "現在完了",
    question: "Have you already finished your English homework for tomorrow?",
    response: "Yes, I (      ).",
    answer: ["have"],
    completedResponse: "Yes, I have.",
    translationQuestion: "明日の英語の宿題はもう終わりましたか。",
    translationAnswer: "はい、終わりました。",
    point: "Haveで聞かれたら have で答える。"
  },
  {
    id: "response_063",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your father usually read before going to bed?",
    response: "He (      ) the newspaper.",
    answer: ["What", "reads"],
    completedResponse: "What does your father usually read before going to bed?He reads the newspaper.",
    translationQuestion: "お父さんは寝る前に普段何を読みますか。",
    translationAnswer: "お父さんは寝る前に新聞を読みます。",
    point: "read の三単現は reads。"
  },
  {
    id: "response_064",
    category: "助動詞",
    topic: "助動詞（must）",
    question: "Must all students wear their school uniforms during the school festival?",
    response: "Yes, they (      ).",
    answer: ["must"],
    completedResponse: "Yes, they must.",
    translationQuestion: "学校祭では全員制服を着なければなりませんか。",
    translationAnswer: "はい、着なければなりません。",
    point: "Must の質問には must で答える。"
  },
  {
    id: "response_065",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your mother usually go shopping on weekends?",
    response: "She (      ) shopping on Saturday afternoons.",
    answer: ["When", "goes"],
    completedResponse: "When does your mother usually go shopping on weekends?She goes shopping on Saturday afternoons.",
    translationQuestion: "お母さんは週末いつ買い物へ行きますか。",
    translationAnswer: "お母さんは土曜日の午後に買い物へ行きます。",
    point: "go の三単現は goes。"
  },
  {
    id: "response_066",
    category: "現在完了",
    topic: "現在完了",
    question: "Has your brother ever visited Kyoto with his classmates?",
    response: "No, he (      ).",
    answer: ["hasn't"],
    completedResponse: "No, he hasn't.",
    translationQuestion: "あなたのお兄さん（弟）はクラスメートと京都へ行ったことがありますか。",
    translationAnswer: "いいえ、ありません。",
    point: "Has の質問は has / hasn't で答える。"
  },
  {
    id: "response_067",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) do you usually go to the library after school?",
    response: "I (      ) to study with my friends.",
    answer: ["Why", "go"],
    completedResponse: "Why do you usually go to the library after school?I go to study with my friends.",
    translationQuestion: "なぜ放課後によく図書館へ行くのですか。",
    translationAnswer: "友達と勉強するために行きます。",
    point: "Why は理由を答える。"
  },
  {
    id: "response_068",
    category: "助動詞",
    topic: "助動詞（will）",
    question: "Will your science teacher give you another experiment next week?",
    response: "I think he (      ).",
    answer: ["will"],
    completedResponse: "I think he will.",
    translationQuestion: "理科の先生は来週また実験をさせてくれますか。",
    translationAnswer: "はい、そう思います。",
    point: "I think ～ を自然に使えるようにする。"
  },
  {
    id: "response_069",
    category: "三単現",
    topic: "三単現",
    question: "What time does your school library close on weekdays?",
    response: "It (      ) at five.",
    answer: ["closes"],
    completedResponse: "It closes at five.",
    translationQuestion: "学校の図書館は平日何時に閉まりますか。",
    translationAnswer: "5時に閉まります。",
    point: "close の三単現は closes。"
  },
  {
    id: "response_070",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Are your classmates talking about tomorrow's English test now?",
    response: "No, they (      ).",
    answer: ["aren't"],
    completedResponse: "No, they aren't.",
    translationQuestion: "クラスメートは今、明日の英語のテストについて話していますか。",
    translationAnswer: "いいえ、話していません。",
    point: "Are の否定は aren't。"
  },
  {
    id: "response_071",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your father always drive to work instead of taking the train?",
    response: "He (      ) because his office is far away.",
    answer: ["Why", "drives"],
    completedResponse: "Why does your father always drive to work instead of taking the train?He drives because his office is far away.",
    translationQuestion: "お父さんはなぜ電車ではなく、いつも車で通勤するのですか。",
    translationAnswer: "会社が遠いので車で通勤しています。",
    point: "Why＋does＋drives の形をまとめて覚える。"
  },
  {
    id: "response_072",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your brother usually spend his Sunday afternoons?",
    response: "He (      ) baseball with his friends.",
    answer: ["How", "plays"],
    completedResponse: "How does your brother usually spend his Sunday afternoons?He plays baseball with his friends.",
    translationQuestion: "あなたのお兄さん（弟）は日曜日の午後を普段どのように過ごしますか。",
    translationAnswer: "日曜日の午後は友達と野球をしています。",
    point: "How と plays（三単現）を同時に覚える。"
  },
  {
    id: "response_073",
    category: "現在完了",
    topic: "現在完了",
    question: "Have you ever borrowed a book from your school library?",
    response: "Yes, I (      ).",
    answer: ["have"],
    completedResponse: "Yes, I have.",
    translationQuestion: "学校の図書館で本を借りたことがありますか。",
    translationAnswer: "はい、あります。",
    point: "Have you ever ～? は英検3級頻出。"
  },
  {
    id: "response_074",
    category: "助動詞",
    topic: "助動詞（can）",
    question: "Can your English teacher speak more than two foreign languages?",
    response: "Yes, she (      ).",
    answer: ["can"],
    completedResponse: "Yes, she can.",
    translationQuestion: "英語の先生は2か国語以上の外国語を話せますか。",
    translationAnswer: "はい、話せます。",
    point: "Can の質問には can。"
  },
  {
    id: "response_075",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your mother usually cook for dinner on Fridays?",
    response: "She (      ) curry.",
    answer: ["What", "cooks"],
    completedResponse: "What does your mother usually cook for dinner on Fridays?She cooks curry.",
    translationQuestion: "お母さんは金曜日の夕食に普段何を作りますか。",
    translationAnswer: "金曜日はカレーを作ります。",
    point: "cook の三単現は cooks。"
  },
  {
    id: "response_076",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Is your father talking with your homeroom teacher right now?",
    response: "No, he (      ).",
    answer: ["isn't"],
    completedResponse: "No, he isn't.",
    translationQuestion: "お父さんは今、担任の先生と話していますか。",
    translationAnswer: "いいえ、話していません。",
    point: "進行形は be動詞で答える。"
  },
  {
    id: "response_077",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) often do your grandparents visit your family?",
    response: "They (      ) us about once a month.",
    answer: ["How", "visit"],
    completedResponse: "How often do your grandparents visit your family?They visit us about once a month.",
    translationQuestion: "おじいさんとおばあさんはどのくらいの頻度で遊びに来ますか。",
    translationAnswer: "月に1回くらい遊びに来ます。",
    point: "How often は頻度を尋ねる。"
  },
  {
    id: "response_078",
    category: "助動詞",
    topic: "助動詞（must）",
    question: "Must students turn off their smartphones during class?",
    response: "Yes, they (      ).",
    answer: ["must"],
    completedResponse: "Yes, they must.",
    translationQuestion: "授業中はスマートフォンの電源を切らなければなりませんか。",
    translationAnswer: "はい、切らなければなりません。",
    point: "Must の質問には must。"
  },
  {
    id: "response_079",
    category: "三単現",
    topic: "三単現",
    question: "Where does your grandfather keep his favorite books?",
    response: "He (      ) them in his study.",
    answer: ["keeps"],
    completedResponse: "Where does your grandfather keep his favorite books?He keeps them in his study.",
    translationQuestion: "おじいさんはお気に入りの本をどこに置いていますか。",
    translationAnswer: "書斎に置いています。",
    point: "keep の三単現は keeps。"
  },
  {
    id: "response_080",
    category: "現在完了",
    topic: "現在完了",
    question: "Has your class already decided where to go for the school trip?",
    response: "Yes, it (      ).",
    answer: ["has"],
    completedResponse: "Yes, it has.",
    translationQuestion: "クラスはもう修学旅行の行き先を決めましたか。",
    translationAnswer: "はい、決まりました。",
    point: "Has の質問には has で答える。"
  },
  {
    id: "response_081",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your science teacher always explain difficult experiments so clearly?",
    response: "He (      ) many examples.",
    answer: ["Why", "uses"],
    completedResponse: "Why does your science teacher always explain difficult experiments so clearly?He uses many examples.",
    translationQuestion: "理科の先生はなぜ難しい実験をいつもあんなに分かりやすく説明するのですか。",
    translationAnswer: "たくさんの例を使うからです。",
    point: "use の三単現は uses。"
  },
  {
    id: "response_082",
    category: "現在完了",
    topic: "現在完了",
    question: "Have you finished reading the English book your teacher recommended?",
    response: "No, I (      )(      ).",
    answer: ["have", "not"],
    completedResponse: "No, I have not.",
    translationQuestion: "先生がおすすめした英語の本はもう読み終わりましたか。",
    translationAnswer: "いいえ、まだ読み終わっていません。",
    point: "現在完了の否定は have not / haven't。"
  },
  {
    id: "response_083",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your sister always finish her homework before dinner?",
    response: "She (      ) to relax after dinner.",
    answer: ["Why", "wants"],
    completedResponse: "Why does your sister always finish her homework before dinner?She wants to relax after dinner.",
    translationQuestion: "お姉さん（妹）はなぜ夕食前に宿題を終わらせるのですか。",
    translationAnswer: "夕食後はゆっくりしたいからです。",
    point: "want の三単現は wants。"
  },
  {
    id: "response_084",
    category: "助動詞",
    topic: "助動詞（could）",
    question: "Could you help me carry these heavy boxes to the music room?",
    response: "Yes, I (      ).",
    answer: ["could"],
    completedResponse: "Yes, I could.",
    translationQuestion: "この重い箱を音楽室まで運ぶのを手伝ってくれませんか。",
    translationAnswer: "はい、お手伝いできます。",
    point: "Could は丁寧な依頼表現。英検3級でも見かける。"
  },
  {
    id: "response_085",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your father usually spend his holidays?",
    response: "He (      ) fishing with his friends.",
    answer: ["How", "goes"],
    completedResponse: "How does your father usually spend his holidays?He goes fishing with his friends.",
    translationQuestion: "お父さんは休日を普段どのように過ごしますか。",
    translationAnswer: "休日は友達と釣りへ行きます。",
    point: "go fishing は重要熟語。三単現は goes。"
  },
  {
    id: "response_086",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Are your classmates discussing the answers after today's English test?",
    response: "Yes, they (      ).",
    answer: ["are"],
    completedResponse: "Yes, they are.",
    translationQuestion: "クラスメートは今日の英語のテストの答え合わせをしていますか。",
    translationAnswer: "はい、しています。",
    point: "現在進行形は be動詞で答える。"
  },
  {
    id: "response_087",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) many countries would you like to visit in the future?",
    response: "I (      ) to visit at least ten.",
    answer: ["How", "want"],
    completedResponse: "How many countries would you like to visit in the future?I want to visit at least ten.",
    translationQuestion: "将来、何か国くらい訪れてみたいですか。",
    translationAnswer: "少なくとも10か国は訪れてみたいです。",
    point: "How many は数量を尋ねる。"
  },
  {
    id: "response_088",
    category: "助動詞",
    topic: "助動詞（must）",
    question: "Must you submit this report before your science class starts tomorrow?",
    response: "No, I (      )(      ) (      ).",
    answer: ["don't", "have", "to"],
    completedResponse: "No, I don't have to.",
    translationQuestion: "明日の理科の授業が始まる前に、このレポートを提出しなければなりませんか。",
    translationAnswer: "いいえ、してはいけません。",
    point: "正式形 must not の形も覚える。"
  },
  {
    id: "response_089",
    category: "三単現",
    topic: "三単現",
    question: "What does your grandfather usually grow in his garden?",
    response: "He (      ) tomatoes and cucumbers.",
    answer: ["grows"],
    completedResponse: "What does your grandfather usually grow in his garden?He grows tomatoes and cucumbers.",
    translationQuestion: "おじいさんは庭で普段何を育てていますか。",
    translationAnswer: "トマトやきゅうりを育てています。",
    point: "grow の三単現は grows。"
  },
  {
    id: "response_090",
    category: "現在完了",
    topic: "現在完了",
    question: "Has your teacher already checked your English notebook?",
    response: "Yes, she (      ).",
    answer: ["has"],
    completedResponse: "Yes, she has.",
    translationQuestion: "先生はもうあなたの英語ノートを確認しましたか。",
    translationAnswer: "はい、確認しました。",
    point: "Has の質問は has で答える。"
  },
  {
    id: "response_091",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your mother always choose this supermarket instead of the closer one?",
    response: "She (      ) the vegetables there are fresher.",
    answer: ["Why", "thinks"],
    completedResponse: "Why does your mother always choose this supermarket instead of the closer one?She thinks the vegetables there are fresher.",
    translationQuestion: "お母さんはなぜもっと近いスーパーではなく、いつもこのスーパーを選ぶのですか。",
    translationAnswer: "そこの野菜の方が新鮮だと思っているからです。",
    point: "think の三単現は thinks。理由を答える英文としても自然な形を覚える。"
  },
  {
    id: "response_092",
    category: "現在完了",
    topic: "現在完了",
    question: "Have you ever spoken with a student from another country in English?",
    response: "Yes, I (      ).",
    answer: ["have"],
    completedResponse: "Yes, I have.",
    translationQuestion: "外国の生徒と英語で話したことがありますか。",
    translationAnswer: "はい、あります。",
    point: "Have you ever ～? は英検3級頻出表現。"
  },
  {
    id: "response_093",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your father usually exercise before going to work?",
    response: "He (      ) at a nearby gym.",
    answer: ["Where", "exercises"],
    completedResponse: "Where does your father usually exercise before going to work?He exercises at a nearby gym.",
    translationQuestion: "お父さんは仕事へ行く前にどこで運動しますか。",
    translationAnswer: "近くのジムで運動します。",
    point: "exercise の三単現は exercises。"
  },
  {
    id: "response_094",
    category: "助動詞",
    topic: "助動詞（will）",
    question: "Will your class perform a play at the school festival this year?",
    response: "Yes, we (      ).",
    answer: ["will"],
    completedResponse: "Yes, we will.",
    translationQuestion: "今年の学校祭で、あなたのクラスは劇を発表しますか。",
    translationAnswer: "はい、発表します。",
    point: "Will の質問は will で答える。"
  },
  {
    id: "response_095",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) subject does your sister study the longest every evening?",
    response: "She (      ) English the longest.",
    answer: ["Which", "studies"],
    completedResponse: "Which subject does your sister study the longest every evening?She studies English the longest.",
    translationQuestion: "お姉さん（妹）は毎晩どの教科を一番長く勉強しますか。",
    translationAnswer: "英語を一番長く勉強します。",
    point: "study の三単現は studies。"
  },
  {
    id: "response_096",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Is your mother preparing tomorrow's lunch before going to bed?",
    response: "No, she (      ).",
    answer: ["isn't"],
    completedResponse: "No, she isn't.",
    translationQuestion: "お母さんは寝る前に明日のお弁当を準備していますか。",
    translationAnswer: "いいえ、準備していません。",
    point: "現在進行形は be動詞で答える。"
  },
  {
    id: "response_097",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) often does your family eat out together?",
    response: "We (      ) out about twice a month.",
    answer: ["How", "eat"],
    completedResponse: "How often does your family eat out together?We eat out about twice a month.",
    translationQuestion: "家族で外食するのはどのくらいの頻度ですか。",
    translationAnswer: "月に2回くらい外食します。",
    point: "eat out（外食する）は重要熟語。"
  },
  {
    id: "response_098",
    category: "助動詞",
    topic: "助動詞（should）",
    question: "Should you ask your teacher if you don't understand today's lesson?",
    response: "Yes, I (      ).",
    answer: ["should"],
    completedResponse: "Yes, I should.",
    translationQuestion: "今日の授業が分からなかったら先生に質問した方がいいですか。",
    translationAnswer: "はい、その方がいいです。",
    point: "Should は「～した方がよい」。"
  },
  {
    id: "response_099",
    category: "三単現",
    topic: "三単現",
    question: "What does your mother usually buy when she goes to the supermarket?",
    response: "She (      ) fresh vegetables.",
    answer: ["buys"],
    completedResponse: "What does your mother usually buy when she goes to the supermarket?She buys fresh vegetables.",
    translationQuestion: "お母さんはスーパーへ行くと普段何を買いますか。",
    translationAnswer: "新鮮な野菜を買います。",
    point: "buy の三単現は buys。"
  },
  {
    id: "response_100",
    category: "現在完了",
    topic: "現在完了",
    question: "Has your class already chosen a leader for the school festival?",
    response: "No, it (      ).",
    answer: ["hasn't"],
    completedResponse: "No, it hasn't.",
    translationQuestion: "クラスはもう学校祭のリーダーを決めましたか。",
    translationAnswer: "いいえ、まだ決まっていません。",
    point: "Has の否定は hasn't。"
  },
  {
    id: "response_101",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your English teacher always speak slowly when explaining new words?",
    response: "She (      ) everyone to understand them.",
    answer: ["Why", "wants"],
    completedResponse: "Why does your English teacher always speak slowly when explaining new words?She wants everyone to understand them.",
    translationQuestion: "英語の先生は新しい単語を説明するとき、なぜいつもゆっくり話すのですか。",
    translationAnswer: "みんなに理解してもらいたいからです。",
    point: "「～したい」が wants のヒントになる。"
  },
  {
    id: "response_102",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your father leave home every weekday morning?",
    response: "He (      ) home at seven.",
    answer: ["When", "leaves"],
    completedResponse: "When does your father leave home every weekday morning?He leaves home at seven.",
    translationQuestion: "お父さんは平日の朝、何時に家を出ますか。",
    translationAnswer: "朝7時に家を出ます。",
    point: "leave の三単現は leaves。"
  },
  {
    id: "response_103",
    category: "be going to",
    topic: "be going to",
    question: "Are you going to join the tennis club next month?",
    response: "Yes, I (      )(      ).",
    answer: ["am", "going"],
    completedResponse: "Yes, I am going to.",
    translationQuestion: "来月テニス部に入る予定ですか。",
    translationAnswer: "はい、その予定です。",
    point: "be going to は「～する予定」。"
  },
  {
    id: "response_104",
    category: "助動詞",
    topic: "助動詞（can）",
    question: "Can your sister play the piano without looking at the music?",
    response: "Yes, she (      ).",
    answer: ["can"],
    completedResponse: "Yes, she can.",
    translationQuestion: "お姉さん（妹）は楽譜を見ないでピアノを弾けますか。",
    translationAnswer: "はい、弾けます。",
    point: "can は能力を表す。"
  },
  {
    id: "response_105",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your mother usually buy flowers?",
    response: "She (      ) them at a flower shop near the station.",
    answer: ["Where", "buys"],
    completedResponse: "Where does your mother usually buy flowers?She buys them at a flower shop near the station.",
    translationQuestion: "お母さんはどこで花を買いますか。",
    translationAnswer: "駅の近くの花屋で買います。",
    point: "buy の三単現は buys。"
  },
  {
    id: "response_106",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Are your classmates cleaning the classroom after school now?",
    response: "Yes, they (      ).",
    answer: ["are"],
    completedResponse: "Yes, they are.",
    translationQuestion: "クラスメートは今、放課後の教室掃除をしていますか。",
    translationAnswer: "はい、しています。",
    point: "現在進行形は be動詞で答える。"
  },
  {
    id: "response_107",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) do you usually carry so many books to school?",
    response: "I (      ) to read during lunch break.",
    answer: ["Why", "like"],
    completedResponse: "Why do you usually carry so many books to school?I like to read during lunch break.",
    translationQuestion: "なぜいつもそんなにたくさん本を学校へ持って行くのですか。",
    translationAnswer: "昼休みに読むのが好きだからです。",
    point: "like to ～ も頻出表現。"
  },
  {
    id: "response_108",
    category: "there is / there are",
    topic: "there is / there are",
    question: "Is there a convenience store near your school?",
    response: "Yes, there (      ).",
    answer: ["is"],
    completedResponse: "Yes, there is.",
    translationQuestion: "学校の近くにコンビニがありますか。",
    translationAnswer: "はい、あります。",
    point: "There is の質問には there is で答える。"
  },
  {
    id: "response_109",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your grandfather usually wake up so early?",
    response: "He (      ) walking every morning.",
    answer: ["Why", "enjoys"],
    completedResponse: "Why does your grandfather usually wake up so early?He enjoys walking every morning.",
    translationQuestion: "おじいさんはなぜいつもそんなに早起きなのですか。",
    translationAnswer: "毎朝散歩を楽しんでいるからです。",
    point: "enjoy の三単現は enjoys。"
  },
  {
    id: "response_110",
    category: "比較",
    topic: "比較",
    question: "Is math more difficult than English for you?",
    response: "No, English (      ).",
    answer: ["is"],
    completedResponse: "No, English is.",
    translationQuestion: "あなたにとって数学は英語より難しいですか。",
    translationAnswer: "いいえ、英語の方が難しいです。",
    point: "比較級も少しずつ慣れていく。"
  },
  {
    id: "response_111",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your English teacher always ask students to read aloud?",
    response: "She (      ) it improves our pronunciation.",
    answer: ["Why", "believes"],
    completedResponse: "Why does your English teacher always ask students to read aloud?She believes it improves our pronunciation.",
    translationQuestion: "英語の先生はなぜいつも音読をさせるのですか。",
    translationAnswer: "発音が良くなると信じているからです。",
    point: "「～と信じている」が believes のヒントになる。"
  },
  {
    id: "response_112",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your mother usually get home from work?",
    response: "She (      ) home around six.",
    answer: ["When", "gets"],
    completedResponse: "When does your mother usually get home from work?She gets home around six.",
    translationQuestion: "お母さんは普段何時に仕事から帰宅しますか。",
    translationAnswer: "6時ごろ帰宅します。",
    point: "get の三単現は gets。"
  },
  {
    id: "response_113",
    category: "現在完了",
    topic: "現在完了",
    question: "Have you ever watched a movie in English without Japanese subtitles?",
    response: "No, I (      ).",
    answer: ["haven't"],
    completedResponse: "No, I haven't.",
    translationQuestion: "日本語字幕なしで英語の映画を見たことがありますか。",
    translationAnswer: "いいえ、ありません。",
    point: "現在完了経験用法の定番。"
  },
  {
    id: "response_114",
    category: "助動詞",
    topic: "助動詞（should）",
    question: "Should we leave earlier to avoid the morning traffic?",
    response: "Yes, we (      ).",
    answer: ["should"],
    completedResponse: "Yes, we should.",
    translationQuestion: "朝の渋滞を避けるために早く出発した方がいいですか。",
    translationAnswer: "はい、その方がいいです。",
    point: "should は「～した方がよい」。"
  },
  {
    id: "response_115",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your sister practice the piano every day?",
    response: "She (      ) in her room.",
    answer: ["Where", "practices"],
    completedResponse: "Where does your sister practice the piano every day?She practices in her room.",
    translationQuestion: "お姉さん（妹）は毎日どこでピアノを練習しますか。",
    translationAnswer: "自分の部屋で練習します。",
    point: "practice の三単現は practices。"
  },
  {
    id: "response_116",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Is your father reading the newspaper in the living room now?",
    response: "Yes, he (      ).",
    answer: ["is"],
    completedResponse: "Yes, he is.",
    translationQuestion: "お父さんは今、リビングで新聞を読んでいますか。",
    translationAnswer: "はい、読んでいます。",
    point: "進行形は be動詞で答える。"
  },
  {
    id: "response_117",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) do you usually study English after dinner?",
    response: "I (      ) for about an hour.",
    answer: ["How", "long", "study"],
    completedResponse: "How long do you usually study English after dinner?I study for about an hour.",
    translationQuestion: "夕食後はどのくらい勉強しますか。",
    translationAnswer: "約1時間勉強します。",
    point: "How long は時間・期間を尋ねる。"
  },
  {
    id: "response_118",
    category: "助動詞",
    topic: "助動詞（can）",
    question: "Can your classmates understand English songs without looking at the lyrics?",
    response: "Some of them (      ).",
    answer: ["can"],
    completedResponse: "Some of them can.",
    translationQuestion: "クラスメートは歌詞を見ないで英語の歌を理解できますか。",
    translationAnswer: "何人かはできます。",
    point: "主語が変わっても can はそのまま。"
  },
  {
    id: "response_119",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your father always wear a suit to work?",
    response: "He (      ) at a bank.",
    answer: ["Why", "works"],
    completedResponse: "Why does your father always wear a suit to work?He works at a bank.",
    translationQuestion: "お父さんはなぜいつもスーツを着て仕事へ行くのですか。",
    translationAnswer: "銀行で働いているからです。",
    point: "work の三単現は works。"
  },
  {
    id: "response_120",
    category: "be going to",
    topic: "be going to",
    question: "Are your classmates going to visit the science museum next week?",
    response: "Yes, they (      )(      ).",
    answer: ["are", "going"],
    completedResponse: "Yes, they are going to.",
    translationQuestion: "クラスメートは来週科学館へ行く予定ですか。",
    translationAnswer: "はい、その予定です。",
    point: "be going to を一まとまりで覚える。"
  },
  {
    id: "response_121",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your English teacher always give us short quizzes at the beginning of class?",
    response: "She (      ) to check our understanding.",
    answer: ["Why", "wants"],
    completedResponse: "Why does your English teacher always give us short quizzes at the beginning of class?She wants to check our understanding.",
    translationQuestion: "英語の先生はなぜ授業の最初にいつも小テストをするのですか。",
    translationAnswer: "私たちの理解度を確認したいからです。",
    point: "「～したい」が wants のヒントになる。"
  },
  {
    id: "response_122",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your brother usually ride his bicycle to school?",
    response: "He (      ) near the school.",
    answer: ["Why", "lives"],
    completedResponse: "Why does your brother usually ride his bicycle to school?He lives near the school.",
    translationQuestion: "あなたのお兄さん（弟）はなぜ普段自転車で学校へ行くのですか。",
    translationAnswer: "学校の近くに住んでいるからです。",
    point: "live の三単現は lives。"
  },
  {
    id: "response_123",
    category: "現在完了",
    topic: "現在完了",
    question: "Have you already decided what club you will join next year?",
    response: "Yes, I (      ).",
    answer: ["have"],
    completedResponse: "Yes, I have.",
    translationQuestion: "来年入る部活動はもう決めましたか。",
    translationAnswer: "はい、決めました。",
    point: "already は現在完了とよく使われる。"
  },
  {
    id: "response_124",
    category: "助動詞",
    topic: "助動詞（will）",
    question: "Will your family travel somewhere during the summer vacation?",
    response: "Yes, we (      ).",
    answer: ["will"],
    completedResponse: "Yes, we will.",
    translationQuestion: "夏休みに家族でどこか旅行しますか。",
    translationAnswer: "はい、行きます。",
    point: "Will の質問は will で答える。"
  },
  {
    id: "response_125",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your grandfather always drink coffee after lunch?",
    response: "He (      ) it helps him stay awake.",
    answer: ["Why", "thinks"],
    completedResponse: "Why does your grandfather always drink coffee after lunch?He thinks it helps him stay awake.",
    translationQuestion: "おじいさんは昼食後にいつもなぜコーヒーを飲むのですか。",
    translationAnswer: "眠気が覚めると思っているからです。",
    point: "think の三単現は thinks。"
  },
  {
    id: "response_126",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Is your sister studying for tomorrow's math test now?",
    response: "No, she (      ).",
    answer: ["isn't"],
    completedResponse: "No, she isn't.",
    translationQuestion: "お姉さん（妹）は今、明日の数学のテスト勉強をしていますか。",
    translationAnswer: "いいえ、していません。",
    point: "現在進行形は be動詞で答える。"
  },
  {
    id: "response_127",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) many books do you usually borrow from the library?",
    response: "I (      ) about three books.",
    answer: ["How", "borrow"],
    completedResponse: "How many books do you usually borrow from the library?I borrow about three books.",
    translationQuestion: "図書館では普段何冊くらい本を借りますか。",
    translationAnswer: "3冊くらい借ります。",
    point: "How many は数量を尋ねる。"
  },
  {
    id: "response_128",
    category: "there is / there are",
    topic: "there is / there are",
    question: "Are there any good restaurants near your school?",
    response: "Yes, there (      ).",
    answer: ["are"],
    completedResponse: "Yes, there are.",
    translationQuestion: "学校の近くにおいしいレストランはありますか。",
    translationAnswer: "はい、あります。",
    point: "There are の質問には there are で答える。"
  },
  {
    id: "response_129",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your English teacher always smile during class?",
    response: "She (      ) teaching English.",
    answer: ["Why", "enjoys"],
    completedResponse: "Why does your English teacher always smile during class?She enjoys teaching English.",
    translationQuestion: "英語の先生はなぜ授業中いつも笑顔なのですか。",
    translationAnswer: "英語を教えることを楽しんでいるからです。",
    point: "enjoy の三単現は enjoys。後ろは -ing。"
  },
  {
    id: "response_130",
    category: "比較",
    topic: "比較",
    question: "Is science easier than math for you?",
    response: "Yes, it (      ).",
    answer: ["is"],
    completedResponse: "Yes, it is.",
    translationQuestion: "あなたにとって理科は数学より簡単ですか。",
    translationAnswer: "はい、そうです。",
    point: "比較級でも答えは be動詞で返す。"
  },
  {
    id: "response_131",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your homeroom teacher always check everyone's homework so carefully?",
    response: "He (      ) every student to improve.",
    answer: ["Why", "wants"],
    completedResponse: "Why does your homeroom teacher always check everyone's homework so carefully?He wants every student to improve.",
    translationQuestion: "担任の先生はなぜみんなの宿題をいつも丁寧に確認するのですか。",
    translationAnswer: "全員に成長してもらいたいからです。",
    point: "「～したい」が wants のヒントになる。"
  },
  {
    id: "response_132",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your father always leave home so early on Mondays?",
    response: "He (      ) an important meeting every Monday morning.",
    answer: ["Why", "has"],
    completedResponse: "Why does your father always leave home so early on Mondays?He has an important meeting every Monday morning.",
    translationQuestion: "お父さんは月曜日になると、なぜいつもそんなに早く家を出るのですか。",
    translationAnswer: "毎週月曜日の朝に大事な会議があるからです。",
    point: "「会議がある」が has のヒントです。"
  },
  {
    id: "response_133",
    category: "be going to",
    topic: "be going to",
    question: "Are you going to practice English after dinner tonight?",
    response: "Yes, I (      )(      ).",
    answer: ["am", "going"],
    completedResponse: "Yes, I am going to.",
    translationQuestion: "今夜は夕食後に英語の勉強をする予定ですか。",
    translationAnswer: "はい、その予定です。",
    point: "be going to は予定・未来を表す。"
  },
  {
    id: "response_134",
    category: "助動詞",
    topic: "助動詞（can）",
    question: "Can your mother drive to the airport by herself?",
    response: "Yes, she (      ).",
    answer: ["can"],
    completedResponse: "Yes, she can.",
    translationQuestion: "お母さんは一人で空港まで運転して行けますか。",
    translationAnswer: "はい、行けます。",
    point: "can は能力・可能。"
  },
  {
    id: "response_135",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your English teacher usually begin every class?",
    response: "She (      ) with a short quiz.",
    answer: ["How", "begins"],
    completedResponse: "How does your English teacher usually begin every class?She begins with a short quiz.",
    translationQuestion: "英語の先生は授業をいつもどのように始めますか。",
    translationAnswer: "最初に小テストから始めます。",
    point: "「始めます」が begins のヒントです。"
  },
  {
    id: "response_136",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Is your brother using the computer for his homework now?",
    response: "No, he (      ).",
    answer: ["isn't"],
    completedResponse: "No, he isn't.",
    translationQuestion: "お兄さん（弟）は今、宿題のためにパソコンを使っていますか。",
    translationAnswer: "いいえ、使っていません。",
    point: "現在進行形は be動詞で答える。"
  },
  {
    id: "response_137",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) do you usually spend your summer vacation?",
    response: "I (      ) a lot of books and play baseball.",
    answer: ["How", "read"],
    completedResponse: "How do you usually spend your summer vacation?I read a lot of books and play baseball.",
    translationQuestion: "夏休みは普段どのように過ごしますか。",
    translationAnswer: "たくさん本を読んで、野球をします。",
    point: "「本を読む」が read のヒントです。"
  },
  {
    id: "response_138",
    category: "助動詞",
    topic: "助動詞（should）",
    question: "Should we review today's lesson before tomorrow's class?",
    response: "Yes, we (      ).",
    answer: ["should"],
    completedResponse: "Yes, we should.",
    translationQuestion: "明日の授業の前に今日の内容を復習した方がいいですか。",
    translationAnswer: "はい、その方がいいです。",
    point: "review（復習する）は頻出単語。"
  },
  {
    id: "response_139",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your grandmother make such delicious bread?",
    response: "She (      ) it every weekend.",
    answer: ["Why", "makes"],
    completedResponse: "Why does your grandmother make such delicious bread?She makes it every weekend.",
    translationQuestion: "おばあさんはどうしてそんなにおいしいパンを作れるのですか。",
    translationAnswer: "毎週末それを作るからです。",
    point: "「作る」が makes のヒントです。"
  },
  {
    id: "response_140",
    category: "現在完了",
    topic: "現在完了",
    question: "Have you ever visited a foreign country with your family?",
    response: "Yes, I (      ).",
    answer: ["have"],
    completedResponse: "Yes, I have.",
    translationQuestion: "家族と外国へ行ったことがありますか。",
    translationAnswer: "はい、あります。",
    point: "現在完了（経験）の定番表現。"
  },
  {
    id: "response_141",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your science teacher always prepare interesting experiments?",
    response: "He (      ) students to enjoy science.",
    answer: ["Why", "wants"],
    completedResponse: "Why does your science teacher always prepare interesting experiments?He wants students to enjoy science.",
    translationQuestion: "理科の先生はなぜいつも面白い実験を準備するのですか。",
    translationAnswer: "生徒に理科を好きになってほしいからです。",
    point: "「してほしい」が wants のヒントです。"
  },
  {
    id: "response_142",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your mother always bring her own shopping bag?",
    response: "She (      ) to reduce plastic waste.",
    answer: ["Why", "wants"],
    completedResponse: "Why does your mother always bring her own shopping bag?She wants to reduce plastic waste.",
    translationQuestion: "お母さんはなぜいつも自分の買い物袋を持って行くのですか。",
    translationAnswer: "プラスチックごみを減らしたいからです。",
    point: "「したい」が wants のヒントです。"
  },
  {
    id: "response_143",
    category: "現在完了",
    topic: "現在完了",
    question: "Has your brother finished his summer homework yet?",
    response: "No, he (      ).",
    answer: ["hasn't"],
    completedResponse: "No, he hasn't.",
    translationQuestion: "お兄さん（弟）はもう夏休みの宿題を終えましたか。",
    translationAnswer: "いいえ、まだ終わっていません。",
    point: "yet は疑問文・否定文でよく使う。"
  },
  {
    id: "response_144",
    category: "助動詞",
    topic: "助動詞（will）",
    question: "Will your class have a vocabulary quiz tomorrow?",
    response: "Yes, we (      ).",
    answer: ["will"],
    completedResponse: "Yes, we will.",
    translationQuestion: "あなたのクラスは明日単語テストがありますか。",
    translationAnswer: "はい、あります。",
    point: "have a quiz は覚えておきたい表現。"
  },
  {
    id: "response_145",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your father usually have lunch?",
    response: "He (      ) lunch at a small restaurant near his office.",
    answer: ["Where", "has"],
    completedResponse: "Where does your father usually have lunch?He has lunch at a small restaurant near his office.",
    translationQuestion: "お父さんは普段どこで昼食を食べますか。",
    translationAnswer: "会社の近くの小さなレストランで昼食を食べます。",
    point: "「昼食を食べる」が has のヒントです。"
  },
  {
    id: "response_146",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Are your parents watching the news on TV now?",
    response: "Yes, they (      ).",
    answer: ["are"],
    completedResponse: "Yes, they are.",
    translationQuestion: "ご両親は今テレビでニュースを見ていますか。",
    translationAnswer: "はい、見ています。",
    point: "現在進行形は be動詞で答える。"
  },
  {
    id: "response_147",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) do you usually practice speaking English?",
    response: "I (      ) at home.",
    answer: ["Where", "practice"],
    completedResponse: "Where do you usually practice speaking English?I practice at home.",
    translationQuestion: "普段どこで英語を話す練習をしていますか。",
    translationAnswer: "家で練習します。",
    point: "「練習する」が practice のヒントです。"
  },
  {
    id: "response_148",
    category: "助動詞",
    topic: "助動詞（can）",
    question: "Can your grandfather use a smartphone without any help?",
    response: "Yes, he (      ).",
    answer: ["can"],
    completedResponse: "Yes, he can.",
    translationQuestion: "おじいさんは一人でスマートフォンを使えますか。",
    translationAnswer: "はい、使えます。",
    point: "without any help（助けなしで）も覚えよう。"
  },
  {
    id: "response_149",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your English teacher remember all the students' names?",
    response: "She (      ) everyone carefully.",
    answer: ["Why", "teaches"],
    completedResponse: "How does your English teacher remember all the students' names?She teaches everyone carefully.",
    translationQuestion: "英語の先生はなぜ全員の名前を覚えているのですか。",
    translationAnswer: "一人ひとりを丁寧に教えるからです。",
    point: "「教える」が teaches のヒントです。"
  },
  {
    id: "response_150",
    category: "比較",
    topic: "比較",
    question: "Is English more interesting than math for you?",
    response: "Yes, it (      ).",
    answer: ["is"],
    completedResponse: "Yes, it is.",
    translationQuestion: "あなたにとって英語は数学より面白いですか。",
    translationAnswer: "はい、そうです。",
    point: "interesting の比較級は more interesting。"
  },
  {
    id: "response_151",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your homeroom teacher always encourage everyone to ask questions?",
    response: "He (      ) students learn better that way.",
    answer: ["Why", "believes"],
    completedResponse: "Why does your homeroom teacher always encourage everyone to ask questions?He believes students learn better that way.",
    translationQuestion: "担任の先生はなぜみんなに質問するよう勧めるのですか。",
    translationAnswer: "その方が生徒はよく学べると信じているからです。",
    point: "「信じている」が believes のヒントです。"
  },
  {
    id: "response_152",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your father always check the weather before leaving home?",
    response: "He (      ) to know if he needs an umbrella.",
    answer: ["Why", "wants"],
    completedResponse: "Why does your father always check the weather before leaving home?He wants to know if he needs an umbrella.",
    translationQuestion: "お父さんはなぜ家を出る前にいつも天気を確認するのですか。",
    translationAnswer: "傘が必要か知りたいからです。",
    point: "「知りたい」が wants のヒントです。"
  },
  {
    id: "response_153",
    category: "現在完了",
    topic: "現在完了",
    question: "Have you ever tried cooking dinner by yourself?",
    response: "Yes, I (      ).",
    answer: ["have"],
    completedResponse: "Yes, I have.",
    translationQuestion: "自分一人で夕食を作ったことがありますか。",
    translationAnswer: "はい、あります。",
    point: "try ～ing も覚えておこう。"
  },
  {
    id: "response_154",
    category: "助動詞",
    topic: "助動詞（should）",
    question: "Should we bring some water for tomorrow's hiking trip?",
    response: "Yes, we (      ).",
    answer: ["should"],
    completedResponse: "Yes, we should.",
    translationQuestion: "明日のハイキングには水を持って行った方がいいですか。",
    translationAnswer: "はい、その方がいいです。",
    point: "bring は英検3級頻出動詞。"
  },
  {
    id: "response_155",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your sister usually study after she gets home?",
    response: "She (      ) math first.",
    answer: ["What", "studies"],
    completedResponse: "What does your sister usually study after she gets home?She studies math first.",
    translationQuestion: "お姉さん（妹）は家に帰ると、まず何を勉強しますか。",
    translationAnswer: "最初に数学を勉強します。",
    point: "「勉強する」が studies のヒントです。"
  },
  {
    id: "response_156",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Is your teacher explaining today's grammar now?",
    response: "Yes, she (      ).",
    answer: ["is"],
    completedResponse: "Yes, she is.",
    translationQuestion: "先生は今、今日の文法を説明していますか。",
    translationAnswer: "はい、説明しています。",
    point: "explain は重要動詞。"
  },
  {
    id: "response_157",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) do you usually meet your friends after school?",
    response: "We (      ) at the school gate.",
    answer: ["Where", "meet"],
    completedResponse: "Where do you usually meet your friends after school?We meet at the school gate.",
    translationQuestion: "放課後はどこで友達と会いますか。",
    translationAnswer: "学校の門で会います。",
    point: "「会う」が meet のヒントです。"
  },
  {
    id: "response_158",
    category: "助動詞",
    topic: "助動詞（must）",
    question: "Must students wear indoor shoes in your school?",
    response: "Yes, they (      ).",
    answer: ["must"],
    completedResponse: "Yes, they must.",
    translationQuestion: "あなたの学校では上履きを履かなければなりませんか。",
    translationAnswer: "はい、履かなければなりません。",
    point: "学校生活でよく使う must。"
  },
  {
    id: "response_159",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your grandfather usually read every morning?",
    response: "He (      ) the newspaper.",
    answer: ["What", "reads"],
    completedResponse: "What does your grandfather usually read every morning?He reads the newspaper.",
    translationQuestion: "おじいさんは毎朝何を読みますか。",
    translationAnswer: "新聞を読みます。",
    point: "「読む」が reads のヒントです。"
  },
  {
    id: "response_160",
    category: "be going to",
    topic: "be going to",
    question: "Are your classmates going to clean the classroom after school?",
    response: "Yes, they (      )(      ).",
    answer: ["are", "going"],
    completedResponse: "Yes, they are going to.",
    translationQuestion: "クラスメートは放課後に教室を掃除する予定ですか。",
    translationAnswer: "はい、その予定です。",
    point: "be going to は未来の予定。"
  },
  {
    id: "response_161",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your English teacher always ask everyone to speak loudly?",
    response: "She (      ) everyone to speak with confidence.",
    answer: ["Why", "wants"],
    completedResponse: "Why does your English teacher always ask everyone to speak loudly?She wants everyone to speak with confidence.",
    translationQuestion: "英語の先生はなぜいつもみんなに大きな声で話すよう言うのですか。",
    translationAnswer: "みんなに自信を持って話してほしいからです。",
    point: "「話してほしい」が wants のヒントです。"
  },
  {
    id: "response_162",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your father usually drive to work instead of taking the train?",
    response: "He (      ) many customers during the day.",
    answer: ["Why", "visits"],
    completedResponse: "Why does your father usually drive to work instead of taking the train?He visits many customers during the day.",
    translationQuestion: "お父さんはなぜ普段電車ではなく車で通勤するのですか。",
    translationAnswer: "日中にたくさんのお客様を訪問するからです。",
    point: "「訪問する」が visits のヒントです。"
  },
  {
    id: "response_163",
    category: "現在完了",
    topic: "現在完了",
    question: "Have you ever written a letter in English?",
    response: "No, I (      ).",
    answer: ["haven't"],
    completedResponse: "No, I haven't.",
    translationQuestion: "英語で手紙を書いたことがありますか。",
    translationAnswer: "いいえ、ありません。",
    point: "write－wrote－written も一緒に覚えよう。"
  },
  {
    id: "response_164",
    category: "助動詞",
    topic: "助動詞（will）",
    question: "Will your parents come to your school festival this year?",
    response: "Yes, they (      ).",
    answer: ["will"],
    completedResponse: "Yes, they will.",
    translationQuestion: "今年、ご両親は学校祭に来ますか。",
    translationAnswer: "はい、来ます。",
    point: "come to ～ は頻出表現。"
  },
  {
    id: "response_165",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your mother usually buy fresh vegetables?",
    response: "She (      ) them at the local market.",
    answer: ["Where", "buys"],
    completedResponse: "Where does your mother usually buy fresh vegetables?She buys them at the local market.",
    translationQuestion: "お母さんは普段どこで新鮮な野菜を買いますか。",
    translationAnswer: "近所の市場で買います。",
    point: "「買う」が buys のヒントです。"
  },
  {
    id: "response_166",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Are your classmates preparing for the speech contest now?",
    response: "Yes, they (      ).",
    answer: ["are"],
    completedResponse: "Yes, they are.",
    translationQuestion: "クラスメートは今、スピーチコンテストの準備をしていますか。",
    translationAnswer: "はい、しています。",
    point: "prepare for ～ は重要表現。"
  },
  {
    id: "response_167",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) do you usually go to bed on school nights?",
    response: "I (      ) to bed at ten.",
    answer: ["When", "go"],
    completedResponse: "When do you usually go to bed on school nights?I go to bed at ten.",
    translationQuestion: "学校がある日は普段何時に寝ますか。",
    translationAnswer: "10時に寝ます。",
    point: "「寝る」が go のヒントです。"
  },
  {
    id: "response_168",
    category: "助動詞",
    topic: "助動詞（can）",
    question: "Can your sister swim across the pool?",
    response: "Yes, she (      ).",
    answer: ["can"],
    completedResponse: "Yes, she can.",
    translationQuestion: "お姉さん（妹）はプールを泳いで渡れますか。",
    translationAnswer: "はい、泳げます。",
    point: "across（～を横切って）はよく出る前置詞。"
  },
  {
    id: "response_169",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your English teacher always review yesterday's lesson first?",
    response: "She (      ) students remember it better.",
    answer: ["Why", "helps"],
    completedResponse: "Why does your English teacher always review yesterday's lesson first?She helps students remember it better.",
    translationQuestion: "英語の先生はなぜいつも昨日の授業を最初に復習するのですか。",
    translationAnswer: "生徒がよりよく覚えられるようにするためです。",
    point: "「できるようにする」が helps のヒントです。"
  },
  {
    id: "response_170",
    category: "there is / there are",
    topic: "there is / there are",
    question: "Are there any empty seats on the bus?",
    response: "No, there (      ).",
    answer: ["aren't"],
    completedResponse: "No, there aren't.",
    translationQuestion: "バスに空いている席はありますか。",
    translationAnswer: "いいえ、ありません。",
    point: "There are の否定は there aren't。"
  },
  {
    id: "response_171",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your science teacher always ask students to write down their observations?",
    response: "He (      ) careful observation is important.",
    answer: ["Why", "believes"],
    completedResponse: "Why does your science teacher always ask students to write down their observations?He believes careful observation is important.",
    translationQuestion: "理科の先生はなぜいつも観察したことを書き留めるように言うのですか。",
    translationAnswer: "注意深い観察が大切だと信じているからです。",
    point: "「信じている」が believes のヒントです。"
  },
  {
    id: "response_172",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your mother usually water the flowers?",
    response: "She (      ) them every morning.",
    answer: ["When", "waters"],
    completedResponse: "When does your mother usually water the flowers?She waters them every morning.",
    translationQuestion: "お母さんは普段いつ花に水をあげますか。",
    translationAnswer: "毎朝水をあげます。",
    point: "「水をあげる」が waters のヒントです。"
  },
  {
    id: "response_173",
    category: "現在完了",
    topic: "現在完了",
    question: "Have you ever lost your school ID card?",
    response: "No, I (      ).",
    answer: ["haven't"],
    completedResponse: "No, I haven't.",
    translationQuestion: "学校の身分証をなくしたことがありますか。",
    translationAnswer: "いいえ、ありません。",
    point: "lose－lost－lost も一緒に覚えよう。"
  },
  {
    id: "response_174",
    category: "助動詞",
    topic: "助動詞（should）",
    question: "Should you ask your parents before buying something expensive?",
    response: "Yes, I (      ).",
    answer: ["should"],
    completedResponse: "Yes, I should.",
    translationQuestion: "高い物を買う前に両親へ相談した方がいいですか。",
    translationAnswer: "はい、その方がいいです。",
    point: "ask A before ～ の形も覚える。"
  },
  {
    id: "response_175",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your brother usually finish his homework?",
    response: "He (      ) it before dinner.",
    answer: ["When", "finishes"],
    completedResponse: "When does your brother usually finish his homework?He finishes it before dinner.",
    translationQuestion: "お兄さん（弟）は普段何時に宿題を終えますか。",
    translationAnswer: "夕食前に終わらせます。",
    point: "「終わらせる」が finishes のヒントです。"
  },
  {
    id: "response_176",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Is your father fixing his bicycle now?",
    response: "No, he (      ).",
    answer: ["isn't"],
    completedResponse: "No, he isn't.",
    translationQuestion: "お父さんは今、自転車を修理していますか。",
    translationAnswer: "いいえ、していません。",
    point: "現在進行形は be動詞（is / am / are）で答える"
  },
  {
    id: "response_177",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) do you usually study with after school?",
    response: "I (      ) with my best friend.",
    answer: ["Who", "study"],
    completedResponse: "Who do you usually study with after school?I study with my best friend.",
    translationQuestion: "放課後は普段誰と勉強しますか。",
    translationAnswer: "親友と勉強します。",
    point: "「勉強する」が study のヒントです。"
  },
  {
    id: "response_178",
    category: "助動詞",
    topic: "助動詞（must）",
    question: "Must everyone hand in the report by Friday?",
    response: "Yes, they (      ).",
    answer: ["must"],
    completedResponse: "Yes, they must.",
    translationQuestion: "全員金曜日までにレポートを提出しなければなりませんか。",
    translationAnswer: "はい、提出しなければなりません。",
    point: "hand in（提出する）は重要熟語。"
  },
  {
    id: "response_179",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your grandfather usually take a walk?",
    response: "He (      ) in the nearby park.",
    answer: ["Where", "walks"],
    completedResponse: "Where does your grandfather usually take a walk?He walks in the nearby park.",
    translationQuestion: "おじいさんは普段どこを散歩しますか。",
    translationAnswer: "近くの公園を散歩します。",
    point: "「散歩する」が walks のヒントです。"
  },
  {
    id: "response_180",
    category: "be going to",
    topic: "be going to",
    question: "Are you going to visit your grandparents this weekend?",
    response: "Yes, I (      )(      ).",
    answer: ["am", "going"],
    completedResponse: "Yes, I am going to.",
    translationQuestion: "今週末、おじいさん・おばあさんの家へ行く予定ですか。",
    translationAnswer: "はい、その予定です。",
    point: "週末の予定を表す定番表現。"
  },
  {
    id: "response_181",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your English teacher always encourage students to read English books?",
    response: "She (      ) reading improves our vocabulary.",
    answer: ["Why", "believes"],
    completedResponse: "Why does your English teacher always encourage students to read English books?She believes reading improves our vocabulary.",
    translationQuestion: "英語の先生はなぜいつも英語の本を読むよう勧めるのですか。",
    translationAnswer: "読書は語彙力を伸ばすと信じているからです。",
    point: "「信じている」が believes のヒントです。"
  },
  {
    id: "response_182",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your father usually arrive at his office?",
    response: "He (      ) there at eight thirty.",
    answer: ["When", "arrives"],
    completedResponse: "When does your father usually arrive at his office?He arrives there at eight thirty.",
    translationQuestion: "お父さんは普段何時に会社へ着きますか。",
    translationAnswer: "8時30分に会社に到着します。",
    point: "「到着する」が arrives のヒントです。"
  },
  {
    id: "response_183",
    category: "現在完了",
    topic: "現在完了",
    question: "Have you ever forgotten your homework at home?",
    response: "Yes, I (      ).",
    answer: ["have"],
    completedResponse: "Yes, I have.",
    translationQuestion: "宿題を家に忘れたことがありますか。",
    translationAnswer: "はい、あります。",
    point: "forget－forgot－forgotten も一緒に覚えよう。"
  },
  {
    id: "response_184",
    category: "助動詞",
    topic: "助動詞（can）",
    question: "Can your teacher answer every student's question?",
    response: "Yes, she (      ).",
    answer: ["can"],
    completedResponse: "Yes, she can.",
    translationQuestion: "先生は生徒全員の質問に答えられますか。",
    translationAnswer: "はい、答えられます。",
    point: "answer は他動詞なので answer a question。"
  },
  {
    id: "response_185",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your sister usually spend her allowance on?",
    response: "She (      ) books and stationery.",
    answer: ["What", "buys"],
    completedResponse: "What does your sister usually spend her allowance on?She buys books and stationery.",
    translationQuestion: "お姉さん（妹）はお小遣いを何に使いますか。",
    translationAnswer: "本や文房具を買います。",
    point: "「買う」が buys のヒントです。"
  },
  {
    id: "response_186",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Is your mother making dinner in the kitchen now?",
    response: "Yes, she (      ).",
    answer: ["is"],
    completedResponse: "Yes, she is.",
    translationQuestion: "お母さんは今、台所で夕食を作っていますか。",
    translationAnswer: "はい、作っています。",
    point: "make dinner は基本表現。"
  },
  {
    id: "response_187",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) do you usually do when you have free time?",
    response: "I (      ) books or listen to music.",
    answer: ["What", "read"],
    completedResponse: "What do you usually do when you have free time?I read books or listen to music.",
    translationQuestion: "時間があるときは普段何をしますか。",
    translationAnswer: "本を読んだり、音楽を聞いたりします。",
    point: "「本を読む」が read のヒントです。"
  },
  {
    id: "response_188",
    category: "助動詞",
    topic: "助動詞（should）",
    question: "Should students be kind to new classmates?",
    response: "Yes, they (      ).",
    answer: ["should"],
    completedResponse: "Yes, they should.",
    translationQuestion: "新しく来たクラスメートには親切にした方がいいですか。",
    translationAnswer: "はい、その方がいいです。",
    point: "be kind to ～ は重要表現。"
  },
  {
    id: "response_189",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your grandfather usually watch on TV every evening?",
    response: "He (      ) the news.",
    answer: ["What", "watches"],
    completedResponse: "What does your grandfather usually watch on TV every evening?He watches the news.",
    translationQuestion: "おじいさんは毎晩テレビで何を見ますか。",
    translationAnswer: "ニュースを見ます。",
    point: "「見る」が watches のヒントです。"
  },
  {
    id: "response_190",
    category: "比較",
    topic: "比較",
    question: "Is your English homework more difficult than your math homework?",
    response: "No, it (      ).",
    answer: ["isn't"],
    completedResponse: "No, it isn't.",
    translationQuestion: "英語の宿題は数学の宿題より難しいですか。",
    translationAnswer: "いいえ、違います。",
    point: "比較級でも答えは be動詞で返す。"
  },
  {
    id: "response_191",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your English teacher always ask students to use complete sentences?",
    response: "She (      ) it helps us communicate more clearly.",
    answer: ["Why", "believes"],
    completedResponse: "Why does your English teacher always ask students to use complete sentences?She believes it helps us communicate more clearly.",
    translationQuestion: "英語の先生はなぜいつも完全な文で答えるように言うのですか。",
    translationAnswer: "その方がより分かりやすく伝えられると信じているからです。",
    point: "「信じている」が believes のヒントです。"
  },
  {
    id: "response_192",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your father usually keep his important documents?",
    response: "He (      ) them in a locked drawer.",
    answer: ["Where", "keeps"],
    completedResponse: "Where does your father usually keep his important documents?He keeps them in a locked drawer.",
    translationQuestion: "お父さんは大切な書類を普段どこに保管していますか。",
    translationAnswer: "鍵のかかる引き出しに保管しています。",
    point: "「保管している」が keeps のヒントです。"
  },
  {
    id: "response_193",
    category: "現在完了",
    topic: "現在完了",
    question: "Have you ever taken part in a speech contest?",
    response: "No, I (      ).",
    answer: ["haven't"],
    completedResponse: "No, I haven't.",
    translationQuestion: "スピーチコンテストに参加したことがありますか。",
    translationAnswer: "いいえ、ありません。",
    point: "take part in（参加する）は重要熟語。"
  },
  {
    id: "response_194",
    category: "助動詞",
    topic: "助動詞（will）",
    question: "Will your class visit a museum during the school trip?",
    response: "Yes, we (      ).",
    answer: ["will"],
    completedResponse: "Yes, we will.",
    translationQuestion: "修学旅行で博物館へ行きますか。",
    translationAnswer: "はい、行きます。",
    point: "visit は「訪れる」。go to と合わせて覚えよう。"
  },
  {
    id: "response_195",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your mother usually make for breakfast?",
    response: "She (      ) toast and eggs.",
    answer: ["What", "makes"],
    completedResponse: "What does your mother usually make for breakfast?She makes toast and eggs.",
    translationQuestion: "お母さんは朝食に普段何を作りますか。",
    translationAnswer: "トーストと卵料理を作ります。",
    point: "「作る」が makes のヒントです。"
  },
  {
    id: "response_196",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Are your classmates practicing for the chorus competition now?",
    response: "No, they (      ).",
    answer: ["aren't"],
    completedResponse: "No, they aren't.",
    translationQuestion: "クラスメートは今、合唱コンクールの練習をしていますか。",
    translationAnswer: "いいえ、していません。",
    point: "practice for ～ はよく使う表現。"
  },
  {
    id: "response_197",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) do you usually help your parents at home?",
    response: "I (      ) the dishes after dinner.",
    answer: ["How", "wash"],
    completedResponse: "How do you usually help your parents at home?I wash the dishes after dinner.",
    translationQuestion: "家ではどのように両親を手伝っていますか。",
    translationAnswer: "夕食後にお皿を洗います。",
    point: "「お皿を洗う」が wash のヒントです。"
  },
  {
    id: "response_198",
    category: "助動詞",
    topic: "助動詞（must）",
    question: "Must you finish this project by next Monday?",
    response: "Yes, I (      ).",
    answer: ["must"],
    completedResponse: "Yes, I must.",
    translationQuestion: "この課題は来週月曜日までに終えなければなりませんか。",
    translationAnswer: "はい、終えなければなりません。",
    point: "finish a project は学校でもよく使う表現。"
  },
  {
    id: "response_199",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your grandfather usually feed the birds?",
    response: "He (      ) them every morning.",
    answer: ["When", "feeds"],
    completedResponse: "When does your grandfather usually feed the birds?He feeds them every morning.",
    translationQuestion: "おじいさんは普段いつ鳥にえさをあげますか。",
    translationAnswer: "毎朝えさをあげます。",
    point: "「えさをあげる」が feeds のヒントです。"
  },
  {
    id: "response_200",
    category: "be going to",
    topic: "be going to",
    question: "Are you going to study abroad someday?",
    response: "Yes, I (      )(      ).",
    answer: ["am", "going"],
    completedResponse: "Yes, I am going to.",
    translationQuestion: "いつか留学する予定ですか。",
    translationAnswer: "はい、その予定です。",
    point: "study abroad は重要熟語。"
  },
  {
    id: "response_201",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your English teacher always ask students to read books outside class?",
    response: "She (      ) it helps us learn new words naturally.",
    answer: ["Why", "believes"],
    completedResponse: "Why does your English teacher always ask students to read books outside class?She believes it helps us learn new words naturally.",
    translationQuestion: "英語の先生はなぜ授業以外でも本を読むよう勧めるのですか。",
    translationAnswer: "自然に新しい単語を覚えられると信じているからです。",
    point: "「信じている」が believes のヒントです。"
  },
  {
    id: "response_202",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your father usually take a vacation?",
    response: "He (      ) a vacation in August.",
    answer: ["When", "takes"],
    completedResponse: "When does your father usually take a vacation?He takes a vacation in August.",
    translationQuestion: "お父さんは普段いつ休暇を取りますか。",
    translationAnswer: "8月に休暇を取ります。",
    point: "「休暇を取る」が takes のヒントです。"
  },
  {
    id: "response_203",
    category: "現在完了",
    topic: "現在完了",
    question: "Have you ever met a famous athlete?",
    response: "No, I (      ).",
    answer: ["haven't"],
    completedResponse: "No, I haven't.",
    translationQuestion: "有名なスポーツ選手に会ったことがありますか。",
    translationAnswer: "いいえ、ありません。",
    point: "meet－met－met も一緒に覚えよう。"
  },
  {
    id: "response_204",
    category: "助動詞",
    topic: "助動詞（can）",
    question: "Can your sister cook dinner by herself?",
    response: "Yes, she (      ).",
    answer: ["can"],
    completedResponse: "Yes, she can.",
    translationQuestion: "お姉さん（妹）は一人で夕食を作れますか。",
    translationAnswer: "はい、作れます。",
    point: "by oneself（自分一人で）も覚えよう。"
  },
  {
    id: "response_205",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your mother usually clean first on weekends?",
    response: "She (      ) the living room.",
    answer: ["What", "cleans"],
    completedResponse: "What does your mother usually clean first on weekends?She cleans the living room.",
    translationQuestion: "お母さんは週末、最初にどこを掃除しますか。",
    translationAnswer: "最初にリビングを掃除します。",
    point: "「掃除する」が cleans のヒントです。"
  },
  {
    id: "response_206",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Is your brother practicing the guitar now?",
    response: "Yes, he (      ).",
    answer: ["is"],
    completedResponse: "Yes, he is.",
    translationQuestion: "お兄さん（弟）は今ギターを練習していますか。",
    translationAnswer: "はい、練習しています。",
    point: "practice the guitar は自然な表現。"
  },
  {
    id: "response_207",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) do you usually spend your Sunday mornings?",
    response: "I (      ) baseball with my friends.",
    answer: ["How", "play"],
    completedResponse: "How do you usually spend your Sunday mornings?I play baseball with my friends.",
    translationQuestion: "日曜日の午前中は普段どのように過ごしますか。",
    translationAnswer: "友達と野球をします。",
    point: "「野球をする」が play のヒントです。"
  },
  {
    id: "response_208",
    category: "助動詞",
    topic: "助動詞（should）",
    question: "Should we review today's vocabulary before going to bed?",
    response: "Yes, we (      ).",
    answer: ["should"],
    completedResponse: "Yes, we should.",
    translationQuestion: "寝る前に今日の単語を復習した方がいいですか。",
    translationAnswer: "はい、その方がいいです。",
    point: "review vocabulary は定番表現。"
  },
  {
    id: "response_209",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your grandfather usually grow in his garden?",
    response: "He (      ) tomatoes and cucumbers.",
    answer: ["What", "grows"],
    completedResponse: "What does your grandfather usually grow in his garden?He grows tomatoes and cucumbers.",
    translationQuestion: "おじいさんは庭で普段何を育てていますか。",
    translationAnswer: "トマトときゅうりを育てています。",
    point: "「育てる」が grows のヒントです。"
  },
  {
    id: "response_210",
    category: "比較",
    topic: "比較",
    question: "Is English easier than science for you?",
    response: "Yes, it (      ).",
    answer: ["is"],
    completedResponse: "Yes, it is.",
    translationQuestion: "あなたにとって英語は理科より簡単ですか。",
    translationAnswer: "はい、そうです。",
    point: "比較級でも be 動詞で答える。"
  },
  {
    id: "response_211",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your English teacher always encourage students to speak English in class?",
    response: "She (      ) speaking English builds confidence.",
    answer: ["Why", "believes"],
    completedResponse: "Why does your English teacher always encourage students to speak English in class?She believes speaking English builds confidence.",
    translationQuestion: "英語の先生はなぜ授業中に英語で話すよう勧めるのですか。",
    translationAnswer: "英語で話すことが自信につながると信じているからです。",
    point: "「信じている」が believes のヒントです。"
  },
  {
    id: "response_212",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your father usually park his car?",
    response: "He (      ) it behind his office.",
    answer: ["Where", "parks"],
    completedResponse: "Where does your father usually park his car?He parks it behind his office.",
    translationQuestion: "お父さんは普段どこに車を止めますか。",
    translationAnswer: "会社の裏に止めます。",
    point: "「止める」が parks のヒントです。"
  },
  {
    id: "response_213",
    category: "現在完了",
    topic: "現在完了",
    question: "Have you ever made lunch by yourself?",
    response: "Yes, I (      ).",
    answer: ["have"],
    completedResponse: "Yes, I have.",
    translationQuestion: "自分で昼食を作ったことがありますか。",
    translationAnswer: "はい、あります。",
    point: "make lunch は日常会話でよく使う。"
  },
  {
    id: "response_214",
    category: "助動詞",
    topic: "助動詞（will）",
    question: "Will your class have a soccer game next week?",
    response: "Yes, we (      ).",
    answer: ["will"],
    completedResponse: "Yes, we will.",
    translationQuestion: "来週、クラスでサッカーの試合がありますか。",
    translationAnswer: "はい、あります。",
    point: "will は未来の予定にも使える。"
  },
  {
    id: "response_215",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your sister usually listen to music?",
    response: "She (      ) to music before going to bed.",
    answer: ["When", "listens"],
    completedResponse: "When does your sister usually listen to music?She listens to music before going to bed.",
    translationQuestion: "お姉さん（妹）はいつ音楽を聞きますか。",
    translationAnswer: "寝る前に聞きます。",
    point: "「聞く」が listens のヒントです。"
  },
  {
    id: "response_216",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Is your teacher talking with another student now?",
    response: "Yes, she (      ).",
    answer: ["is"],
    completedResponse: "Yes, she is.",
    translationQuestion: "先生は今、別の生徒と話していますか。",
    translationAnswer: "はい、話しています。",
    point: "talk with ～ はよく使う表現。"
  },
  {
    id: "response_217",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) do you usually use your computer?",
    response: "I (      ) it to study English.",
    answer: ["Why", "use"],
    completedResponse: "Why do you usually use your computer?I use it to study English.",
    translationQuestion: "普段何のためにパソコンを使いますか。",
    translationAnswer: "英語を勉強するために使います。",
    point: "「使う」が use のヒントです。"
  },
  {
    id: "response_218",
    category: "助動詞",
    topic: "助動詞（must）",
    question: "Must you wear your student ID at school?",
    response: "Yes, I (      ).",
    answer: ["must"],
    completedResponse: "Yes, I must.",
    translationQuestion: "学校では学生証を身につけなければなりませんか。",
    translationAnswer: "はい、身につけなければなりません。",
    point: "wear は「着る」だけでなく「身につける」。"
  },
  {
    id: "response_219",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your grandfather usually read before breakfast?",
    response: "He (      ) the newspaper.",
    answer: ["What", "reads"],
    completedResponse: "What does your grandfather usually read before breakfast?He reads the newspaper.",
    translationQuestion: "おじいさんは朝食前に普段何を読みますか。",
    translationAnswer: "新聞を読みます。",
    point: "「読む」が reads のヒントです。"
  },
  {
    id: "response_220",
    category: "there is / there are",
    topic: "there is / there are",
    question: "Is there a bookstore near your station?",
    response: "Yes, there (      ).",
    answer: ["is"],
    completedResponse: "Yes, there is.",
    translationQuestion: "駅の近くに本屋がありますか。",
    translationAnswer: "はい、あります。",
    point: "There is の応答を覚えよう。"
  },
  {
    id: "response_221",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your English teacher always ask students to read aloud?",
    response: "She (      ) it improves our pronunciation.",
    answer: ["Why", "believes"],
    completedResponse: "Why does your English teacher always ask students to read aloud?She believes it improves our pronunciation.",
    translationQuestion: "英語の先生はなぜいつも音読をさせるのですか。",
    translationAnswer: "音読で発音が良くなると信じているからです。",
    point: "「信じている」が believes のヒントです。"
  },
  {
    id: "response_222",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your father usually buy coffee on his way to work?",
    response: "He (      ) it at a convenience store.",
    answer: ["Where", "buys"],
    completedResponse: "Where does your father usually buy coffee on his way to work?He buys it at a convenience store.",
    translationQuestion: "お父さんは通勤途中のどこでコーヒーを買いますか。",
    translationAnswer: "コンビニで買います。",
    point: "「買う」が buys のヒントです。"
  },
  {
    id: "response_223",
    category: "現在完了",
    topic: "現在完了",
    question: "Have you ever won a prize at school?",
    response: "No, I (      ).",
    answer: ["haven't"],
    completedResponse: "No, I haven't.",
    translationQuestion: "学校で賞をもらったことがありますか。",
    translationAnswer: "いいえ、ありません。",
    point: "win－won－won も一緒に覚えよう。"
  },
  {
    id: "response_224",
    category: "助動詞",
    topic: "助動詞（can）",
    question: "Can your brother solve this math problem?",
    response: "Yes, he (      ).",
    answer: ["can"],
    completedResponse: "Yes, he can.",
    translationQuestion: "お兄さん（弟）はこの数学の問題を解けますか。",
    translationAnswer: "はい、解けます。",
    point: "solve a problem は重要表現。"
  },
  {
    id: "response_225",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your mother usually buy bread?",
    response: "She (      ) it at a bakery.",
    answer: ["Where", "buys"],
    completedResponse: "Where does your mother usually buy bread?She buys it at a bakery.",
    translationQuestion: "お母さんは普段どこでパンを買いますか。",
    translationAnswer: "パン屋で買います。",
    point: "「買う」が buys のヒントです。"
  },
  {
    id: "response_226",
    category: "現在進行形",
    topic: "現在進行形",
    question: "Are your classmates studying in the library now?",
    response: "Yes, they (      ).",
    answer: ["are"],
    completedResponse: "Yes, they are.",
    translationQuestion: "クラスメートは今、図書館で勉強していますか。",
    translationAnswer: "はい、勉強しています。",
    point: "現在進行形は be動詞で答える。"
  },
  {
    id: "response_227",
    category: "5W1H",
    topic: "5W1H",
    question: "(      ) do you usually go shopping with?",
    response: "I (      ) with my mother.",
    answer: ["Who", "go"],
    completedResponse: "Who do you usually go shopping with?I go with my mother.",
    translationQuestion: "普段誰と買い物へ行きますか。",
    translationAnswer: "母と行きます。",
    point: "「行く」が go のヒントです。"
  },
  {
    id: "response_228",
    category: "助動詞",
    topic: "助動詞（should）",
    question: "Should we practice speaking English every day?",
    response: "Yes, we (      ).",
    answer: ["should"],
    completedResponse: "Yes, we should.",
    translationQuestion: "毎日英語を話す練習をした方がいいですか。",
    translationAnswer: "はい、その方がいいです。",
    point: "practice ～ing の形も覚えよう。"
  },
  {
    id: "response_229",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your grandfather usually spend his evenings?",
    response: "He (      ) books and watches TV.",
    answer: ["How", "reads"],
    completedResponse: "How does your grandfather usually spend his evenings?He reads books and watches TV.",
    translationQuestion: "おじいさんは夕方を普段どのように過ごしますか。",
    translationAnswer: "本を読んだりテレビを見たりして過ごします。",
    point: "「本を読む」が reads のヒントです。"
  },
  {
    id: "response_230",
    category: "比較",
    topic: "比較",
    question: "Is your English class more enjoyable than your history class?",
    response: "Yes, it (      ).",
    answer: ["is"],
    completedResponse: "Yes, it is.",
    translationQuestion: "英語の授業は歴史の授業より楽しいですか。",
    translationAnswer: "はい、そうです。",
    point: "more enjoyable のような比較級にも慣れておこう。"
  },
  {
    id: "response_231",
    category: "5W1H",
    topic: "5W1H（三単現）",
    question: "(      ) does your English teacher always tell students to keep studying every day?",
    response: "She (      ) daily practice leads to success.",
    answer: ["Why", "believes"],
    completedResponse: "Why does your English teacher always tell students to keep studying every day?She believes daily practice leads to success.",
    translationQuestion: "英語の先生はなぜ毎日勉強を続けるように言うのですか。",
    translationAnswer: "毎日の積み重ねが成功につながると信じているからです。",
    point: "「信じている」が believes のヒントです。"
  }
];

window.responseTrainingBank = normalizeResponseTrainingBank([
  ...responseTrainingBaseItems,
  ...responseTrainingAppendedItems
]);
